lastmile-ai/aiconfig

- README.md
- python/README.md
Update to Readme
Basic update to readme to run this repo locally.
> Update to Readme

- python/src/aiconfig/AIConfigSettings.py
- python/src/aiconfig/__init__.py
[Python] Ease of Use Changes
- Modified imports in __init__.py
- Updated import in test
This diff Allows imports to be smaller and easier to use.
`from aiconfig.AIConfigSettings import AIConfig` -> `from aiconfig import AIConfig`
> [Python] Ease of Use Changes

- python/src/aiconfig/Config.py
- python/src/aiconfig/schema.py
[Python] Minor Usability Updates
- Updated `config.Save()` to make it more user friendly
- - Pretty Print to file as opposed to cramming everything in one line, with indentation of 2 (TS impl uses indent of 2 as well).
- - Exclude Null and None values when saving to disk
- Type update for `execution_count` in `ExecuteResult`
- - `float` -> `int`
Usability and alignment with library reqs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/94).
* #96
* #95
* __->__ #94
> [Python] Minor Usability Updates

- aiconfig-docs/docs/introduction/basics.md
- aiconfig-docs/docs/introduction/getting-started.md
[Docs][2/n] AIConfig Getting Started
Add a Getting Started guide for AIConfig
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/102).
* __->__ #102
* #101
> [Docs][2/n] AIConfig Getting Started

- aiconfig-docs/docs/introduction/getting-started.md
- aiconfig-docs/src/components/HomepageFeatures/index.tsx
[Docs][3/n] AIConfig landing page
Add 3 key value props
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/103).
* __->__ #103
* #102
* #101
> [Docs][3/n] AIConfig landing page

- cookbook/Chain-of-Verification/Chain_of_Verification_Pipeline.ipynb
- cookbook/Chain-of-Verification/README.md
- cookbook/Chain-of-Verification/cove_config.json
Attached: 
- readme 
- aiconfig
- .ipynb
> Chain of Verification Cookbook

- aiconfig-docs/docs/introduction/getting-started.md
[AI Config Docs] Restructured Getting Started section
same content -- if any, minor tweaks. restructured to be instruction-style.
> [AI Config Docs] Restructured Getting Started section

- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/default_parsers/palm.py
- python/src/aiconfig/model_parser.py
[Python] Update serialize to Async
Updated serialize() method signatures to async wherever it was not already updated.
- `def serialize` -> `async def serialize`
- added awaits where necessary
- Updated test to `await` serialize
callback executions are async. Must also be called from an async method.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/117).
* #120
* #118
* #109
* #108
* #107
* #119
* __->__ #117
> [Python] Update serialize to Async

- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/default_parsers/parameterized_model_parser.py
- python/tests/aiconfigs/basic_chatgpt_query_config.json
- python/tests/aiconfigs/parametrized_data_config.json
- python/tests/conftest.py
- python/tests/test_load_config.py
- test.ipynb
[Python] remove old code from  run_with_dependencies
- align run_with_dependencies impl with new changes
- updated stream calculation logic in openai model parser
- - updated test
> [Python] remove old code from  run_with_dependencies

- cookbook/Multi-LLM-Consistency/README.md
- cookbook/Multi-LLM-Consistency/multi_llm_consistency.json
> Initial Commit for Multi LLM Consistency cookbook

- aiconfig-docs/docs/introduction/getting-started.md
updating parameter (include_output) -> (include_outputs)
> Updating config.save parameter

- aiconfig-docs/docusaurus.config.js
[Docs] Add gtag and Discord
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/131).
* #132
* __->__ #131
* #130
* #129
* #128
> [Docs] Add gtag and Discord

- aiconfig-docs/docusaurus.config.js
- aiconfig-docs/src/css/custom.scss
[Docs] Fix highlighting of right nav bar
Thanks Zak for the fix!
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/132).
* __->__ #132
* #131
* #130
* #129
* #128
> [Docs] Fix highlighting of right nav bar

- aiconfig-docs/docusaurus.config.js
- aiconfig-docs/src/css/custom.scss
[Docs] Add Algolia text search
See https://docusaurus.io/docs/search#using-algolia-docsearch for more info
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/133).
* __->__ #133
* #132
* #131
* #130
* #129
* #128
> [Docs] Add Algolia text search

- aiconfig-docs/docusaurus.config.js
[Docs] Set baseUrl to '/'
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/134).
* __->__ #134
* #133
* #132
* #131
* #130
* #129
* #128
> [Docs] Set baseUrl to '/'

- .github/workflows/pr_python.yml
- .github/workflows/pr_typescript.yml
- .github/workflows/test-deploy-docs.yml
- README.md
Add build badges to readme
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/137).
* __->__ #137
* #136
* #134
* #133
* #132
* #131
* #130
* #129
* #128
> Add build badges to readme

- aiconfig-docs/docs/extensibility/callback-handler-guide.md
[Docs] Quick change to trigger docs rebuild
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/139).
* __->__ #139
* #138
* #137
* #136
* #134
* #133
* #132
* #131
* #130
* #129
* #128
> [Docs] Quick change to trigger docs rebuild

- aiconfig-docs/docusaurus.config.js
[Docs] Simplify algolia search config
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/144).
* __->__ #144
* #140
* #139
* #138
* #137
* #136
* #134
* #133
* #132
* #131
* #130
* #129
* #128
> [Docs] Simplify algolia search config

- aiconfig-docs/docusaurus.config.js
Algolia search key fix
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/146).
* __->__ #146
* #145
* #144
* #140
* #139
* #138
* #137
* #136
* #134
* #133
* #132
* #131
* #130
* #129
* #128
> Algolia search key fix

- typescript/lib/config.ts
- typescript/lib/modelParser.ts
- typescript/lib/modelParserRegistry.ts
- typescript/lib/parsers/openai.ts
[Typescript] Changes to make the getting started guide start working
The schema update makes every field on a prompt besides Name and Input optional. Changes in this diff reflect this update.
> [Typescript] Changes to make the getting started guide start working

- README.md
[README] More Getting Started
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/150).
* __->__ #150
* #148
> [README] More Getting Started

- README.md
- aiconfig-docs/docs/introduction/getting-started.md
- aiconfig-docs/src/css/custom.scss
[README] Start adding step-by-step getting started
Also fix css (thanks Zak) for mobile rendering.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/151).
* __->__ #151
* #150
* #148
> [README] Start adding step-by-step getting started

- aiconfig-docs/docs/introduction/basics.md
- aiconfig-docs/docs/introduction/getting-started.md
- aiconfig-docs/docs/overview/ai-config-format.md
[Docs] Remove some links to empty pages
Will be added back once pages are populated
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/157).
* __->__ #157
* #156
* #151
* #150
* #148
> [Docs] Remove some links to empty pages

- aiconfig-docs/src/css/custom.scss
[Docs] Fix navbar in mobile
Thanks @Zak for the fix!
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/160).
* __->__ #160
* #157
* #156
* #151
* #150
* #148
> [Docs] Fix navbar in mobile

- cookbook/Teaching Assistant/README.md
- cookbook/Teaching Assistant/assistant_aiconfig.json
- cookbook/Teaching Assistant/assistant_app.py
- cookbook/Teaching Assistant/create_config.py
- cookbook/Teaching Assistant/requirements.txt
[AI Config Cookbook] Prompt Routing Demo
This is a simple demo of prompt routing:
- Create config from scratch (create_config.py)
- Build app to handle prompt routing logic which leverages config (assistant_app.py)
- Host app on streamlit once approved
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/141).
* #164
* #161
* #149
* __->__ #141
> [AI Config Cookbook] Prompt Routing Demo

- README.md
[README] More or less complete readme
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/167).
* __->__ #167
* #160
* #157
* #156
* #151
* #150
* #148
> [README] More or less complete readme

- cookbook/Getting-Started/README.md
- cookbook/Getting-Started/getting_started.ipynb
- cookbook/Getting-Started/travel.aiconfig.json
[AI Config Cookbook] Getting Started notebook (python)
added .ipynb for getting started
> [AI Config Cookbook] Getting Started notebook (python)

- python/.gitignore
- python/requirements.txt
- python/src/aiconfig/Config.py
- python/src/aiconfig/__init__.py
- python/src/aiconfig/callback.py
- python/src/aiconfig/default_parsers/openai.py
[Python][Callbacks][4/n] Add Callback events to openai ModelParser
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/109).
* #120
* __->__ #109
* #108
* #107
* #119
> [Python][Callbacks][4/n] Add Callback events to openai ModelParser

- python/.gitignore
- python/requirements.txt
- python/src/aiconfig/Config.py
- python/src/aiconfig/__init__.py
- python/src/aiconfig/callback.py
[Python][Callbacks][2/n] Add CallbackManager to AIConfigRuntime
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/107).
* #120
* #109
* #108
* __->__ #107
* #119
> [Python][Callbacks][2/n] Add CallbackManager to AIConfigRuntime

- python/.gitignore
- python/requirements.txt
- python/src/aiconfig/Config.py
- python/src/aiconfig/__init__.py
- python/src/aiconfig/callback.py
[Python][Callbacks][3/n] Add callback events to AIConfigRuntime
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/108).
* #120
* #109
* __->__ #108
* #107
* #119
> [Python][Callbacks][3/n] Add callback events to AIConfigRuntime

- python/.gitignore
- python/requirements.txt
- python/src/aiconfig/__init__.py
- python/src/aiconfig/callback.py
[Python][Callbacks][1/n] CallbackManager impl
For context, the callback typehint is defined as:
`Callback = Callable[[CallbackEvent], Awaitable]`
In laymans terms this means an async function that takes in a `CallbackEvent` (no output types are defined here).
Some python stuff going on here. When you define an async function, its really a function that returns a coroutine. a `coroutine` conforms to type `Awaitable`
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/119).
* #120
* #109
* #108
* #107
* __->__ #119
> [Python][Callbacks][1/n] CallbackManager impl

- Extensions/HuggingFace/python/hf.py
- Extensions/HuggingFace/python/requirements.txt
- cookbook/HuggingFace/hf.py
- cookbook/HuggingFace/python/ask-mistral.py
- cookbook/HuggingFace/python/hf.py
[Extensions][Python] hf
Standalone extension.
cookbook clones the extension and includes a script. Needs polish
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/174).
* #175
* __->__ #174
* #165
> [Extensions][Python] hf

- typescript/index.ts
- typescript/package.json
- typescript/yarn.lock
[node] Update package to v1.0.2
Some minor changes and publish package on npm
> [node] Update package to v1.0.2

- cookbooks/HuggingFace/Mistral-aiconfig.json
- cookbooks/HuggingFace/python/ask-mistral.py
- python/pyproject.toml
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/hf.py
[Py] HuggingFaceTextGenerationParser as a default parser
Bring back HuggingFaceTextGenerationParser into AIConfig.
Discussed offline @Saquadri
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/187).
* #188
* __->__ #187
* #185
> [Py] HuggingFaceTextGenerationParser as a default parser

- cookbooks/Create-AIConfig-Programmatically/README.md
- cookbooks/Create-AIConfig-Programmatically/create_aiconfig_programmatically.ipynb
- cookbooks/Create-AIConfig-Programmatically/programmatic.aiconfig.json
Cookbook for creating config programmatically
> Cookbook for creating config programmatically

- cookbook/Workshop-Demo/Workshop-1/README.md
[AIConfig Workshop] Create README.md
Creating a README.md for Workshop 1.
Students can access the Workbook + Colab and instructions here during the live workshop since we won't have a chat interface to send them these links.
> [AIConfig Workshop] Create README.md

- python/pyproject.toml
- python/requirements.txt
- python/src/aiconfig/ChatCompletion.py
- python/src/aiconfig/default_parsers/openai.py
- python/tests/conftest.py
- python/tests/parsers/test_openai_util.py
- python/tests/test_run_config.py
[Python] update AIConfig & OpenAI model parser compatibility with sdk api version 1.0.0
title
1. Modified ChatCompletion api to match the new API structure
- `openai.ChatCompletions.create()` -> `openai.chat.completions.create()`
2. Refactored tests
- New method requires env API Key to be set even when attempting to mock
- - set env before mocking method. Diff looks huge due to spacing changes but there's no other changes made there
- Modified mock ChatCompletion request to mimic new typing (see next bullet)
3. OpenAI API response is now backed with Pydantic Typing.
- AIConfig uses dicts for non core types (core types defined in schema.py). Now, On response from Completion API, Updated to convert response to dict and exclude any values that are None typed
- - ex: `response = …
> [Python] update AIConfig & OpenAI model parser compatibility with sdk api version 1.0.0

- typescript/lib/callback.ts
- typescript/lib/config.ts
- typescript/lib/parsers/openai.ts
- typescript/package.json
- typescript/yarn.lock
[Typescript][Callbacks][4/n] Add Callback events to OpenAI Model Parser
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/116).
* #198
* __->__ #116
* #113
* #112
* #111
* #115
> [Typescript][Callbacks][4/n] Add Callback events to OpenAI Model Parser

- typescript/lib/callback.ts
- typescript/lib/config.ts
- typescript/package.json
- typescript/yarn.lock
[Typescript][Callbacks][2/n] Add CallbackManager to AIConfigRuntime
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/112).
* #198
* #116
* #113
* __->__ #112
* #111
* #115
> [Typescript][Callbacks][2/n] Add CallbackManager to AIConfigRuntime

- workshops/Stanford/competition/README.md
Adding readme for stanford competition
> Adding readme for stanford competition

- workshops/Stanford/README.md
> Update Workshop README.md

- workshops/Stanford/README.md
Update colab notebook link for workshop
> Update colab notebook link for workshop

- workshops/Stanford/README.md
> Update readme for workshop

- typescript/index.ts
[typescript] update exports
Export *
- utils.ts
- - util methods. Important method `extractOverrideSettings` for writing a model parser
- hf.ts
- - hugging face text gen parser
> [typescript] update exports

- README.md
Update readme for callbacks
title
> Update readme for callbacks

- aiconfig-docs/docs/introduction/usage-guide.md
- aiconfig-docs/docs/overview/create-an-aiconfig.md
[Docs] FAQ for usage and creating an aiconfig page
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/221).
* __->__ #221
* #217
> [Docs] FAQ for usage and creating an aiconfig page

- README.md
[readme] Update Callback section with python code snippets
title
> [readme] Update Callback section with python code snippets

- typescript/package.json
Update Node package
Publish 1.0.3 with callbacks
> Update Node package

- aiconfig-docs/core/tabConstants.js
- aiconfig-docs/docs/overview/create-an-aiconfig.md
- typescript/package.json
[Docs] Add "Create an aiconfig" section
Guide for creating an aiconfig from scratch
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/228).
* __->__ #228
* #227
> [Docs] Add "Create an aiconfig" section

- aiconfig-docs/docs/overview/define-prompt-chain.md
- python/demo/PaLM-Chat-WhatAreTransformers.json
[Docs] Add "Prompt chain" section
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/229).
* __->__ #229
* #228
* #227
> [Docs] Add "Prompt chain" section

- cookbooks/Custom-Callbacks/python/custom_callbacks.ipynb
- cookbooks/Custom-Callbacks/travel.aiconfig.json
[cookbooks] Logging
not sure if This should be a cookbook but created one anyway
> [cookbooks] Logging

- aiconfig-docs/docs/introduction/usage-guide.md
- aiconfig-docs/docs/overview/parameters-and-chaining.md
[Docs] Add "Passing data into prompts" section
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/231).
* __->__ #231
* #229
* #228
* #227
> [Docs] Add "Passing data into prompts" section

- README.md
[docs][readme] model parsers getting started
Basics of getting started for writing a model parser. It would make sense to have a more in depth guide section that handholds a user in writing a model parser
> [docs][readme] model parsers getting started

- aiconfig-docs/docs/introduction/basics.md
- aiconfig-docs/docs/overview/parameters.md
[Docs] A few fixes
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/232).
* __->__ #232
* #231
* #229
* #228
* #227
> [Docs] A few fixes

- aiconfig-docs/docs/introduction/getting-started.md
- aiconfig-docs/docs/overview/ai-config-format.md
- aiconfig-docs/docs/overview/create-an-aiconfig.md
- aiconfig-docs/docs/overview/define-prompt-chain.md
- aiconfig-docs/docs/overview/monitoring-aiconfig.md
- aiconfig-docs/docs/overview/parameters.md
- aiconfig-docs/docs/overview/run-aiconfig.md
- aiconfig-docs/docs/overview/use-aiconfig.md
[Docs] Add "Run a prompt" section
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/233).
* __->__ #233
* #232
* #231
* #229
* #228
* #227
> [Docs] Add "Run a prompt" section

- aiconfig-docs/docs/overview/monitoring-aiconfig.md
[Docs] Add "monitoring and tracing" section
> [Docs] Add "monitoring and tracing" section

- .gitignore
- cookbooks/llama/python/ask_llama.py
- cookbooks/llama/python/llama.py
- extensions/llama/python/llama.py
- extensions/llama/python/requirements.txt
[AIC-PY][1/n] llama extension+cookbook
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/219).
* #238
* __->__ #219
> [AIC-PY][1/n] llama extension+cookbook

- .vscode/extensions.json
- CONTRIBUTING.md
- python/requirements.txt
[AIC-py] py linter
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/223).
* #240
* #238
* __->__ #223
> [AIC-py] py linter

- cookbooks/llama/typescript/README.md
- cookbooks/llama/typescript/ask-llama.ts
> Add Video to Cookbook README

- workshops/berkeley/README.md
- workshops/berkeley/competition/README.md
Adding berkeley workshop directory
> Adding berkeley workshop directory

- workshops/berkeley/README.md
Links to go to Berkeley Content (workbook, notebook, etc.)
> Update Berkeley Workshop README.md

- .gitignore
- .vscode/extensions.json
- CONTRIBUTING.md
- cookbooks/llama/python/ask_llama.py
- extensions/llama/python/llama.py
- python/requirements.txt
[AIC-PY][2/n] llama extension+cookbook: streaming
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/238).
* #224
* #240
* __->__ #238
* #223
> [AIC-PY][2/n] llama extension+cookbook: streaming

- cookbooks/Cli-Mate/README.md
- cookbooks/Cli-Mate/cli-mate.aiconfig.json
- cookbooks/Cli-Mate/cli-mate.py
- cookbooks/llama/python/ask_llama.py
- extensions/llama/python/llama.py
- python/requirements.txt
[AIC-PY] cli-mate demo
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/224).
* __->__ #224
* #240
> [AIC-PY] cli-mate demo

- cookbooks/llama/python/ask_llama.py
- extensions/llama/python/llama.py
[AIC-PY][3/n] llama extension+cookbook: remember
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/240).
* #224
* __->__ #240
> [AIC-PY][3/n] llama extension+cookbook: remember

- aiconfig-docs/docs/basics.md
- aiconfig-docs/docusaurus.config.js
Link to Extensibility Entries from /basics Page
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/249).
* #250
* __->__ #249
* #246
> Link to Extensibility Entries from /basics Page

- cookbooks/Create-AIConfig-Programmatically/create_aiconfig_programmatically.ipynb
Updating create_aiconfig_programmatically to use new version
> Updating create_aiconfig_programmatically to use new version

- README.md
- aiconfig-docs/docs/extensibility.md
[Docs] Update Extensibility guide
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/253).
* __->__ #253
* #252
> [Docs] Update Extensibility guide

- cookbooks/RAG-with-AIConfig/RAG_with_AIConfig.ipynb
- cookbooks/RAG-with-AIConfig/README.md
- cookbooks/RAG-with-AIConfig/rag_aiconfig.json
[AIConfig Cookbook] RAG Notebook
from workshop, extracted the RAG section and created a cookbook.
> [AIConfig Cookbook] RAG Notebook

- cookbooks/Function-Calling-OpenAI/Function_Calling_with_OpenAI.ipynb
- cookbooks/Function-Calling-OpenAI/README.md
- cookbooks/Function-Calling-OpenAI/function-call.aiconfig.json
[AIConfig Cookbooks] Python Function Calling Cookbook
Created Colab notebook for function calling with OpenAI. Same example as the typescript (located in typescript/demo).
> [AIConfig Cookbooks] Python Function Calling Cookbook

- README.md
[README] improvements and better navigation
> [README] improvements and better navigation

- python/src/aiconfig/default_parsers/hf.py
[python][easy] hf update update method from refactor
generate_model_metadata -> get_model_metadata
This wasn't updating during previous refactor
> [python][easy] hf update update method from refactor

- README.md
[README] Some more cleanup of lists and links
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/263).
* __->__ #263
* #261
* #259
> [README] Some more cleanup of lists and links

- README.md
[README] Get video rendering on GitHub
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/266).
* __->__ #266
* #263
* #261
* #259
> [README] Get video rendering on GitHub

- cookbooks/Multi-LLM-Consistency/Multi-LLM Consistency Prompting & LLM-based Quorum_aiconfig.json
- pyrightconfig.json
- python/src/aiconfig/Config.py
- python/src/aiconfig/__init__.py
- python/src/aiconfig/default_parsers/palm.py
[python] {wip} fix palm model parser
- Updated Palm Model Parsers in line with rest of the sdk
- Added Callbacks
- Hasn't been updated in a while
- google api has changed
> [python] {wip} fix palm model parser

- README.md
made minor changes to video (wont show pip install)
> [readme] Updated getting started video

- README.md
- aiconfig-docs/docs/getting-started.md
- python/README.md
- python/pyproject.toml
- typescript/README.md
- typescript/package.json
Latest package updates, and minor readme cleanup
> Latest package updates, and minor readme cleanup

- aiconfig-docs/docs/getting-started.md
- python/README.md
[README] Fix code snippet
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/273).
* __->__ #273
* #272
> [README] Fix code snippet

- README.md
> [README] Code snippet updates

- README.md
- python/README.md
- typescript/README.md
[README] minor updates
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/275).
* __->__ #275
* #274
> [README] minor updates

- README.md
Moved API key setup to earlier
Felt a bit out of place in the general core features
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/277).
* __->__ #277
* #276
> Moved API key setup to earlier

- README.md
Explicit instructions on creating a new file and running from terminal
More explicit. Also changed `pip` to `pip3`
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/276).
* #277
* __->__ #276
> Explicit instructions on creating a new file and running from terminal

- README.md
> [Readme] Discord Invite

- python/src/aiconfig/default_parsers/dalle.py
[dall-e parser][2/n] Do not read streaming options
I don't think that the image generation, edit, or variations support streaming for the Dall-E 2/3 APIs. I just removed this logic because we could have streaming enabled for other prompts (ex: text-based ones)
Even for image variations (dall-e 2), the examples use a BytesIO stream, but only to get the final value of it. If you look at the API we need to pass in a full file: https://platform.openai.com/docs/guides/images/using-in-memory-image-data
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/290).
* #297
* #294
* __->__ #290
> [dall-e parser][2/n] Do not read streaming options

- python/README_dev.md
Make it clearer for python noobs like me
> Update Python Dev README

- CODEOWNERS
+ CODEOWNERS
Add the eng team as owners for now. This makes every PR have reviewers automatically.
This can be configured to set different reviewers for different files/globs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/304).
* #313
* __->__ #304
> + CODEOWNERS

- typescript/index.ts
[ts][easy] update root exports
update root exports to encompass callbacks and parameterize utils.
Some types are not exported. When developing with aiconfig, modules or types won't be importable unless done manually through the dist folder
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/312).
* #314
* __->__ #312
> [ts][easy] update root exports

- python/requirements.txt
[aic-py] add missing deps
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/313).
* #310
* #309
* __->__ #313
> [aic-py] add missing deps

- .lint_glob_excludes
- .vscode/extensions.json
- .vscode/settings.json
- pyrightconfig.json
[aic-py] lint, pyright, formatting settings
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/309).
* #310
* __->__ #309
> [aic-py] lint, pyright, formatting settings

- python/src/aiconfig/default_parsers/openai.py
[py] streaming refactor wip
refactor stream check to respect stream options
streaming options wasn't respecting the stream attribute
> [py] streaming respect stream value

- cookbooks/Chain-of-Verification/Chain_of_Verification_GPT4_Template.ipynb
- cookbooks/Chain-of-Verification/README.md
[cookbook] added github link to config.json
added github link to config.json
updated example in notebook
minor changes to readme
> [cookbook] added github link to config.json

- cli/README.md
- cli/aiconfig-editor/package.json
- cli/aiconfig-editor/pages/api/aiconfig/load.ts
- cli/aiconfig-editor/pages/api/aiconfig/save.ts
- cli/aiconfig-editor/pages/editor.tsx
- cli/aiconfig-editor/pages/index.tsx
- cli/aiconfig-editor/travel.aiconfig.json
- cli/aiconfig-editor/yarn.lock
- cli/index.ts
- cli/package.json
Updating build script for CLI
This gets a JS version of the CLI and editor working (so no typescript dependencies, etc.).
Work in progress: Bundling dist with aiconfig npm repo and placing script into aiconfig/.bin folder to use as proper cli on publish to npm.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/172).
* __->__ #172
* #171
> Updating build script for CLI

- cli/README.md
- cli/aiconfig-editor/package.json
- cli/aiconfig-editor/pages/api/aiconfig/load.ts
- cli/aiconfig-editor/pages/api/aiconfig/save.ts
- cli/aiconfig-editor/pages/editor.tsx
- cli/aiconfig-editor/pages/index.tsx
- cli/aiconfig-editor/travel.aiconfig.json
- cli/aiconfig-editor/yarn.lock
Basic initial editor for aiconfig
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/171).
* #172
* __->__ #171
> Basic initial editor for aiconfig

- cookbooks/Getting-Started/README.md
- cookbooks/Getting-Started/getting_started.ipynb
Update Getting Started notebook
Fixes #335
> Update Getting Started notebook

- cookbooks/HuggingFace/python/ask-mistral.py
- extensions/llama/python/llama.py
- python/demo/function_calling_demo.py
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/default_parsers/palm.py
- python/src/aiconfig/default_parsers/parameterized_model_parser.py
- python/src/aiconfig/util/config_utils.py
- python/src/aiconfig/util/params.py
- python/test.py
- python/tests/conftest.py
- python/tests/parsers/test_openai_util.py
- python/tests/test_library_helpers.py
- python/tests/test_load_config.py
- python/tests/test_programmatically_create_an_AIConfig.py
- python/tests/test_registry.py
- python/tests/test_resolve.py
- python/tests/test_run_config.py
[ez][2/n][AIC-py] rm unused imports
> [ez][2/n][AIC-py] rm unused imports

- cookbooks/OpenAI-ChatCompletion-AIConfigWrapper/aiconfig.json
- cookbooks/OpenAI-ChatCompletion-AIConfigWrapper/function_call.aiconfig.json
- cookbooks/OpenAI-ChatCompletion-AIConfigWrapper/openai_wrapper.ipynb
- cookbooks/OpenAI-ChatCompletion-AIConfigWrapper/storytelling.aiconfig.json
Some fixes for openai wrapper cookbook
* Add cell to import python-aiconfig package
* Add outputs
* Add example aiconfigs that are created with openai introspection.
Still requires a bunch more cleanup and better comments
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/349).
* __->__ #349
* #347
> Some fixes for openai wrapper cookbook

- cookbooks/Function-Calling-OpenAI/Function_Calling_with_OpenAI.ipynb
- cookbooks/Getting-Started/getting_started.ipynb
- cookbooks/RAG-with-AIConfig/RAG_with_AIConfig.ipynb
3/n Rag With AIconfig
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/339).
* __->__ #339
* #338
* #337
> 3/n Rag With AIconfig

- cookbooks/Getting-Started/getting_started.ipynb
[cookbook] use .env 1/n getting started
import os, import dotenv
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/337).
* #339
* #338
* __->__ #337
> [cookbook] use .env 1/n getting started

- cookbooks/Function-Calling-OpenAI/Function_Calling_with_OpenAI.ipynb
- cookbooks/Getting-Started/getting_started.ipynb
2/n Function calling
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/338).
* #339
* __->__ #338
* #337
> 2/n Function calling

- cookbooks/Function-Calling-OpenAI/Function_Calling_with_OpenAI.ipynb
- cookbooks/Function-Calling-OpenAI/README.md
- cookbooks/Function-Calling-OpenAI/function-call.aiconfig.json
Improve Function Calling cookbook
* Better Colab notebook
* Added Colab badge to readme
> Improve Function Calling cookbook

- .github/workflows/pr_python.yml
- python/tests/parameterization/test_parameterization.py
Higher Fidelity test script for PY
Updated github action script for python to build package and install package instead of creating a dynamic link to source code
added a space in test file to kick off action. Otherwise it won't run on this diff
Higher Fidelity testing
> Higher Fidelity test script for PY

- .github/workflows/main-typescript.yml
Github Action TS Tests on Main
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/368).
* __->__ #368
* #366
> Github Action TS Tests on Main

- README.md
Update ReadMe Test Badges to reflect tests on Main
title
> Update ReadMe Test Badges to reflect tests on Main not latest PR

- python/pyproject.toml
- python/requirements.txt
Link pyproject to requirements.txt in Python
Original comment from Ankush in https://github.com/lastmile-ai/aiconfig/pull/344#discussion_r1409410409
> Link pyproject to requirements.txt in Python

- python/requirements-dev.txt
- python/requirements.txt
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/hugging_face_transformers/text_generation.py
[hf parsers][1/n] Transformer for text generation
This is super basic, just getting started.
1) Have not supported streaming
2) Have not supported using any of the completion params in the generator call
3) Hardcoded to using the 'gpt2' model, will make it more generic in the future
4) Have not added automated test yet for serialize and loading the AIConfig
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/344).
* #380
* #379
* #351
* #363
* #348
* #345
* __->__ #344
> [hf parsers][1/n] Transformer for text generation

- python/requirements-dev.txt
- python/requirements.txt
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/hugging_face_transformers/text_generation.py
- python/src/aiconfig/registry.py
- typescript/lib/modelParserRegistry.ts
Add more docstrings to ModelParserRegistry
Making this easier to understand what's going on
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/363).
* #380
* #379
* #351
* __->__ #363
* #348
* #345
* #344
> Add more docstrings to ModelParserRegistry

- extensions/README.md
- python/requirements-dev.txt
- python/requirements.txt
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/hugging_face_transformers/text_generation.py
- python/src/aiconfig/registry.py
- typescript/lib/modelParserRegistry.ts
Add README file for how to build extensions
Do we have a tutorial on how to build one which we can link to?
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/379).
* #380
* __->__ #379
* #351
* #363
* #348
* #345
* #344
> Add README file for how to build extensions

- extensions/HuggingFace/python/requirements.txt
- extensions/HuggingFaceTransformers/LICENSE
- extensions/HuggingFaceTransformers/python/pyproject.toml
- extensions/HuggingFaceTransformers/python/requirements.txt
Add pyproject.toml to HuggingFaceTransformers extension
Need this so we can publish
> Add pyproject.toml to HuggingFaceTransformers extension

- extensions/HuggingFaceTransformers/python/pyproject.toml
- extensions/HuggingFaceTransformers/python/src/aiconfig_extension_hugging_face_transformers/__init__.py
[hf parser] Add exported class to __init__ in text generation extension
Need this or else the downstream files that import won't be able to see anything in this module
> [hf parser] Add exported class to __init__ in text generation extension

- cli/aiconfig-editor/pages/editor.tsx
- cli/aiconfig-editor/pages/index.tsx
- cli/aiconfig-editor/src/components/EditorContainer.tsx
- cli/aiconfig-editor/tsconfig.json
Add an `EditorContainer` component, under which the editor proper will be rendered. Sibling components of the `EditorContainer`, rendered in `editor.tsx` will be things like the left file tree.
- Editor still renders the same
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/388).
* #391
* #390
* #389
* __->__ #388
> [1/n] Editor Scaffolding - Add EditorContainer

- cli/aiconfig-editor/pages/api/aiconfig/load.ts
- cli/aiconfig-editor/pages/api/aiconfig/save.ts
- cli/aiconfig-editor/pages/editor.tsx
- cli/aiconfig-editor/pages/index.tsx
- cli/aiconfig-editor/src/components/EditorContainer.tsx
- cli/aiconfig-editor/src/shared/serverTypes.ts
- cli/aiconfig-editor/tsconfig.json
Update the request and responses types for consistency. This was part of another change that I scrapped (had an endpoint for changing prompt which I've since removed for now) but this change is still good to include
- Load/save still work
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/389).
* #391
* #390
* __->__ #389
* #388
> [2/n] Update Save/Load Req/Res Types

- python/src/aiconfig/eval/custom_eval/examples/travel/travel_eval.ipynb
- python/src/aiconfig/eval/lib.py
[AIC-py] test-suite style eval docs
https://colab.research.google.com/drive/16kMEX5KBMBBDCkV7rvLL-Ef7sn-KyP2Z
> [AIC-py] test-suite style eval docs

- extensions/HuggingFaceTransformers/python/pyproject.toml
- extensions/HuggingFaceTransformers/python/src/aiconfig_extension_hugging_face_transformers/text_generation.py
- python/src/aiconfig/schema.py
[ez] Bump version number to publish on PyPi
TSIA, want to do this after last few bug fixes
- https://github.com/lastmile-ai/aiconfig/pull/411
- https://github.com/lastmile-ai/aiconfig/pull/410
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/414).
* __->__ #414
* #411
* #410
> [ez] Bump version number to publish on PyPi

- python/src/aiconfig/Config.py
- python/src/aiconfig/schema.py
- python/tests/test_programmatically_create_an_AIConfig.py
- typescript/lib/config.ts
[ez] Add prompt name to error messages
Pretty simple. Should probably unify all the TS error messages, but just wanted to get this done first for now quickly. Added a TODO
> [ez] Add prompt name to error messages

- python/src/aiconfig/eval/examples/travel/travel_eval.ipynb
Add utils setup + api key for eval cookbook
TSIA, making it easier for n00bs!
> Add utils setup + api key for eval cookbook

- extensions/LLama-Guard/python/LICENSE
- extensions/LLama-Guard/python/README.md
- extensions/LLama-Guard/python/python/LICENSE
- extensions/LLama-Guard/python/python/README.md
- extensions/LLama-Guard/python/python/pyproject.toml
- extensions/LLama-Guard/python/python/requirements.txt
- extensions/LLama-Guard/python/python/src/aiconfig_extension_llama_guard/LLamaGuard.py
- extensions/LLama-Guard/python/python/src/aiconfig_extension_llama_guard/__init__.py
[extensions] LLama-Guard
Model Parser Extension for LLama-Guard
Loads LLama-Guard, a 7b model into memory
> [extensions] LLama-Guard

- typescript/lib/config.ts
[ts] random fixes
Fixes that needed updating. Found while implementing and Testing PaLM Model Parser
- AIConfigRuntime.`getModelParser()` wasn't returning anything
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/395).
* #377
* #396
* #397
* #394
* #376
* #375
* __->__ #395
> [ts] random fixes

- python/src/aiconfig/default_parsers/hf.py
2/n add default stream = True
default stream to true
> 2/n add default stream = True

- CHANGELOG.md
- python/pyproject.toml
- typescript/package.json
> changelog 12/11

- cli/aiconfig-editor/package.json
- cli/aiconfig-editor/src/components/EditorContainer.tsx
- cli/aiconfig-editor/src/components/prompt/PromptActionBar.tsx
- cli/aiconfig-editor/src/components/prompt/PromptContainer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/PromptInputConfigRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/PromptInputRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/schema_renderer/PromptInputAttachmentsSchemaRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/schema_renderer/PromptInputDataSchemaRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_metadata/PromptMetadataRenderer.tsx
- cli/aiconfig-editor/src/shared/prompt_schemas/OpenAIChatVisionModelParserPromptSchema.ts
- cli/aiconfig-editor/src/utils/promptUtils.ts
- cli/aiconfig-editor/travel.aiconfig.json
- cli/aiconfig-editor/yarn.lock
Update Prompt Card UI to Better Match Designs (Low-fi)
Low-fidelity UI update to better match the designs / layout to start off
Still quite a bit of work needed but this is better than everything being jumbled together while developing the components
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/482).
* __->__ #482
* #398
> Update Prompt Card UI to Better Match Designs (Low-fi)

- cookbooks/Gemini/Gemini.ipynb
- cookbooks/Gemini/README.md
- cookbooks/Gemini/gemini_demo.aiconfig.json
https://github.com/lastmile-ai/aiconfig/assets/129882602/18af5ecd-6107-480f-be20-cd067159e69c
> Adding a Gemini Cookbook, Readme, and Notebook

- python/src/aiconfig/eval/api/__init__.py
- python/src/aiconfig/eval/common.py
- python/src/aiconfig/eval/lib.py
- python/src/aiconfig/eval/metrics.py
- python/tests/test_eval.py
[AIC-py][eval] finishing touches / cleanup
> [AIC-py][eval] finishing touches / cleanup

- extensions/HuggingFaceTransformers/python/pyproject.toml
- extensions/HuggingFaceTransformers/python/requirements.txt
- extensions/HuggingFaceTransformers/python/src/aiconfig_extension_hugging_face_transformers/__init__.py
- extensions/HuggingFaceTransformers/python/src/aiconfig_extension_hugging_face_transformers/text_2_image.py
- extensions/HuggingFaceTransformers/python/src/aiconfig_extension_hugging_face_transformers/text_generation.py
- python/src/aiconfig/default_parsers/dalle.py
[hf parser] Add parser for text2Image
Copying a lot of what I did for the TextGeneration extension: https://github.com/lastmile-ai/aiconfig/tree/main/extensions/HuggingFaceTransformers
Referencing the API defined in
- https://huggingface.co/docs/diffusers/v0.24.0/en/api/pipelines/auto_pipeline#diffusers.AutoPipelineForText2Image
- https://huggingface.co/docs/diffusers/using-diffusers/conditional_image_generation
Test by rebasing onto https://github.com/lastmile-ai/aiconfig/pull/461
I also linked GH issues for each TODO as followups
> [hf parser] Add parser for text2Image

- extensions/HuggingFaceTransformers/python/src/aiconfig_extension_hugging_face_transformers/text_2_image.py
[hf parser] Text2Image: Use GPU if available
Based on Ankush's comments in https://github.com/lastmile-ai/aiconfig/pull/460#discussion_r1424810992
Wanted to make this a separate diff to show the effect it has in test plan. Tested by rabsing onto: https://github.com/lastmile-ai/aiconfig/pull/461
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/496).
* #461
* __->__ #496
> [hf parser] Text2Image: Use GPU if available

- README.md
[readme] fixed image and links
fixed image sizing
added links that were previously missing
> [readme] fixed image and links

- README.md
[README] Minor update to add new paragraph
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/500).
* __->__ #500
* #499
> [README] Minor update to add new paragraph

- aiconfig-docs/docs/overview/model-parsers.md
Adding a table of supported models. Links to root directories for extensions.
> Updating the supported model doc

- extensions/Gemini/python/LICENSE
- extensions/Gemini/python/README.md
- extensions/Gemini/python/pyproject.toml
- extensions/Gemini/python/requirements.txt
- extensions/Gemini/python/src/aiconfig_extension_gemini/Gemini.py
- extensions/Gemini/python/src/aiconfig_extension_gemini/__init__.py
[extensions][py] Gemini
[extensions][py] Gemini
Gemini Model Parser Extension
Supports Gemini Models.
Gemini api seems to only allow candidate of 1. This means number of outputs is always 1.
Gemini models are:
Gemini Pro
Gemini pro Visio (similar to gpt -4v)
This model parser supports Gemini Pro T2T functionality
Cookbook: https://github.com/lastmile-ai/aiconfig/tree/main/cookbooks/Gemini
#463
> [extensions][py] Gemini

- python/requirements.txt
- python/src/aiconfig/eval/common.py
- python/src/aiconfig/eval/lib.py
- python/src/aiconfig/eval/metrics.py
- python/tests/test_eval.py
[AIC-py][eval] robust function calls
main thing: call `run_thunk_safe()` for eval functions
- async, catch exceptions, timeout
- make a few important downstream changes, e.g. ID for logging/debugging
> [AIC-py][eval] robust function calls

- CHANGELOG.md
- python/pyproject.toml
- typescript/package.json
> Changelog 12/18/2023

- cli/aiconfig-editor/package.json
- cli/aiconfig-editor/pages/api/aiconfig/load.ts
- cli/aiconfig-editor/pages/api/aiconfig/save.ts
- cli/aiconfig-editor/pages/editor.tsx
- cli/aiconfig-editor/src/components/EditorContainer.tsx
- cli/aiconfig-editor/src/components/aiconfigReducer.ts
- cli/aiconfig-editor/src/components/prompt/PromptContainer.tsx
- cli/aiconfig-editor/src/components/prompt/TextRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/model_settings/ModelSettingsRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/model_settings/ModelSettingsSchemaRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/attachments/Attachment.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/attachments/AttachmentContainer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/attachments/AttachmentMetadata.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/attachments/AttachmentUploader.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/schema_renderer/PromptInputAttachmentsSchemaRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_metadata/PromptMetadataRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_outputs/PromptOutputsRenderer.tsx
- cli/aiconfig-editor/src/hooks/useSchemaState.ts
- cli/aiconfig-editor/src/shared/types.ts
- cli/aiconfig-editor/src/utils/dropzoneHelpers.ts
- cli/aiconfig-editor/src/utils/promptUtils.ts
- cli/aiconfig-editor/travel.aiconfig.json
- cli/aiconfig-editor/yarn.lock
[editor] Initial Output Rendering
Get prompt outputs to render. The main consideration here is that we can't really render directly based on the raw AIConfig outputs since those can be any arbitrary data defined by the model parsers. Instead, we add Client-specific types (mainly `ClientExecuteResult`) for the AIConfig which are constructed on load of the config, and which we will be able to properly handle rendering. For non-text outputs, we'll probably have an 'attachments' type to render those output attachments based on mimetype.
Side note -- maybe we just have a single type which can support both text & attachments? We should revisit if we have such models. This should do for now as a starting point.
--- …
> [editor] Initial Output Rendering

- cli/aiconfig-editor/package.json
- cli/aiconfig-editor/pages/api/aiconfig/save.ts
- cli/aiconfig-editor/src/components/EditorContainer.tsx
- cli/aiconfig-editor/src/components/prompt/model_settings/ModelSettingsRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/model_settings/ModelSettingsSchemaRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/attachments/Attachment.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/attachments/AttachmentContainer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/attachments/AttachmentMetadata.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/attachments/AttachmentUploader.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/schema_renderer/PromptInputAttachmentsSchemaRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_metadata/PromptMetadataRenderer.tsx
- cli/aiconfig-editor/src/hooks/useSchemaState.ts
- cli/aiconfig-editor/src/utils/dropzoneHelpers.ts
- cli/aiconfig-editor/src/utils/promptUtils.ts
- cli/aiconfig-editor/yarn.lock
[editor] Input Attachments Starting Point
Initial implementation for prompt input attachments rendering. This supports rendering existing attachments and adds an upload field to add new attachments or update existing attachments.
Some follow-ups (ordered by priority):
- Implement upload endpoint to actually store new attachments
- UI improvements
- Implement attachment metadata editing
https://github.com/lastmile-ai/aiconfig/assets/5060851/21d17037-45fa-446b-a204-e8f437842603
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/511).
* #515
* #514
* __->__ #511
* #510
> [editor] Input Attachments Starting Point

- cli/aiconfig-editor/package.json
- cli/aiconfig-editor/pages/api/aiconfig/save.ts
- cli/aiconfig-editor/src/components/EditorContainer.tsx
- cli/aiconfig-editor/src/components/SettingsPropertyRenderer.tsx
- cli/aiconfig-editor/src/components/aiconfigReducer.ts
- cli/aiconfig-editor/src/components/prompt/PromptActionBar.tsx
- cli/aiconfig-editor/src/components/prompt/PromptContainer.tsx
- cli/aiconfig-editor/src/components/prompt/PromptParametersRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/model_settings/ModelSettingsRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/model_settings/ModelSettingsSchemaRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_metadata/PromptMetadataRenderer.tsx
- cli/aiconfig-editor/src/shared/prompt_schemas/OpenAIChatModelParserPromptSchema.ts
- cli/aiconfig-editor/src/utils/promptUtils.ts
- cli/aiconfig-editor/yarn.lock
Model Settings Renderer Starting Point
Starting point for rendering prompt model settings. The SettingsRenderer is pretty much directly taken from lastmile without any significant changes; subsequent PRs will add additional renderers for types not yet supported (map, union)
- Supported settings render and correct values are persisted to the config:
https://github.com/lastmile-ai/aiconfig/assets/5060851/a35c43dc-9d0b-408e-9e4f-162c5e6a1342
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/545).
* __->__ #545
* #544
> Model Settings Renderer Starting Point

- cli/aiconfig-editor/pages/api/aiconfig/save.ts
Remove renderData from config on save
When saving the client typed config, we need to remove the `renderData` from the prompt outputs to ensure the renderData is not persisted to the config.
This should just be temporary until we have outputs structured to support proper rendering without these client-specific types/handling.
- saved a config with outputs and ensured no renderData is present in the outputs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/544).
* #545
* __->__ #544
> Remove renderData from config on save

- extensions/Gemini/python/src/aiconfig_extension_gemini/Gemini.py
1/n Gemini Update deserialize to take data in the form of completion params
Updated deserialize() in Gemini Model Parser to take in completion data from prompt input if it is already in the form of the Gemini Completion data
Now, you can specify input in the form of a request to gemini api, ie the parts.
Previously This was skipped due to a lack of understanding of how the api requests worked.
Validating 2 pieces of functionality with this test plan:
1. setting the generation config for Gemini in setings. Generation Config is gemini's way of defining settings like topP
2. Deserialize() can take in data just like the api, by setting "contents" in the prompt input.
--- …
> 1/n Gemini Update deserialize to take data in the form of completion params

- extensions/Gemini/python/requirements.txt
- extensions/Gemini/python/src/aiconfig_extension_gemini/Gemini.py
3/n pin Gemini dependency (google api)
Pin google-generative ai, the library used for Gemini
Anticipiating potential updates to the library, its prudent to pin its current version.
Additionally, it ensures that all users operate on the same, specified version of the API.
I ran `pip list | grep google-generativeai` to find the version of the library that was installed locally.
```
ankush@ap-mbp python % pip list | grep google-generativeai
google-generativeai                           0.3.1
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/534).
* #558
* __->__ #534
* #531
* #532
> 3/n pin Gemini dependency (google api)

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/scripts/aiconfig_cli.py
[AIC-py][editor] bundle easy changes
- make aiconfig runtime
- log to file
- make path relative to aiconfig root
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/556).
* #567
* #565
* #563
* #560
* __->__ #556
* #555
> [AIC-py][editor] bundle easy changes

- cookbooks/Gemini/Gemini.ipynb
- cookbooks/Getting-Started/travel.aiconfig.json
remove unintended changes to Gemini cookbook
Mistakenly updated cookbook.
Browsed repo before commit that changed it: ipynb grabbed from https://github.com/lastmile-ai/aiconfig/blob/e2f2d191c1367166efa9717305ac26f7a524d74a/cookbooks/Gemini/Gemini.ipynb
Also removed a null from system prompt  cc:@rossdanlm
> remove unintended changes to Gemini cookbook

- python/src/aiconfig/editor/example_aiconfig_model_registry.py
- python/src/aiconfig/editor/server/server.py
[AIC-py][editor] add default model parsers file
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/567).
* #573
* __->__ #567
> [AIC-py][editor] add default model parsers file

- python/src/aiconfig/editor/README.md
- python/src/aiconfig/editor/example_aiconfig_model_registry.py
- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/scripts/aiconfig_cli.py
[AIC-py][editor] kill the frontend servers better
Fix up server mode stuff
- Enum for validation
- better logging
- try to kill the frontend servers anywhere the script ends
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/573).
* __->__ #573
* #567
> [AIC-py][editor] kill the frontend servers better

- typescript/package.json
- typescript/yarn.lock
> Add node-fetch explicitly

- typescript/__tests__/testSave.ts
> [Typescript] test for save()

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/scripts/aiconfig_cli.py
[AIC-py][editor] bug fix: catch aiconfigruntime load exc
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/575).
* #580
* #579
* #576
* __->__ #575
> [AIC-py][editor] bug fix: catch aiconfigruntime load exc

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/scripts/aiconfig_cli.py
[AIC-py][editor] return aiconfig from http endpoints
and some path validation fixes
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/576).
* #580
* #579
* __->__ #576
* #575
> [AIC-py][editor] return aiconfig from http endpoints

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/scripts/aiconfig_cli.py
[AIC-py][editor] return aiconfig from remaining existing post endpoints
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/579).
* #580
* __->__ #579
* #576
* #575
> [AIC-py][editor] return aiconfig from remaining existing post endpoints

- typescript/__tests__/parsers/palm-text/palm.test.ts
- typescript/demo/test-hf.ts
- typescript/lib/parsers/palm.ts
- typescript/lib/utils.ts
[ez] Auto-format typescript files
Doing this before next diff to keep things separate
> [ez] Auto-format typescript files

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/editor/server/server_utils.py
[AIC-py][editor] get endpoint: list_models
- Name post response better (w. aiconfig)
- add get method (list models)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/594).
* #595
* __->__ #594
> [AIC-py][editor] get endpoint: list_models

- CHANGELOG.md
Date was 2023-11-18. Updated to 2023-12-18. Made the headings consistent.
> [quick fix] fixed date in CHANGELOG.md

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/editor/server/server_utils.py
- python/src/aiconfig/scripts/aiconfig_cli.py
[AIC-py][editor] Basic CRUD API
This does some refactoring to dedup and implements the core crud API
(load, save, run, add_prompt, update_prompt, delete_prompt)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/595).
* __->__ #595
* #594
> [AIC-py][editor] Basic CRUD API

- python/src/aiconfig/editor/README.md
[editor] add easy to use one linear to readme
adding a one line command to readme for local testing. This can be updated and removed later
> [editor] add easy to use one linear to readme

- CHANGELOG.md
- python/pyproject.toml
- typescript/package.json
Changelog v1.1.8
Will published when approved. Realized we messed up and bumped pre-maturely to v1.1.6 (https://github.com/lastmile-ai/aiconfig/commit/5072b13b9456be67d3819c4e0d5c1f20146e2f03) so went to v1.1.7 directly from v1.1.5, so now on Python we're at v1.1.8
> Changelog v1.1.8

- python/requirements.txt
- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/components/prompt/AddPromptButton.tsx
- python/src/aiconfig/editor/client/src/utils/aiconfigStateUtils.ts
- python/src/aiconfig/editor/client/src/utils/api.ts
- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/scripts/aiconfig_cli.py
[editor] Add Prompt Button
[editor] Add Prompt Button
Implement the button for adding a prompt below/between prompts
https://github.com/lastmile-ai/aiconfig/assets/5060851/c3ba1699-adbb-4f7a-a001-9a6972f31cb6
Ensure the new prompt has correct name, model and settings renderer from the schema:
> [editor] Add Prompt Button

- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptOutputBar.tsx
[editor] Prompt Output Bar
Placeholder/starting point for the Output bar. In the future, we'll add metrics such as token usage to this component.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/638).
* #640
* #639
* __->__ #638
> [editor] Prompt Output Bar

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_generation.py
- extensions/LLama-Guard/python/python/src/aiconfig_extension_llama_guard/LLamaGuard.py
- extensions/llama/python/llama.py
Explicit str type checking in model parsers
See comment here for context: https://github.com/lastmile-ai/aiconfig/pull/611#discussion_r1437759469
Separating this diff from https://github.com/lastmile-ai/aiconfig/pull/611 to make it easier and get that one unblocked
> Explicit str type checking in model parsers

- python/src/aiconfig/editor/client/.eslintrc.json
- python/src/aiconfig/editor/client/package.json
- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/ParametersRenderer.tsx
- python/src/aiconfig/editor/client/src/components/SettingsPropertyRenderer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/components/prompt/AddPromptButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/ModelSelector.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptMenuButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptOutputBar.tsx
- python/src/aiconfig/editor/client/src/components/prompt/RunPromptButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/TextRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/model_settings/ModelSettingsSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputConfigRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/attachments/AttachmentContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/attachments/AttachmentMetadata.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/attachments/AttachmentUploader.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputAttachmentsSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputDataSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_metadata/PromptMetadataRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_outputs/PromptOutputsRenderer.tsx
- python/src/aiconfig/editor/client/src/components/property_controls/UnionPropertyControl.tsx
- python/src/aiconfig/editor/client/src/hooks/useLoadModels.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
- python/src/aiconfig/editor/client/yarn.lock
- typescript/.eslintrc.js
[editor] Add Linting & Fix Lint Errors
After some previous PRs I realized linting is not even set up for the editor client yet, which is why there were some missing deps issues noticed in the previous PR. To fix, set up the lint config with proper rules and then manually resolve all errors/warnings.
```
ryanholinshead@Ryans-MacBook-Pro client % yarn lint
$ eslint . --max-warnings=0
✨  Done in 0.87s.
ryanholinshead@Ryans-MacBook-Pro client %
```
Ran through the workbook actions (change input, prompt name, model settings, parameters) and ensure they all work as expected
> [editor] Add Linting & Fix Lint Errors

- .gitignore
[easy] Add production build folder to gitignore
TSIA
> [easy] Add production build folder to gitignore

- typescript/yarn.lock
[easy] yarn.lock updates
Ran `yarn` in `typescript` folder and got a few updates.
> [easy] yarn.lock updates

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/editor/server/server_utils.py
- python/src/aiconfig/schema.py
- python/src/aiconfig/util/params.py
- python/tests/test_parameter_api.py
- python/tests/test_programmatically_create_an_AIConfig.py
Create update_model endpoint
TSIA, backend implementation of `update_model()`. The other changes were from running the auto-formatter:
```
fd --glob '*.py'  python/src/aiconfig/editor/server | xargs python -m 'scripts.lint' --mode=fix --files
```
```
curl http://localhost:8080/api/update_model -d curl http://localhost:8080/api/update_model -d '{"prompt_name":"get_activities", "model_name": "gpt-4", "settings": {"top_p": 0.9}}' -X POST -H 'Content-Type: application/json'
```
Notice that the model name is updated to `gpt-4`, and the `top_p` is now at 0.9
https://github.com/lastmile-ai/aiconfig/assets/151060367/3031fa59-8925-495c-a5eb-e56ec65b7fb …
> Create update_model endpoint

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/editor/server/server_utils.py
- python/src/aiconfig/schema.py
- python/src/aiconfig/util/params.py
- python/tests/test_parameter_api.py
- python/tests/test_programmatically_create_an_AIConfig.py
Create set_description endpoint
TSIA
```
curl http://localhost:8080/api/set_description -d '{"description":"yo this is a cool new description get rekt dont @ me bro"}' -X POST -H 'Content-Type: application/json'
```
https://github.com/lastmile-ai/aiconfig/assets/151060367/0db278b3-8273-4178-8010-380538dcd0ca
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/693).
* __->__ #693
* #692
* #691
* #690
* #688
* #670
* #668
> Create set_description endpoint

- python/src/aiconfig/editor/server/server_utils.py
[AIC-py][editor] file path initialization
1. path is non-optional and has a default value
2. on init, create a new instance and save to the path if the file doesn't exist
(otherwise, try to load as usual)
Run server with and without explicit path. Observe in the logs
that, in either case, when the file doesn't exist it
gets created and written to.
Run again pointing at an existing valid path (e.g. the one just created).
Observe again in the logs that it loads from the path.
https://github.com/lastmile-ai/aiconfig/assets/148090348/ee24a0c0-84d8-47aa-b37f-bc9180948b4e
> [AIC-py][editor] file path initialization

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
Missed adding the try/catch when implementing the callback, so just add them now to be consistent
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/708).
* __->__ #708
* #707
> [editor] Error Notification for Name/Description Exception

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
[editor] Connect Server & Client for Updating Model Name / Settings
Add the calls to the server endpoint for `update_model` to set the model name and settings
https://github.com/lastmile-ai/aiconfig/assets/5060851/6e6f6cb4-5968-4050-8e97-9316d553c2a8
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/707).
* #708
* __->__ #707
> [editor] Connect Server & Client for Updating Model Name / Settings

- python/src/aiconfig/schema.py
Update prompt index with new prompt data name
Fixing issue from https://github.com/lastmile-ai/aiconfig/pull/710#issuecomment-1874432213
> Update prompt index with new prompt data name

- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
[editor] Debounced Error Handling for Prompt Name and Input
`debounced` callbacks won't propagate thrown errors so we should use an `onError` callback to handle those. This PR handles them for updating prompt name and input.
Added the following in /update_prompt endpoint to return an error:
```
return HttpResponseWithAIConfig(
#
message=f"Failed to update prompt",
code=500,
aiconfig=None,
).to_flask_format()
```
See notifications:
https://github.com/lastmile-ai/aiconfig/assets/5060851/04270541-eca9-4d41-8b7c-1e456d992814
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/724).
* #725
* __->__ #724
> [editor] Debounced Error Handling for Prompt Name and Input

- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
[editor] Debounced Error Handling for Update Model & Model Settings
`debounced` callbacks won't propagate thrown errors so we should use an `onError` callback to handle those. This PR handles them for updating prompt model name and model settings.
Added the following in /update_model endpoint to return an error:
```
return HttpResponseWithAIConfig(
#
message=f"Failed to update model",
code=500,
aiconfig=None,
).to_flask_format()
```
See notifications:
https://github.com/lastmile-ai/aiconfig/assets/5060851/899587d7-9ecf-44f5-89b2-0b8919e42079
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/725).
* #728
* #727
* #726
* __->__ #725
> [editor] Debounced Error Handling for Update Model & Model Settings

- python/src/aiconfig/default_parsers/dalle.py
- python/src/aiconfig/default_parsers/hf.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/default_parsers/palm.py
- python/src/aiconfig/default_parsers/parameterized_model_parser.py
[ez] Autoformat python model parsers
Want to keep these changes separate from functional changes next PR in stack
Ran
```
fd --glob '*.py'  python/src/aiconfig/default_parsers | xargs python -m 'scripts.lint' --mode=fix --files
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/737).
* #739
* __->__ #737
> [ez] Autoformat python model parsers

- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/anyscale_endpoint.py
- typescript/lib/config.ts
- typescript/lib/parsers/anyscale.ts
- typescript/lib/parsers/openai.ts
[TypeScript] Default modelparser for AnyScale endpoints
Add a ModelParser for Anyscale Endpoints
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/743).
* #752
* #748
* #746
* #745
* __->__ #743
* #730
> [TypeScript] Default modelparser for AnyScale endpoints

- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/anyscale_endpoint.py
- typescript/lib/config.ts
- typescript/lib/parsers/anyscale.ts
- typescript/lib/parsers/openai.ts
[easy] Allow AnyscaleEndpoint modelparser to accept both ANYSCALE_ENDPOINT_API_KEY or OPENAI_API_KEY
TSIA
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/745).
* #752
* #748
* #746
* __->__ #745
* #743
* #730
> [easy] Allow AnyscaleEndpoint modelparser to accept both ANYSCALE_ENDPOINT_API_KEY or OPENAI_API_KEY

- cookbooks/Anyscale/Function_Calling_with_Mixtral.ipynb
- cookbooks/Function-Calling-OpenAI/python/Function_Calling_with_OpenAI.ipynb
- cookbooks/OpenAI-ChatCompletion-AIConfigWrapper/openai_wrapper.ipynb
- python/src/aiconfig/default_parsers/anyscale_endpoint.py
- python/src/aiconfig/default_parsers/openai.py
Check tool call type instead of function field for tool call data support
Just a small nit I noticed from Sarmad's changes in https://github.com/lastmile-ai/aiconfig/pull/752. I also ran the autoformatter command: `fd --glob '*.py'  python/src/aiconfig/default_parsers | xargs python -m 'scripts.lint' --mode=fix --files`.
I also updated the 3 ipynb notebooks and found + fixed some bugs from that! I also cleared the outputs here, not sure if that's desired, but tested that it works so should be good!
Run the anyscale, openai, and function call cookbooks to make sure they still work
> Check tool call type instead of function field for tool call data support

- python/src/aiconfig/editor/server/server_utils.py
Revert #765
Revert #765 to fix properly in the AIConfig SDK
> Revert #765

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/AnyscaleEndpointPromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
- python/src/aiconfig/editor/travel.aiconfig.json
Add the PromptSchema for AnyscaleEndpoint, following https://docs.anyscale.com/endpoints/model-serving/openai-migration-guide#step-3-check-parameter-compatibility for supported parameters/descriptions
> [editor] Add AnyscaleEndpoint Prompt Schema

- cookbooks/Gemini/Gemini.ipynb
- extensions/Gemini/python/src/aiconfig_extension_gemini/Gemini.py
- python/src/aiconfig/util/config_utils.py
- python/tests/test_util/test_config_util.py
Set the Gemini api key in init instead of re-running every inference call
See comments from https://github.com/lastmile-ai/aiconfig/pull/772#discussion_r1443387445
Run the Gemini cookbook to make sure it still works
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/786).
* #787
* __->__ #786
* #772
> Set the Gemini api key in init instead of re-running every inference call

- python/src/aiconfig/editor/client/package.json
- python/src/aiconfig/editor/client/src/components/JSONEditorToggleButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/RunPromptButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/model_settings/ModelSettingsRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/DalleImageGenerationParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/OpenAIChatModelParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/PaLMChatParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/PaLMTextParserPromptSchema.ts
- python/src/aiconfig/editor/client/yarn.lock
[editor][easy] Center Running Spinner
The 'running' spinner for the RunPromptButton is currently not aligned anymore. This fixes it to keep it centered:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/802).
* #803
* __->__ #802
* #801
* #800
* #799
> [editor][easy] Center Running Spinner

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_2_image.py
Zip image response lists together for HuggingFace text to image diffusor
Victor added a helper function to aggregate the images and has_nsfw_response of each, so we don't have to do this all nested inside of a single big for-loop. Makes this easier to read and debug :)
This is mainly based on Victor's diff in https://github.com/lastmile-ai/aiconfig/pull/750, but added:
- type hints
- created an extra step where we merge the image + nsfw data into a single `ImageData` class
- [bug-fix] Moved helper function outside of class so that it can be called (if we wanted to keep it within the class, we would've had to pass `self` arg as first param and call `self.refine_responses(...)`
For testing rebase on https://github.com/lastmile-ai/aiconfig/pull/461. Tested this on both StableDiffusion and …
> Zip image response lists together for HuggingFace text to image diffusor

- python/pyproject.toml
- typescript/package.json
Updated packages
Published to pypi and npm
> Updated packages

- cookbooks/Getting-Started/travel.aiconfig.json
- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/GlobalParametersContainer.tsx
- python/src/aiconfig/editor/client/src/components/ParametersRenderer.tsx
[Local Editor Styling Updates]
> [Local Editor Styling Updates]

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/DalleImageGenerationParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceAutomaticSpeechRecognitionPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceText2ImageDiffusorPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextGenerationParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/PaLMChatParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/PaLMTextParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
[editor] HuggingFaceAutomaticSpeechRecognitionPromptSchema
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/818).
* __->__ #818
* #815
* #814
> [editor] HuggingFaceAutomaticSpeechRecognitionPromptSchema

- extensions/HuggingFace/python/pyproject.toml
[ez] Update HF extension to v0.0.2
Already published, just doing it here: https://pypi.org/project/aiconfig-extension-hugging-face/
> [ez] Update HF extension to v0.0.2

- python/src/aiconfig/editor/client/src/components/MimeTypeRenderer.tsx
This is basically a copy/paste from workbook audio outputs in lastmile, so it should work the same.
> [editor] Audio Output Renderer

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextGenerationTransformerPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextSummarizationTransformerPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextTranslationTransformerPromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
[editor] HuggingFaceTextGenerationTransformerPromptSchema
> [editor] HuggingFaceTextGenerationTransformerPromptSchema

- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/attachments/AttachmentUploader.tsx
[editor] Handle Uploading Attachments to Public S3 Bucket
Tested in #845 -- needed to remove the policy request there for now and left a TODO to re-add
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/817).
* #848
* #845
* __->__ #817
> [editor] Handle Uploading Attachments to Public S3 Bucket

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/attachments/AttachmentUploader.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputAttachmentsSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceAutomaticSpeechRecognitionPromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
[editor] Get Automatic Speech Recognition Working
https://github.com/lastmile-ai/aiconfig/assets/5060851/fba30e0e-2160-4a84-b657-759f8689ed9e
Some fixes were needed for handling uploading attachments:
1. CORS is currently preventing policy request to lastmile endpoint from localhost; we'll need to fix this but for now we don't need the policy
2. Handling case of no attachments needed some fixes for how attachments are added to the end of the attachments array in `onAddAttachments` and we also need the default input structure to be an object to match the schema (previously was defaulting to string)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/845).
* #848
* __->__ #845
* #817
> [editor] Get Automatic Speech Recognition Working

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceText2SpeechTransformerPromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
> [editor] HuggingFaceText2SpeechTransformerPromptSchema

- README.md
[docs] updated readme for local editor
> [docs] updated readme for local editor

- extensions/HuggingFace/python/pyproject.toml
- python/src/aiconfig/Config.py
Update HF extensions to v0.0.3
Already published, just doing this here: https://pypi.org/project/aiconfig-extension-hugging-face
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/887).
* __->__ #887
* #886
> Update HF extensions to v0.0.3

- python/pyproject.toml
[py] bump pyproject.toml 1.1.12
bump pyproject python project version number
> [py] bump pyproject.toml 1.1.12

- cookbooks/Gradio/README.md
- cookbooks/Gradio/hf_model_parsers.py
- cookbooks/Gradio/huggingface.aiconfig.json
- cookbooks/Gradio/requirements.txt
Small updates to Gradio cookbook
> Small updates to Gradio cookbook

- aiconfig-docs/docs/getting-started.md
- my_aiconfig.aiconfig.json
[docs] update getting started with setup API key
adding the api key instructions setup
> [docs] update getting started with setup API key

- python/src/aiconfig/editor/client/src/components/SettingsPropertyRenderer.tsx
https://github.com/lastmile-ai/aiconfig/assets/5060851/30a1ce9e-0bf4-477b-a799-102463e3025e
> [editor][easy] Make String Settings Inputs Textarea Components

- python/src/aiconfig/scripts/aiconfig_cli.py
- python/src/aiconfig/scripts/rage/rage.py
[AIC-py] cli rage part 2: issue draft
Try to do a lot of stuff automatically. Run it and you'll see exactly what I mean :)
`aiconfig rage`
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/903).
* __->__ #903
* #870
* #869
> [AIC-py] cli rage part 2: issue draft

- schema/aiconfig.schema.json
rebuild schema
Rebuild the schema with changes in the diff below, using `yarn gen-schema` from aiconfig/typescript dir
> rebuild schema

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/automatic_speech_recognition.py
[extensions] 2/n update asr model parser with input schema
With a new input attachment type `AttachmentDataWithStringValue` defined, This diff updates the ASR Model parser to validate input is in the expected form/type.
Also made some updates to to make input attachment validation clearer.
Sapling removed the dependency pr. Depends on
#929
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/932).
* #944
* #940
* __->__ #932
> [extensions] 2/n update asr model parser with input schema

- README.md
- aiconfig-docs/docs/getting-started.md
[docs] added quickstart to getting started
added quickstart section to README + Getting Started
> [docs] added quickstart to getting started

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/ConfigNameDescription.tsx
- python/src/aiconfig/editor/client/src/utils/api.ts
Just address some easy lints
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/959).
* #960
* __->__ #959
> [editor][easy] Fix Some Lints

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextGenerationTransformerPromptSchema.ts
Float isn't a valid type in the renderer, it's 'number'
> Fix float schema type to number

- python/pyproject.toml
[sdk][py] pyproject bump 1.1.6
- published to pypi
> [sdk][py] pyproject bump 1.1.6

- CHANGELOG.md
Updated CHANGELOG for v 1.1.15
TSIA, this is for release up until this PR: https://github.com/lastmile-ai/aiconfig/pull/995
> Updated CHANGELOG for v 1.1.15

- python/src/aiconfig/default_parsers/gemini.py
[easy][sdk][python] 2/n sort imports in Gemini.py
title
Part of a diff stack to incorporate Gemini in the core sdk.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/986).
* #1023
* #987
* __->__ #986
* #973
> [easy][sdk][python] 2/n sort imports in Gemini.py

- python/src/aiconfig/default_parsers/azure.py
- python/src/aiconfig/default_parsers/openai.py
RFC: [python][sdk] Azure OpenAI Model Parser
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1034).
* __->__ #1034
* #1033
> RFC: [python][sdk] Azure OpenAI Model Parser

- python/src/aiconfig/default_parsers/openai.py
RFC: [python][sdk]  Refactor Model Parser: Overridable methot to construct client
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1033).
* #1034
* __->__ #1033
> RFC: [python][sdk]  Refactor Model Parser: Overridable methot to construct client

- python/src/aiconfig/__init__.py
[easy] [python] export Azure
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1079).
* #1080
* __->__ #1079
> [easy] [python] export Azure

- python/src/aiconfig/editor/client/src/components/global/ShareButton.tsx
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
[gradio] Update 'Share' button text to 'Share Workbook'
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1083).
* __->__ #1083
* #1082
> [gradio] Update 'Share' button text to 'Share Workbook'

- cookbooks/Claude-And-Azure/claude_azure_aiconfig.ipynb
Azure and Claude Cookbook
Demonstrating Claude & Azure OpenAI with AIConfig
> Azure and Claude Cookbook

- python/src/aiconfig/editor/client/src/components/ConfigNameDescription.tsx
One thing that would be nice for making configs more readable (especially in Gradio instructions -- https://huggingface.co/spaces/lastmileai/gradio-workbook-template) is if the description renderer supported markdown, similar to our output renderers. This PR swaps the non-editing view of the description to use our TextRenderer (which handles markdown, code, etc. rendering)
Added special handling for clicking on links and the prism code copy button:
https://github.com/lastmile-ai/aiconfig/assets/5060851/bf7a8a12-3901-46b2-80e8-05d22924a9b1
> Support Markdown Rendering in Config Description

- python/src/aiconfig/editor/client/src/components/prompt/ModelSelector.tsx
Proper terminology is "Hugging Face Task" instead of "HuggingFace Task"
> [gradio][ez] Add Space in Hugging Face

- aiconfig-docs/docs/gradio-workbook.md
[docs] gradio workbook documentation
Addressed Rossdan's first pass of comments:
Notes:
- (Rossdan/Ryan) Outstanding issues with read-only from Sarmad
- (Tanya) Feedback on Quicstart Space Description - Tanya to edit the space directly with the follow-ups.
- Delete the '# can delete...' comment in app.py
- (Tanya) Update SDXL Space to have one cell using a global param.
> [docs] gradio workbook documentation

- aiconfig-docs/docs/gradio-workbook.md
[easy][docs] gradio workbook docs
minor edits
> [easy][docs] gradio workbook docs

- python/src/aiconfig/editor/client/src/components/ConfigNameDescription.tsx
- python/src/aiconfig/editor/client/src/components/GlobalParametersContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptMenuButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputConfigRenderer.tsx
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
- python/src/aiconfig/editor/client/src/themes/LocalTheme.ts
[gradio] Fix Margin of Title / Global Parameters
In gradio, the prompt menu button has styles overridden by gradio button styles and therefore has no padding. This messes up the alignment of the title/description and global parameters compared to the prompts:
Similarly, in readOnly mode there is no prompt menu button but we still had the left margin on the title/description and global parameters:
This PR fixes both situations by:
- Explicitly setting the padding/margin for the prompt menu button in gradio theme to have higher specificity than gradio button styles
- Dynamically handling the left margin of the title/description and global parameters based on readOnly or not
Notes:
- Not sure how to test vscode theme here really since the actual vs code package has different styles, etc. …
> [gradio] Fix Margin of Title / Global Parameters

- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputConfigRenderer.tsx
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
[gradio] Fix Local Parameters AddParameter Button Style
The 'add parameter' button in the prompt parameters section currently doesn't match the global one in gradio. This fixes to apply the same class to both:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1102).
* #1109
* #1105
* #1104
* #1103
* __->__ #1102
* #1101
* #1100
* #1099
* #1098
* #1097
* #1096
* #1095
> [gradio] Fix Local Parameters AddParameter Button Style

- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputConfigRenderer.tsx
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
[gradio] Fix Input Background in Dark Mode
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1103).
* #1109
* #1105
* #1104
* __->__ #1103
* #1102
* #1101
* #1100
* #1099
* #1098
* #1097
* #1096
* #1095
> [gradio] Fix Input Background in Dark Mode

- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputConfigRenderer.tsx
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
[gradio] Change Side Panel Color to Differ from Background
Just change the background color of the prompt right side panel to be a tiny bit lighter than the background.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1105).
* #1109
* __->__ #1105
* #1104
* #1103
* #1102
* #1101
* #1100
* #1099
* #1098
* #1097
* #1096
* #1095
> [gradio] Change Side Panel Color to Differ from Background

- python/src/aiconfig/editor/client/src/components/ConfigNameDescription.tsx
- python/src/aiconfig/editor/client/src/components/ParametersRenderer.tsx
Left-align Parameters Description
From https://github.com/lastmile-ai/aiconfig/pull/1121/files, just applying to main since it makes sense / looks better here as well.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1132).
* #1134
* #1133
* __->__ #1132
* #1131
> Left-align Parameters Description

- vscode-extension/.vscode/launch.json
- vscode-extension/.vscode/settings.json
- vscode-extension/.vscode/tasks.json
- vscode-extension/LICENSE
- vscode-extension/editor/.vscodeignore
[easy] Create configs for debugging and launching vscode extension
Adding `launch.json` and `tasks.json` to set up hot reloading debugger for vscode extension.
More details here: https://docs.google.com/document/d/1eEqJ2nRTg9uyoeuIJ8C26MGN7Xb3JbKeI-8WT65dAkw/edit#heading=h.hdwz6fcvlys
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1140).
* #1142
* #1141
* __->__ #1140
> [easy] Create configs for debugging and launching vscode extension

- cookbooks/RAG-with-Model-Graded-Eval/rag.aiconfig.yaml
- cookbooks/RAG-with-Model-Graded-Eval/rag.py
- cookbooks/RAG-with-Model-Graded-Eval/rag_demo.ipynb
- cookbooks/RAG-with-Model-Graded-Eval/requirements.txt
Create cookbook for RAG with model-graded eval
Courtesy @jonathanlastmileai for the implementation.
Mostly moved from: https://github.com/lastmile-ai/lastmile/pull/1368, with a cleaned up ipynb.
> Create cookbook for RAG with model-graded eval

- python/pyproject.toml
Update python-aiconfig to 1.1.22
Add changes for pinned dependency in https://github.com/lastmile-ai/aiconfig/pull/1171
> Update python-aiconfig to 1.1.22

- vscode-extension/package.json
[vscode] Publish extension v0.0.6
Already published, just updating package.json as well
> [vscode] Publish extension v0.0.6

- vscode-extension/.vscode/settings.json
- vscode-extension/package.json
- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
- vscode-extension/src/welcomePage.html
[vs-code][2/n] Welcome Page: HTML content
Just some HTML content.
I tried having links to commands, but turns out that's not super straightforward, so whatever just listing commands and they can run it themselves. See how VSCode does it in here:
- command definition: https://github.com/microsoft/vscode/blob/c1021c9573c1a60c652be64556b8ac024e543c83/src/vs/workbench/contrib/welcomeGettingStarted/common/gettingStartedContent.ts#L64C15-L64C45
- command execution: https://github.com/microsoft/vscode/blob/c1021c9573c1a60c652be64556b8ac024e543c83/src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.ts#L1232
Can add more pictures later if you want.
Added some FAQ to learn more + get unblocked.
Video showing full page (can pause to read stuff) …
> [vs-code][2/n] Welcome Page: HTML content

- vscode-extension/.vscode/settings.json
- vscode-extension/package.json
- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
- vscode-extension/src/welcomePage.html
[vs-code][1/n] Welcome Page: Scaffolding
Just basic scaffolding for now, nothing fancy, will make UI better next diff
Following instructions from https://lastmileai.dev/workbooks/cls5af4s700pkqrsegl64gx3i
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1178).
* #1182
* __->__ #1178
> [vs-code][1/n] Welcome Page: Scaffolding

- cookbooks/RAG-with-Model-Graded-Eval/rag.aiconfig.yaml
[workshop] Update aiconfig with some instructions on model switching
TSIA
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1199).
* __->__ #1199
* #1198
> [workshop] Update aiconfig with some instructions on model switching

- .gitignore
Add `log.txt` to .gitignore
This was grinding my gears!!!!
> Add `log.txt` to .gitignore

- README.md
Updated the editor to VS Code Extension within the README, with updated screenshot.
> Andrew readme vscode

- CHANGELOG.md
> CHANGELOG 2/08

- CHANGELOG.md
fix date on change log to 2/12
> fix date on change log to 2/12

- extensions/HuggingFace/python/pyproject.toml
Update HF extension to 0.0.9
I messed up for 0.0.8 becuase I forgot to rebase. This includs Ryan's changes from https://github.com/lastmile-ai/aiconfig/pull/1221
> Update HF extension to 0.0.9

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/__init__.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/conversational.py
[extension] 3/n default export conversational model parser
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1229).
* __->__ #1229
* #1228
* #1227
> [extension] 3/n default export conversational model parser

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/conversational.py
[extension]  1/n scaffolding for HF conversational remote inference model parser
just a copy paste of text_translation.py
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1227).
* #1229
* #1228
* __->__ #1227
> [extension]  1/n scaffolding for HF conversational remote inference model parser

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceConversationalRemoteInferencePromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
[Editor]  4/n HF Conversational Prompt schema
> [Editor]  4/n HF Conversational Prompt schema

- aiconfig-docs/docs/gradio-notebook.md
> Documentation on Local Model Parsers

- aiconfig-docs/docs/gradio-notebook.md
Accidentally missed pushing this minor change before merging #1238
> [docs] Actually push the changes from the PR feedback

- aiconfig-docs/docs/gradio-notebook.md
Update Gradio-Notebook Markdown
TSIA
> Update Gradio-Notebook Markdown

- aiconfig-docs/docs/gradio-notebook.md
More content updated to gradio notebook docs
TSIA
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1244).
* __->__ #1244
* #1243
> More content updated to gradio notebook docs

- aiconfig-docs/docs/gradio-notebook.md
[docs] Update docs with Youtube demo video, plus gifs
Gifs courtesy Zak.
How Verified:
* yarn start
> [docs] Update docs with Youtube demo video, plus gifs

- gradio-notebook/frontend/package.json
- gradio-notebook/frontend/yarn.lock
- gradio-notebook/pyproject.toml
- gradio-notebook/requirements.txt
Update Gradio packages
TSIA, not on v0.0.13
> Update Gradio packages

- python/pyproject.toml
- typescript/package.json
Update python sdk to 1.1.26 and typescript sdk to 1.1.8
Doing this as last PR before changelog so that when I publish it will include these changes
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1263).
* #1264
* __->__ #1263
> Update python sdk to 1.1.26 and typescript sdk to 1.1.8

- gradio-notebook/frontend/Index.svelte
Copy the changes here from https://github.com/lastmile-ai/gradio-notebook/pull/196, with typing `window` as `any` to prevent lint errors accessing the `__gradio_space__` property.
Note, I still can't `yarn build` since I get:
```
(aiconfig) ryanholinshead@Ryans-MBP frontend % yarn build
$ node config/index.js --mode build
node:fs:1674
handleErrorFromBinding(ctx);
^
Error: ENOENT: no such file or directory, lstat '../templates/frontend'
at lstatSync (node:fs:1674:3)
at statFunc (node:internal/fs/cp/cp-sync:122:15)
at getStatsSync (node:internal/fs/cp/cp-sync:123:19)
at checkPathsSync (node:internal/fs/cp/cp-sync:72:33)
at cpSyncFn (node:internal/fs/cp/cp-sync:58:42)
at Object.cpSync (node:fs:3018:3)
at run (file:///Users/ryanholinshead/Projects/aiconfig/gradio-notebook/fro …
```
> Copy Source URL Changes from gradio-notebook

- gradio-notebook/frontend/package.json
- gradio-notebook/frontend/yarn.lock
- gradio-notebook/pyproject.toml
Matching changes from https://github.com/lastmile-ai/gradio-notebook/pull/198
> [gradio] Update aiconfig-editor package and bump pyproject package

- vscode-extension/package.json
[RFC] Initial walkthrough content for VS Code extension
Following the guide from VSCode tutorials here: https://code.visualstudio.com/api/references/contribution-points#contributes.walkthroughs
This is now just extremely barebones, want to get some comments on what other commands we feel should be included.
Also note that I can also add in images and markdown to the right side of panel for each item that's selected
Let's just get this out really quickly so that Tanya + Zak can help out with content + graphics in the markdown files
https://github.com/lastmile-ai/aiconfig/assets/151060367/5827b98c-ac1c-4454-a337-ce9eb3c44b1a
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1273).
* #1276
* __->__ …
> [RFC] Initial walkthrough content for VS Code extension

- vscode-extension/package.json
- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
[vscode][1/n] Setup Env Variables: Initial scaffolding
No implementation yet, just connecting commands
https://github.com/lastmile-ai/aiconfig/assets/151060367/46f254ae-68e0-426f-81e3-88f2c3c64ea7
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1277).
* #1278
* __->__ #1277
> [vscode][1/n] Setup Env Variables: Initial scaffolding

- vscode-extension/package.json
[nit] Update Create JSON and Create YAML button commands
VSCode walkthroughs automatically format things in pretty blue boxes whenever you have a single command per newline
> [nit] Update Create JSON and Create YAML button commands

- vscode-extension/static/untitled.aiconfig.json
- vscode-extension/static/untitled.aiconfig.yaml
Updated the empty config state
Made it cleaner - this should be intuitive to use as is.
Also user doesn't have to delete as much text from initial state to jump in and get started.
> Updated the empty config state

- vscode-extension/static/untitled.aiconfig.json
- vscode-extension/static/untitled.aiconfig.yaml
updated empty state config
added more detail - still needs improvement but better than the blank state from before.
to follow-up
- replace gpt4 with gemini to showcase a non-openai model. having some issues with the output not saving..so not using it for now.
- also wanted to add image cell with dalle3 but not saving output right now
> updated empty state config

- vscode-extension/static/env_template.env
updated the env_tempate.env
updating the template for environment variables
> updated the env_tempate.env

- vscode-extension/src/extension.ts
[vscode][6/n] Setup Env Variables: Add more validation to env path input
Added two noteworthy checks that we didn't have before:
1. The filename itself must be ".env" (before it only checked for ending so things like "invalid/filename.env" could be valid)
2. The path must be a subset of the workspace path, to ensure that when we call the `loadenv()` function from Python in AIConfig SDK, it's able to access this `.env` file
I also made this into a separate function to keep it cleaner
https://github.com/lastmile-ai/aiconfig/assets/151060367/d77305c4-2cc6-4cb8-a918-b74826ff3714
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1291).
* #1300
* __->__ #1291
> [vscode][6/n] Setup Env Variables: Add more validation to env path input

- vscode-extension/package.json
[ez][vsode] walkthrough: add back button for install
title
> [ez][vsode] walkthrough: add back button for install

- vscode-extension/editor/src/VSCodeEditor.tsx
[vscode] Set datadog service to vscode-aiconfig
> [vscode] Set datadog service to vscode-aiconfig

- vscode-extension/src/extension.ts
Create listener to open info dialog for when python interpreter path changes
Haven't added the actual implementation for restarting server. Ryan is working on that now so will connect to it next PR when it's ready
Some additional context that Ankush and I discussed:
If user selects an invalid interpreter, that's fine because:
1. They AIconfig flow will be invalid and fail (upon restarting server), but we have checks to pester them to update their interpreter to the correct one via the `installDependencies()` flow (defined in https://github.com/lastmile-ai/aiconfig/pull/1307)
https://github.com/lastmile-ai/aiconfig/assets/151060367/b9219c15-5843-4bf7-888f-357b20faff6a
Also tested this does not trigger the button to be shown when selecting an interpreter gets triggered because we haven't …
> Create listener to open info dialog for when python interpreter path changes

- vscode-extension/media/ApiKeys.md
- vscode-extension/media/CreateAIConfig.md
- vscode-extension/media/InitializeExtension.md
- vscode-extension/media/more.md
- vscode-extension/package.json
- vscode-extension/src/aiConfigEditor.ts
Clean up Welcome
Just a few wording updates to clean up the welcome walkthrough.
Also bring back buttons that got removed in #1295
https://github.com/lastmile-ai/aiconfig/assets/25641935/6a155304-1cb6-46b1-b11e-b9231fabc542
Walkthrough command pallette:
> Clean up Welcome

- vscode-extension/src/editor_server/serverPortManager.ts
[3/n] Restart Editor Servers on Python Interpreter Change
Missed pushing local changes with https://github.com/lastmile-ai/aiconfig/pull/1328, but the test plan is from this.
https://github.com/lastmile-ai/aiconfig/assets/5060851/e8c03725-afc8-41e2-a610-64e3afc73efd
> [3/n] Restart Editor Servers on Python Interpreter Change

- vscode-extension/python/requirements.txt
[ez] Update extension requirements.txt with latest python-aiconfig
TSIA
> [ez] Update extension requirements.txt with latest python-aiconfig

- vscode-extension/media/ApiKeys.md
- vscode-extension/media/CreateAIConfig.md
- vscode-extension/media/InitializeExtension.md
- vscode-extension/media/more.md
- vscode-extension/package.json
- vscode-extension/src/util.ts
Add completion events to walkthrough steps
Ok, upon further investigation, I found out that the `completionEvents` doesn't actually do anything anymore: https://github.com/microsoft/vscode/issues/176074#issuecomment-1676995414. However, this no-op is being reverted in next VS Code update in https://github.com/microsoft/vscode/issues/176074#issuecomment-1912698405, so it's still good to included this here!!! We should then advertise to people to pls update their VS Code version!!!
You can read more about completion events in https://code.visualstudio.com/api/references/contribution-points#Completion-events
~~Now we shouldn't auto-mark steps as completed unless command has been run~~
I also added "CMD/CTRL" to the readme files and renamed the readme files to be non-capitalized. I also made …
> Add completion events to walkthrough steps

- vscode-extension/editor/package.json
- vscode-extension/editor/yarn.lock
Includes the changes from #1325 for not polling server status in readonly
> Update aiconfig-editor to 0.2.2

- vscode-extension/package.json
- vscode-extension/src/utilities/versionUpdateUtils.ts
Open walkthrough if activating extension for the first time
Last PR I did the if-else statements to connect to the flow. This PR I'm actually doing the implementation to open the walkthrough.
https://github.com/lastmile-ai/aiconfig/assets/151060367/4b72b541-61f3-489a-9b97-61ab120fde32
> Open walkthrough if activating extension for the first time

- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
Remove ShowWelcome internals
I removed this from the package.json in https://github.com/lastmile-ai/aiconfig/pull/1322 but forgot to remove the internal function definitions
No functional changes
> Remove ShowWelcome internals

- python/src/aiconfig/Config.py
[sdk & editor] Modify Default Ordering of Models
This diff moves Gemini closer to the top of the model registry list.
| Before | After |
| <img width="1398" alt="Screenshot 2024-02-26 at 11 34 33 AM" src="https://github.com/lastmile-ai/aiconfig/assets/141073967/fb2e610c-a0b5-4f80-bcc5-0d7b4e7de07f">  | <img width="1333" alt="Screenshot 2024-02-26 at 11 34 02 AM" src="https://github.com/lastmile-ai/aiconfig/assets/141073967/5e9bd45b-fc15-455a-94d6-6173a58d5b8b">  |
> [sdk & editor] Modify Default Ordering of Models

- vscode-extension/static/untitled.aiconfig.yaml
[easy fix] untitle.aiconfig.yaml was missing parameter value
added parameter value to default untitle yaml
> [easy fix] untitle.aiconfig.yaml was missing parameter value

- README.md
[aiconfig readme] updated quickstart to link to vs code extension
> [aiconfig readme] updated quickstart to link to vs code extension

- vscode-extension/src/utilities/pythonSetupUtils.ts
[ez][vscode] Remove `Please Try Again Later` From Install Dependencies message
Title
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1363).
* __->__ #1363
* #1361
> [ez][vscode] Remove `Please Try Again Later` From Install Dependencies message

- vscode-extension/media/initializeExtension.md
- vscode-extension/package.json
[RFC] Updated content to add a bit more information
Discussed content with Sarmad and Ankush, but didn't actually talk about the formatting so want to request comments.
| | Dark mode | Light Mode |
|--|--|--|
| 1 | <img width="1920" alt="Screenshot 2024-02-26 at 16 20 34" src="https://github.com/lastmile-ai/aiconfig/assets/151060367/9e9edf80-ad95-4400-9de5-e3d460125cf6"> | <img width="1920" alt="Screenshot 2024-02-26 at 16 20 51" src="https://github.com/lastmile-ai/aiconfig/assets/151060367/852e6825-748e-4b74-b703-9057880caa13"> |
| 2 | <img width="1920" alt="Screenshot 2024-02-26 at 16 20 40" src="https://github.com/lastmile-ai/aiconfig/assets/151060367/e1b1d78d-c7d0-494b-aec4-07dc1a311c2a"> | <img width="1920" alt="Screenshot 2024-02-26 at 16 21 07" …
> [RFC] Updated content to add a bit more information

- vscode-extension/python/requirements.txt
[vscode] Bump AIConfig Python Requirement
Titlez
ontop of #1365
> [vscode] Bump AIConfig Python Requirement

- vscode-extension/package.json
[ez] Bump up extension version
Published to vscode marketplace
> [ez] Bump up extension version

- vscode-extension/README.md
- vscode-extension/package.json
- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
Update extension readme and add a Welcome command
* Updates to extension readme
* Welcome command to quickly open Welcome page
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1374).
* __->__ #1374
* #1370
> Update extension readme and add a Welcome command

- vscode-extension/package.json
> Bump VS Code Package Version from Publish

- cookbooks/Groq/aiconfig_model_registry.py
- cookbooks/Groq/groq.aiconfig.json
- extensions/Groq/LICENSE
- extensions/Groq/README.md
- extensions/Groq/pyproject.toml
- extensions/Groq/requirements.txt
- extensions/Groq/src/aiconfig_extension_groq/__init__.py
- extensions/Groq/src/aiconfig_extension_groq/groq.py
[groq] Initialize extension for Groq OpenAI client wrapper
Documentation here: https://console.groq.com/docs/quickstart
Will publish extension after it's approved
https://github.com/lastmile-ai/aiconfig/assets/151060367/29437586-97de-427c-8480-2d9535304d05
> [groq] Initialize extension for Groq OpenAI client wrapper

- cookbooks/Groq/aiconfig_model_registry.py
- extensions/Groq/README.md
- extensions/Groq/src/aiconfig_extension_groq/__init__.py
- extensions/Groq/src/aiconfig_extension_groq/groq.py
Change GroqOpenAIParser --> GroqParser
Simple change, no functional changes
> Change GroqOpenAIParser --> GroqParser

- extensions/Groq/pyproject.toml
Update Groq extension to 0.0.2
TSIA
> Update Groq extension to 0.0.2

- python/pyproject.toml
- vscode-extension/package.json
- vscode-extension/python/requirements.txt
[vscode & aiconfig] Version Bump
Summary:
includes env file changes
Test Plan:
> [vscode & aiconfig] Version Bump

- vscode-extension/editor/package.json
- vscode-extension/package.json
[vscode] version bump
Title, latest version of aiconfig-editor
> [vscode] version bump

- vscode-extension/editor/yarn.lock
add yarn.lock from yarn build
Dependencies:
#1424
> add yarn.lock from yarn build

- vscode-extension/package.json
[vscode][ez] Update extension tags and categories
TSIA
> [vscode][ez] Update extension tags and categories

- .github/workflows/publish_python_sdk.yml
combine jobs, build and publish in the same step.
also add a secrets web hook
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1454).
* __->__ #1454
* #1453
> combine jobs, build and publish in the same step.

- vscode-extension/python/requirements.txt
Bump python-aiconfig package
Summary: Bump the aiconfig package so that deleting model settings works
Test Plan:
https://github.com/lastmile-ai/aiconfig/assets/5060851/49433ed1-40bd-451e-aba8-36b37f020fda
> Bump python-aiconfig package

- python/src/aiconfig/schema.py
- python/tests/test_dataclass.py
Small minor fixes to functions in Prompt functions
Just a couple of minor fixes.
No tests exist for this so just gotta trust me I guess
> Small minor fixes to functions in Prompt functions

- python/pyproject.toml
- python/requirements.txt
[sdk] Version Bump
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1479).
* __->__ #1479
* #1478
> [sdk] Version Bump

- vscode-extension/python/requirements.txt
Summary: This bump is necessary to have the sever-side changes for deleting single prompt output
Test Plan: Can delete output and save & see the config has no outputs (empty outputs array)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1480).
* #1481
* __->__ #1480
> Update python-aiconfig package version

- python/requirements.txt
> bump lm-utils

- python/pyproject.toml
Bump python-sdk
ontop of #1485
> Bump python-sdk

- .github/workflows/publish_python_sdk.yml
format ci/cd payload
title
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1487).
* __->__ #1487
* #1486
> format ci/cd payload

- cookbooks/Basic-Prompt-Routing/assistant.aiconfig.json
Convert routing cookbook to an actual aiconfig.json
Summary:
Test Plan:
> Convert routing cookbook to an actual aiconfig.json

- cookbooks/Basic-Prompt-Routing/assistant.aiconfig.json
- cookbooks/Basic-Prompt-Routing/assistant.ipynb
Add an ipynb to show basic prompt routing in action
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1493).
* __->__ #1493
* #1492
> Add an ipynb to show basic prompt routing in action
