- python/src/aiconfig/AIConfigSettings.py
- python/src/aiconfig/Config.py
[Python] 1/n Serialize Setup
Implemented Serialize in ConfigRuntime which calls ModelParser
`serialize`
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/32).
* #33
* __->__ #32
> [Python] 1/n Serialize Setup

- python/src/aiconfig/AIConfigSettings.py
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/util/config_utils.py
- python/tests/parsers/test_openai_util.py
- python/tests/test_programmatically_create_an_AIConfig.py
- typescript/__tests__/config.test.ts
- typescript/demo/demo.ts
- typescript/demo/function-call-stream.ts
- typescript/lib/config.ts
- typescript/lib/parsers/openai.ts
[Python] 4/n Serialize OpenAI Model Parser
Modified serialize return type to list of Prompts.
Implemented serialize for OpenAI ModelParser.
Tested with api wrapper with the diff on top.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/33).
* __->__ #33
* #38
* #39
* #37
> [Python] 4/n Serialize OpenAI Model Parser

- python/src/aiconfig/AIConfigSettings.py
- python/src/aiconfig/util/config_utils.py
- python/tests/test_programmatically_create_an_AIConfig.py
[Python] 1\n Added helpers for retrieving & merging model settings
This diff adds two helpers which ensure that retreived model settings properly contains relevant global settings.
- `extract_override_settings`
- `generate_model_metadata`
Added test for `extract_override_settings`
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/37).
* #33
* #38
* #39
* __->__ #37
> [Python] 1\n Added helpers for retrieving & merging model settings

- python/src/aiconfig/AIConfigSettings.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/util/config_utils.py
- python/tests/parsers/test_openai_util.py
- python/tests/test_programmatically_create_an_AIConfig.py
[Python] 3\n Update OpenAI Deserialize spec to handle function calling
- Modified PromptInput type args to be  more generic and in turn allow function calling .
Function calling prompt input with openai will look something like the following. The main difference is that the input has a role, and content, similar,
```
newPrompt:
{
name: 'functionCallResult-3',
input: {
role: 'function',
name: 'list',
content: '[{"name":"To Kill a Mockingbird","id":"a1"},{"name":"All the Light We Cannot See","id":"a2"},{"name":"Where the Crawdads Sing","id":"a3"}]'
},
metadata: {
model: { name: 'gpt-3.5-turbo', settings: [Object] },
parameters: {},
remember_chat_context: true
},
outputs: undefined
}```
--- …
> [Python] 3\n Update OpenAI Deserialize spec to handle function calling

- python/src/aiconfig/AIConfigSettings.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/util/config_utils.py
- python/tests/test_programmatically_create_an_AIConfig.py
[Python] 2\n helper fn's to Augment OpenAI Serialize()
This diff introduces two new helper functions inside the openai model parser.
- `add_prompt_as_message`
- `has_valid_prompt_string`
First one  converts prompts into messages and appends them to a list of messages. Designed to augment serialize()
Second one validates if a prompt's input type.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/39).
* #33
* #38
* __->__ #39
* #37
> [Python] 2\n helper fn's to Augment OpenAI Serialize()

- python/src/aiconfig/ChatCompletion.py
- python/src/aiconfig/Config.py
OpenAI Api Chat Completion wrapper
Wrapper for openai.ChatCompletion.Create()
Saves the latest prompt and system prompt in each call to config and disk under `aiconfig.json`
TODO: make a test
> OpenAI Api Chat Completion wrapper

- schema/aiconfig.schema.json
- typescript/lib/config.ts
- typescript/lib/modelParser.ts
- typescript/lib/modelParserRegistry.ts
- typescript/lib/parameterize.ts
- typescript/lib/parameterizedModelParser.ts
- typescript/lib/parsers/openai.ts
- typescript/types.ts
AIConfig Schema updates
A few schema updates to AIConfig based on feedback from bug bash and team brainstorming:
1. Add a `default_model` property to AIConfig metadata. If used, we can simplify the prompt to not have to specify any model information at all (see item #5 in Bug Bash: https://docs.google.com/document/d/1tMu-N53AzCKc_uPEeLARLgdnpVLM5HPQjlqOPs3Z0B4/edit)
2. Add `model_parsers` mapping property to AIConfig metadata. This allows us to specify a model parser ID in the config itself. This is based on Ryan's feedback for things like Hugging Face model parsers, which can support hundreds of different models. Now, the models that someone uses in the AIConfig can register the HF model parser in the config, saving us from having to manage a rapidly changing list of model IDs …
> AIConfig Schema updates

- python/src/aiconfig/util/params.py
[Python] Fixed a bug that  let Global Parameters take precendence over User Paramaters
Identified in Tanya's notebook: https://colab.research.google.com/drive/1OpDWyI_2aLg8VfWb5VbD864vQDdQjv-m#scrollTo=TBhwhp-b4ajx
> [Python] Fixed a bug that  let Global Parameters take precendence over User Paramaters

- python/tests/parameterization/test_parameterization.py
[Python] Tests for parameterization
Created a test file which tested Parameterization amongst global, prompt, and user specified parameters.
Each test has an associated config that utilizes GPT-3.5-turbo as its model.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/88).
* __->__ #88
* #87
> [Python] Tests for parameterization

- python/src/aiconfig/util/config_utils.py
- typescript/__tests__/testProgramaticallyCreateConfig.ts
- typescript/lib/config.ts
[Typescript] Introduce the getGlobalSettings API Method
This diff introduces the `getGlobalSetting` API method, which retrieves global settings for a specified model.
One of the steps in enhancing ModelParser creation. More in diffs on top.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/51).
* #76
* #75
* #55
* #52
* #54
* __->__ #51
* #50
> [Typescript] Introduce the getGlobalSettings API Method

- python/src/aiconfig/util/config_utils.py
[Python][Easy] Type Hint update
`AIConfigSettings` is a file not a type. Updated to `AIConfig` to reflect the correct type hint.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/50).
* #76
* #75
* #55
* #52
* #54
* #51
* __->__ #50
> [Python][Easy] Type Hint update

- python/src/aiconfig/util/config_utils.py
- typescript/__tests__/testProgramaticallyCreateConfig.ts
- typescript/lib/config.ts
[Typescript][easy] Refactor updateModel to correctly propogate settings
Refactored updateModel to correctly propogate inference settinsg into global settings when no prompt is specified.
updateModel() takes in two Parameters:
- `ModelMetadata` and an Optional `Prompt`
- `ModelMetadata` has a name field and a settings field
- Global settings on aiconfig, `aiconfig.metadata.models` has type `models?: GlobalModelMetadata;`
where GlobalModelMetadata is a mime typed map/dict, NOT ModelMetadata.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/54).
* #76
* #75
* #55
* #52
* __->__ #54
* #51
* #50
> [Typescript][easy] Refactor updateModel to correctly propogate settings

- cookbook/HuggingFace/Mistral-aiconfig.json
- cookbook/HuggingFace/README.md
- python/src/aiconfig/__init__.py
- python/src/aiconfig/default_parsers/parameterized_model_parser.py
[Python][Easy] reformat helper method to be an instance method
title
method() -> method(self,)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/84).
* #86
* #85
* __->__ #84
* #83
* #82
> [Python][Easy] reformat helper method to be an instance method

- python/requirements.txt
- python/src/aiconfig/Config.py
[Python] Update run() to make parameters optional.
- run() doesn't need parameters specified. Updated parameters to truly be optional, typehint was misleading here
- pinned openai to <1.0.0. Fixing for new version in a seperate diff.
> [Python] Update run() to make parameters optional.

- typescript/__tests__/testProgramaticallyCreateConfig.ts
- typescript/demo/mistral-config.json
- typescript/demo/test-hf.ts
- typescript/lib/config.ts
- typescript/lib/parsers/hf.ts
- typescript/lib/utils.ts
- typescript/package.json
- typescript/yarn.lock
[Typescript] Added HuggingFace Text Generation Parser.
HF text gen model parser.
- Built off Ryan's previous diff on building Model Parser
- Doesn't require an api key but it can be specified.
TS HuggingFace api differs from the Python side in a couple of ways ie:
- different apis for streaming,
- - utilized both inside the TS impl
- Python lets you specify details to be included, no option in TS but default is most of those details
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/76).
* #91
* __->__ #76
* #75
* #55
* #52
> [Typescript] Added HuggingFace Text Generation Parser.

- typescript/__tests__/testProgramaticallyCreateConfig.ts
- typescript/lib/utils.ts
[Typescript] Introduce Extract Override Settings method
This diff introduces the `extractOverrideSettings` function. One of the abstractions which will make it easier to construct model sttings
- Abstracted existing logic to get overrides
- Added test. Same test & logic as the python side
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/52).
* #91
* #76
* #75
* #55
* __->__ #52
> [Typescript] Introduce Extract Override Settings method

- typescript/__tests__/testProgramaticallyCreateConfig.ts
- typescript/lib/config.ts
- typescript/lib/utils.ts
[Typescript] Introduce GenerateModelMetadata API method.
This diff introduces a new api method to config, `generateModelMetadata()` to make it much easier to implement `serialize()` when writing a modelParser
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/55).
* #91
* #76
* #75
* __->__ #55
* #52
> [Typescript] Introduce GenerateModelMetadata API method.

- typescript/__tests__/testProgramaticallyCreateConfig.ts
- typescript/lib/config.ts
- typescript/lib/utils.ts
[TypeScript] Fix forced Type when creating a model parser
- Modified aiconfig.`registerModelParser()` by using a generic `Any` instead of defaulting to JSONObject within ModelParser. This change enables the acceptance of types that do not conform to JSONObject.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/75).
* #91
* #76
* __->__ #75
* #55
* #52
> [TypeScript] Fix forced Type when creating a model parser

- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/default_parsers/palm.py
- python/src/aiconfig/model_parser.py
- python/tests/parsers/test_openai_util.py
[Python] Refactor out InferenceOptions from `Resolve` and `Deserialize`
Removed dependency on `Inference Options` for
- config.resolve()
- ModelParser.deserialize()
- - Sets `stream` based on config, not InferenceOptions
`Resolve()` in Config and `Deserialize()` in ModelParser should not use Inference Options. Settings should be derived directly from config. Discussed Offline @saqadri
> [Python] Refactor out InferenceOptions from `Resolve` and `Deserialize`

- python/demo/aiconfig_demo.ipynb
- python/demo/function_calling_demo.py
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/schema.py
- python/tests/parsers/test_openai_util.py
- python/tests/test_library_helpers.py
- python/tests/test_load_config.py
- python/tests/test_programmatically_create_an_AIConfig.py
- python/tests/test_resolve.py
- python/tests/test_run_config.py
[Python] Refactor `generate_model_metadata()` Name
Previously:
- `generate_model_metadata()`
Refactored to:
- `get_model_metadta()`
- Provide better Name for method. `Generate` doesn't really tell the developer what the method does.
- Align on library reqs. Updated in TS already
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/96).
* __->__ #96
* #95
* #94
> [Python] Refactor `generate_model_metadata()` Name

- python/demo/aiconfig_demo.ipynb
- python/demo/function_calling_demo.py
- python/src/aiconfig/Config.py
- python/src/aiconfig/schema.py
- python/tests/parsers/test_openai_util.py
- python/tests/test_library_helpers.py
- python/tests/test_load_config.py
- python/tests/test_programmatically_create_an_AIConfig.py
- python/tests/test_resolve.py
- python/tests/test_run_config.py
[Python] Refactor `from_config()` Name
Before:
- `AIConfigRuntime.from_config()`
After:
- `AIConfigRuntime.Load()`
- Similar to TS impl
- Aligning with Library reqs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/95).
* #96
* __->__ #95
* #94
> [Python] Refactor `from_config()` Name

- python/src/aiconfig/Config.py
- test.py
[Python] Refactor save() to use file from load()
The Config.save() method has been updated to automatically save the aiconfig back to the original source file unless an alternative file path is provided
- Added attribute `file_path` to AIConfigRuntime.
- on `config.load()` `file_path` attribute is set to the file
- Modified save() to use file path if available else default to `aiconfig.json`
The flow from loading and saving a config should be as easy as possible. This way the user can easily update their config without having the extra step of specifying the same file path that was used to load.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/98).
* #99
* __->__ #98
> [Python] Refactor save() to use file from load()

- test.py
- typescript/lib/config.ts
[Typescript] Refactor save() to use file from load()
The Config.save() method has been updated to automatically save the aiconfig back to the original source file unless an alternative file path is provided
- Added attribute `file_path` to AIConfigRuntime.
- on `config.load()` `file_path` attribute is set to the file
- Modified save() to use file path if available else default to `aiconfig.json`
The flow from loading and saving a config should be as easy as possible. This way the user can easily update their config without having the extra step of specifying the same file path that was used to load.
Local testing
- Load Config()
- Save config() with no params specified.
- Config saved under original file path
> [Typescript] Refactor save() to use file from load()

- aiconfig-docs/docs/introduction/getting-started.md
[DOCS] Fix Python Getting Started
Fixes:
- removed `You can also use AIConfigRuntime.loadJSON({})` for python. Its possible to load Json (dictionaries)  but not with that syntax
- Step 2, specify `options=` for inference options
- Step 3, specify `options=` for inference options
- Step 4: correct `run_with_dependencies`
> [DOCS] Fix Python Getting Started

- .github/workflows/deploy-docs.yml
[Docs] Set CNAME in docs deployment
Setting up `aiconfig.lastmileai.dev`
For more info, see:
* https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-add-cname-file-cname
* https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/138).
* __->__ #138
* #137
* #136
* #134
* #133
* #132
* #131
* #130
* #129
* #128
> [Docs] Set CNAME in docs deployment

- README.md
[Readme] Add AIConfig overview
Still wip
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/148).
* __->__ #148
* #146
* #145
* #144
* #140
* #139
* #138
* #137
* #136
* #134
* #133
* #132
* #131
* #130
* #129
* #128
> [Readme] Add AIConfig overview

- python/requirements.txt
- python/src/aiconfig/ChatCompletion.py
[Python] Openai Wrapper improvements
1. Save outputs
2. Allow passing a file path
3. Allow passing an AIConfig object
4. Persist output with streaming enabled (pass through streaming)
Notes:
- With streaming, we can either capture the response and not return it to the user or use pass through streaming, but, if the stream completion is not fully iterated through, ie the user doesn't touch the completion, completion args doesn't get serialized. Can't do both due to the nature of what it entails
- - chose to go with pass through streaming
- If the completion has a prompt that is already in the config (same input, settings, etc) but different outputs, the outputs are overriden with the new one
- if one completion is streamed, and another is not, those are considered different prompts and get …
> [Python] Openai Wrapper improvements

- aiconfig-docs/docs/introduction/getting-started.md
- cookbook/Basic-Prompt-Routing/README.md
[Cookbook README] Updated Readme
Updated readme for basic prompting demo
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/179).
* __->__ #179
* #178
> [AIConfig Cookbook] Updated Readme for Basic Prompt Routing Demo

- aiconfig-docs/docs/introduction/getting-started.md
[AIConfig Docs] Edits to Getting Started
- removed params=none from getting started
- added gtihub link for travel.aiconfig.json
- linked getting started cookbok
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/178).
* #179
* __->__ #178
> [AIConfig Docs] Edits to Getting Started

- aiconfig-docs/docs/introduction/basics.md
[AIConfig Docs] Added Videos to Intro Docs
Added 2 Videos to "What is AI Config":
1. Create a workbook from AIConfig
2. Download AIConfig from Workbook
I tried GIFs but it felt noisy on the page and I thought the video was nice to pause in case you needed it. The videos are short anyways.
> [AIConfig Docs] Added Videos to Intro Docs

- cookbooks/HuggingFace/Mistral-aiconfig.json
- cookbooks/HuggingFace/python/ask-mistral.py
- python/pyproject.toml
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/hf.py
- typescript/demo/test-hf.ts
- typescript/lib/config.ts
- typescript/lib/parsers/hf.ts
[TS] HuggingFaceTextGenerationParser as a default parser
- Bring back HuggingFaceTextGenerationParser into AIConfig.
- Modified Cookbook to test; will be updating cookbook with extension later
- Updated modelParser name to `HuggingFaceTextGenerationParser` everywhere used
Discussed offline @Saquadri
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/188).
* __->__ #188
* #187
* #185
> [TS] HuggingFaceTextGenerationParser as a default parser

- python/pyproject.toml
[py] Bump to 1.0.9
Republished AIConfig to 1.0.8 Changes Made Locally:
updated dependencies in pyproject.toml, should be good to go on that front.
(small) added an await statement that was missing for a callback
changes made locally
If any problems arise please let me know, I will fix asap.
1.0.9:
- Updated openai version to >1.0.0
- updated model parser and wrapper as well
> [py] Bump to 1.0.9

- cookbooks/llama/typescript/ask-llama.ts
- cookbooks/llama/typescript/package.json
- cookbooks/llama/typescript/yarn.lock
- extensions/llama/typescript/README.md
- extensions/llama/typescript/llama.ts
- extensions/llama/typescript/package.json
- extensions/llama/typescript/yarn.lock
With the Callbacks exposed for use in the latest `aiconfig` npm package, this PR updates the `LlamaModelParser` extension in ts to emit all the default ModelParser callback events.
Also, fixes the `run` implementation to save the outputs to the prompt for now
Updated & ran the `ask-llama.ts` cookbook to test out callback handlers being called with the events
> Add Callback Events to LlamaModelParser

- README.md
- aiconfig-docs/docs/extensibility.md
I realized there is already documentation for ModelParsers and extensibility, and don't think there's much more to add. This just cleans up the page a bit to get rid of some redundant headers, split some stuff (Callbacks & Metadata) outside of ModelParsers and point to Contributing Guidelines for those who want to share their ModelParsers as extensions
> Minor Cleanup of Extensibility Page

- CONTRIBUTING.md
- aiconfig-docs/docs/contributing.md
Went through the CONTRIBUTING.md file and copied over to the docs site, fixing some stuff as I read through (minor wording changes, fixed a few links, fixed format of **{ Code Contributions }** etc since those fail compilation on the doc site.
> Add Contributing Guidelines to Docs Site

- README.md
- aiconfig-docs/docs/basics.md
- aiconfig-docs/docs/extensibility.md
- aiconfig-docs/docusaurus.config.js
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/250).
* __->__ #250
* #249
* #246
> Fix formatting of Callback Event object keys

- aiconfig-docs/docusaurus.config.js
Remove 'Edit this page' Link on All Pages
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/246).
* #250
* #249
* __->__ #246
> Remove 'Edit this page' Link on All Pages

- python/README_dev.md
Make README_dev more clear for understanding why packages are required
Also fixed typo for requirements-dev.txt
> Make README_dev more clear for understanding why packages are required

- typescript/lib/parsers/hf.ts
When using the HF parser as an example for Llama, I noticed it didn't correctly set the prompt output during `run`. This PR correctly sets it, similar to the openai parser
- Added jest tests in https://github.com/lastmile-ai/aiconfig/pull/283
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/279).
* #283
* #282
* #281
* #280
* __->__ #279
> [ts] Add outputs to Prompt in HF Parser

- typescript/lib/parsers/hf.ts
This core ModelParser was missing all the callbacks, so add them here.
- Added jest tests in https://github.com/lastmile-ai/aiconfig/pull/283
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/280).
* #283
* #282
* #281
* __->__ #280
* #279
> Add Callbacks to Core HF ModelParser

- typescript/lib/callback.ts
- typescript/lib/parsers/hf.ts
When running `yarn test` there's an informative warning:
> Jest did not exit one second after the test run has completed.
'This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
Re-running with `--detectOpenHandles` surfaced:
```
Jest has detected the following 4 open handles potentially keeping Jest from exiting:
●  Timeout
23 | ): Promise<any> {
24 |   const timeoutPromise = new Promise((_, reject) => {
> 25 |     setTimeout(() => {
|     ^
26 |       reject(new Error("Timeout"));
27 |     }, timeout * 1000);
28 |   });
at lib/callback.ts:25:5
at lib/callback.ts:24:26
```
The problem is the timeout is still active ones the Promise is resolved. We can close the open handle …
> Close Open Handle in `withTimeout`

- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/dalle.py
[dall-e parser][1/n] Initial AIConfig Python parser for Dall-E 3 (non-streaming)
This takes in inputs from the AIConfig and saves them as outputs in the AIConfig prompt.
Right now this only supports
- non-streaming (will add streaming next diff)
- Dall-E 3 (will make the parser class more generic to support both Dall-E 3 and Dall-E 2 in future diff)
- Python
Results
Using color as yellow (the metadata text says green with yellow hue)
Using color as red
The input and output AIConfigs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/288).
* #295
* #294
* #290
* __->__ #288
> [dall-e parser][1/n] Initial AIConfig Python parser for Dall-E 3 (non-streaming)

- python/src/aiconfig/default_parsers/dalle.py
- python/tests/aiconfigs/basic_dalle3_config.json
- python/tests/parsers/test_dalle_parser.py
- python/tests/test_load_config.py
[dall-e parser][3/n] Add basic tests for load and serialize
Pretty simple, just adding in the tests which I already did manually to test the previous commits
Specifically I added tests for `load()` and `serialize()`. Found an error on serialize through this test (had to define function as `async`!
Should now be able to run tests by entering:
```
cd ~/Projects/aiconfig/python && pytest --disable-warnings -vv
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/294).
* #301
* #298
* #297
* __->__ #294
> [dall-e parser][3/n] Add basic tests for load and serialize

- cookbooks/llama/typescript/README.md
- extensions/llama/typescript/README.md
- extensions/llama/typescript/package.json
A few minor things:
- fix cookbook README video (should play video inline in GH README, as opposed to the video element needed for the doc site)
- link to the GH repo in the package metadata and the package README
Will publish once accepted
> Update Llama Extension Package Info With Links

- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/dalle.py
- python/tests/aiconfigs/basic_dalle2_config.json
- python/tests/test_load_config.py
[dall-e parser][5/n] Add mime type for urls (png) and base64 (plaintext)
Didn't know about this until now, wasn't adding it earlier.
The common MIME types are listed here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
| Before | After |
|---|---|
| <img width="672" alt="Screenshot 2023-11-20 at 18 11 17" src="https://github.com/lastmile-ai/aiconfig/assets/151060367/75bc9b3a-494a-400f-8405-afdff5bcf093"> | <img width="684" alt="Screenshot 2023-11-20 at 18 15 55" src="https://github.com/lastmile-ai/aiconfig/assets/151060367/b2a1f88a-c0a7-4b73-ac7b-076ca5e0ea5a"> |
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/298).
* __->__ #298
* #297
> [dall-e parser][5/n] Add mime type for urls (png) and base64 (plaintext)

- python/src/aiconfig/schema.py
- typescript/lib/config.ts
[py][ts] rename prompt name when adding a prompt
when given a name when adding a prompt, rename the prompt object's name.
The prompt object wasn't being renamed. If a user provides a different name, the Prompt object and config Names will diverge (unintended side effect)
> [py][ts] rename prompt name when adding a prompt

- aiconfig-docs/docs/overview/create-an-aiconfig.md
Update the README for create an aiconfig files
This wouldn't run because of
1. asyncio with await statements
2. changing typo in `include_outputs=`
> Update the README for create an aiconfig files

- extensions/HuggingFace/typescript/hf.ts
[extensions][ts] 1/n Update to Model Parser impl
1. Copied over ts implementation from core library
2. two smaller changes
- model.id()
- - `HuggingFaceTextGenerationParser` -> `HuggingFaceTextGenerationModelParserExtension`
- modelparser class name
- - `HuggingFaceTextGenerationParser` -> `HuggingFaceTextGenerationModelParserExtension`
Starting diff for stack to create an extension that serves as an example on how to write a model parser extension including comprehensive docs, docstrings, etc.
Consequently, the model id has to differ as the library already has HuggingFace model parser
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/314).
* #315
* __->__ #314
* #312
> [extensions][ts] 1/n Update to Model Parser impl

- schema/aiconfig.schema.json
- typescript/__tests__/config.test.ts
- typescript/__tests__/parsers/hf/hf.test.ts
- typescript/__tests__/testProgramaticallyCreateConfig.ts
- typescript/lib/config.ts
- typescript/types.ts
Make prompt.metadata Optional in Schema and TS Prompt Type
This ensure the typescript implementation and the schema definition match existing python implementation and desired functionality -- the metadata isn't always needed and no point in having it be an empty object
```
ryanholinshead@Ryans-MacBook-Pro typescript % yarn test
$ jest --runInBand
PASS  __tests__/testProgramaticallyCreateConfig.ts
test Get Global Settings
✓ Retrieving global setting from AIConfig with 1 model (1 ms)
ExtractOverrideSettings function
✓ Should return initial settings when no global settings are defined
✓ Should return an override when initial settings differ from global settings
✓ Should return empty override when global settings match initial settings (10 ms)
✓ Should return empty override …
```
> Make prompt.metadata Optional in Schema and TS Prompt Type

- python/src/aiconfig/default_parsers/dalle.py
- python/src/aiconfig/default_parsers/hf.py
- python/src/aiconfig/default_parsers/parameterized_model_parser.py
[AIC-py] uncycle some imports
This is enough uncycling to get the tests to pass after isort.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/330).
* #328
* __->__ #330
> [AIC-py] uncycle some imports

- python/pyproject.toml
[py] bump version 1.1.1 -> 1.1.2 -> 1.1.3
bump pytoml version to encompass Bug Fix in diff below. Package was republished under 1.1.2
Edit:
bumped to 1.1.3 to incorporate PR#318
> [py] bump version 1.1.1 -> 1.1.2 -> 1.1.3

- python/src/aiconfig/default_parsers/openai.py
Fix openai streaming
This reverts changes to openai.py made in #332, which are no longer needed (and contained a bug) after #334.
> Fix openai streaming

- cookbooks/Getting-Started/README.md
Add Getting Started Tutorial video to cookbook readme
Will also add it to docs and main readme as a follow-up
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/355).
* __->__ #355
* #354
> Add Getting Started Tutorial video to cookbook readme

- .github/workflows/main_python.yml
new github action for merge
New GithubAction for Python Tests that runs after a pr is merged
This way we can link the tests_passing badge on readme to main rather than the latest PR
> new github action on merge for ReadMe Badge

- python/requirements-dev.txt
- python/requirements.txt
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/hugging_face_transformers/text_generation.py
[hf parsers][2/n] Use completion params in text generation transformer
Just a bit of playing around to make sure that we can pass in full completion params. The API for this is https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationConfig
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/345).
* #380
* #379
* #351
* #363
* #348
* __->__ #345
* #344
> [hf parsers][2/n] Use completion params in text generation transformer

- python/requirements-dev.txt
- python/requirements.txt
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/hugging_face_transformers/text_generation.py
[hf parsers][3/n] Add streaming for text generation transformer
Streaming now enabled using the `TextIteratorStreamer` object: https://huggingface.co/docs/transformers/v4.35.2/en/internal/generation_utils#transformers.TextIteratorStreamer
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/348).
* #380
* #379
* #351
* #363
* __->__ #348
* #345
* #344
> [hf parsers][3/n] Add streaming for text generation transformer

- python/requirements-dev.txt
- python/requirements.txt
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/hugging_face_transformers/text_generation.py
- python/src/aiconfig/registry.py
- typescript/lib/modelParserRegistry.ts
[hf parsers][4/n] Do not use hardcoded value for model
TSIA, we're now able to pass in a model name during the constructor through the AIConfig
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/351).
* #380
* #379
* __->__ #351
* #363
* #348
* #345
* #344
> [hf parsers][4/n] Do not use hardcoded value for model

- extensions/HuggingFaceTransformers/python/LICENSE
- extensions/HuggingFaceTransformers/python/README.md
Add README and LICENSE within the python extension dir
Also need this for publishing the extension
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/385).
* __->__ #385
* #384
> Add README and LICENSE within the python extension dir

- python/src/aiconfig/eval/promptfoo/README.md
- python/src/aiconfig/eval/promptfoo/examples/travel/travel_aiconfig_test_suite_settings.json
- python/src/aiconfig/eval/promptfoo/examples/travel/travel_parametrized_for_testing.aiconfig.json
- python/src/aiconfig/eval/promptfoo/examples/travel/travel_promptfooconfig.yaml
- python/src/aiconfig/eval/promptfoo/run_aiconfig.py
- typescript/scripts/eval/promptfoo/README.md
- typescript/scripts/eval/promptfoo/examples/travel/travel_aiconfig_test_suite_settings.json
- typescript/scripts/eval/promptfoo/examples/travel/travel_parametrized_for_testing.aiconfig.json
- typescript/scripts/eval/promptfoo/examples/travel/travel_promptfooconfig.yaml
- typescript/scripts/eval/promptfoo/run_aiconfig.ts
[AIC-py] promptfoo integration prototype
Make a custom provider using AIConfig and configure it with promptfoo yaml.
Run (TS connector):
`npx promptfoo@latest eval -c typescript/scripts/eval/promptfoo/examples/travel/travel_promptfooconfig.yaml`
Run (Py connector):
`npx promptfoo@latest eval -c python/src/aiconfig/eval/promptfoo/examples/travel/travel_promptfooconfig.yaml`
> [AIC-py] promptfoo integration prototype

- extensions/llama/python/pyproject.toml
[AIC-py] add llama model parser extension project file
v0.0.1 is published but this file was missing.
> [AIC-py] add llama model parser extension project file

- python/pyproject.toml
- typescript/package.json
Version Bumps
Python
- 1.1.3 -> 1.1.4
Node
- 1.0.6 -> 1.0.7
note: current release is 1.0.6. so this change is now 1.0.5 -> 1.0.6 -> 1.0.7
> Version Bumps for first changelog

- extensions/HuggingFaceTransformers/python/src/aiconfig_extension_hugging_face_transformers/text_generation.py
- python/src/aiconfig/schema.py
[hf parser] Fix bug where we're not properly appending outputs for multiple return sequences
Minor bug fix I noticed that I messed up when adding streaming support in https://github.com/lastmile-ai/aiconfig/pull/380 (after I already supported multiple inputs in https://github.com/lastmile-ai/aiconfig/pull/345). The reason i missed this is that streaming only supports a single return sequence so didn't end up testing for multiple non-streaming. We should have automated tests. Added GH issue in
Tested by reabsing onto: https://github.com/lastmile-ai/aiconfig/pull/412
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/411).
* #414
* __->__ #411
* #410
> [hf parser] Fix bug where we're not properly appending outputs for multiple return sequences

- python/requirements.txt
Fixed typo for last-mile utils dependency
TSIA, see the install command from https://pypi.org/project/lastmile-utils/
Before
```
rossdancraig@MacBook-Pro python % pip list | grep lastmile_utils
```
After
```
rossdancraig@MacBook-Pro python %  pip3 list | grep lastmile
lastmile-utils                               0.0.6
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/418).
* #419
* __->__ #418
> Fixed typo for last-mile utils dependency

- python/src/aiconfig/default_parsers/hf.py
[py] Bug Fix: add back removed import
- added back import for `resolve_pompt()` method of parameterization util
- slight update to streaming logic to respect streaming options
This import was previously removed and has been a breaking change
[issue 442](https://github.com/lastmile-ai/aiconfig/issues/442)
> [py] Bug Fix: add back removed import

- python/src/aiconfig/schema.py
- schema/aiconfig.schema.json
- typescript/demo/demo.ts
- typescript/lib/parsers/openai.ts
- typescript/package-lock.json
- typescript/package.json
- typescript/types.ts
- typescript/yarn.lock
"Commandeering" https://github.com/lastmile-ai/aiconfig/pull/360 here (not sure if it's possible to update the existing PR) and addressing the feedback + reflecting changes in the JSON schema itself.
This adds the `attachments` field to to PromptInput objects to support attaching non-text data of different MIME types to prompt inputs. Note that this was technically already supported by the generic input data, but we should instead use attachments as the de facto way to do this.
- `yarn test` for typescript tests
```
ryanholinshead@Ryans-MacBook-Pro typescript % yarn test
$ jest --runInBand
PASS  __tests__/config.test.ts
Loading an AIConfig
✓ loading a basic chatgpt query config (8 ms)
✓ loading a prompt chain (4 ms)
✓ deserialize and re-serialize a prompt chain (2 ms)
✓ …
```
> Add attachments field to PromptInput

- cookbooks/Function-Calling-OpenAI/python/Function_Calling_with_OpenAI.ipynb
- cookbooks/Getting-Started/getting_started.ipynb
- python/pyproject.toml
Bump pypi package version to 1.1.6 to support Prompt Input Attachments
With the Attachments added to the config schema, bumping the package version to 1.1.6 prior to publishing to pypi.
Tested successfully on the Getting Started and Function Calling cookbooks (moved python function calling one to python dir)
> Bump pypi package version to 1.1.6 to support Prompt Input Attachments

- cli/aiconfig-editor/src/components/prompt/PromptContainer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/PromptInputConfigRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/PromptInputRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/schema_renderer/PromptInputAttachmentsSchemaRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/schema_renderer/PromptInputDataSchemaRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_metadata/PromptMetadataRenderer.tsx
- cli/aiconfig-editor/src/shared/prompt_schemas/OpenAIChatVisionModelParserPromptSchema.ts
- cli/aiconfig-editor/src/utils/promptUtils.ts
- cli/aiconfig-editor/travel.aiconfig.json
Implement the basis for rendering prompt inputs -- each may be rendered directly from the config or from the Prompt schema associated with the model parser.
Using GPT4-V as an example, created a schema `OpenAIChatVisionModelParserPromptSchema` which outlines how attachments can be specified.
Once https://github.com/lastmile-ai/aiconfig/pull/360 we can implement the attachments rendering more completely.
Quick video showing updating input and input.data and saving properly persists it to the config on disk:
https://github.com/lastmile-ai/aiconfig/assets/5060851/8f7f8adf-741e-493d-9cbf-837b9afc533f
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/398).
* #482
* __->__ #398
> [5/n] Scaffolding for Prompt Input via Schema

- aiconfig-docs/core/tabConstants.js
- aiconfig-docs/docs/getting-started.md
- aiconfig-docs/docs/overview/create-an-aiconfig.md
- aiconfig-docs/docs/overview/define-prompt-chain.md
- aiconfig-docs/docs/overview/monitoring-aiconfig.md
- aiconfig-docs/docs/overview/parameters.md
- aiconfig-docs/docs/overview/run-aiconfig.md
Make sure all example code / tabs prioritizes showing python since that's the most common language for AIConfig usage. The order is actually determined by the order in the `aiConfigLanguages` array in tab constants, but this PR also updates the tabs defined in the md code to reflect the intended ordering.
- Went through each page and each tab toggle to ensure correctness
e.g.
https://github.com/lastmile-ai/aiconfig/assets/5060851/b852005d-2620-414e-a226-7a885cc95622
> Prioritize python example code tab in docs

- python/src/aiconfig/Config.py
- typescript/lib/config.ts
[py][ts] Clear outputs before running
Remove the outputs of the prompt when run() is called
previous outputs stay cached. This introduces unintended side effects
Run a prompt twice, expect the same output without any changes. This is the result of the output no longer being cached on a new run
TS:
Py:
Added print statements to verify outputs were getting removed
> [py][ts] Clear outputs before running

- .vscode/settings.json
Increase VSCode Formatter Line Length to 150
> Increase VSCode Formatter Line Length to 150

- FAQ.md
- README.md
- aiconfig-docs/wip_docs/readme_v0.md
[docathon] updated readme
updated the readme as part of docathan to be much more concise.
- moved v0 of readme to wip_docs
- renamed contributing section to be more clear
- linked the changelog
- redirects to full documentation for more information on SDK details, faqs, and other resources that were here before.
> [docathon] updated readme

- aiconfig-docs/docs/getting-started.md
[docs] 1/n Update getting started Code Snippets
Small changes that make it easier to copy paste and run (and have it work)
> [docs] 1/n Update getting started Code Snippets

- typescript/lib/config.ts
Remove PromptWithOutputs type
Fix for #365
> Remove PromptWithOutputs type

- python/src/aiconfig/schema.py
[ez][documentation] Making error message for unfound param to delete more clear where we're trying to look for it
TSIA
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/504).
* #507
* __->__ #504
* #502
> [ez][documentation] Making error message for unfound param to delete more clear where we're trying to look for it

- python/src/aiconfig/schema.py
[documentation] Add comment to add code issue when update_model but model parser isn't connected or registered
Will also create GH issue for this
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/502).
* #507
* #504
* __->__ #502
> [documentation] Add comment to add code issue when update_model but model parser isn't connected or registered

- python/requirements.txt
[py] pin openai to a range of versions
pin openai dependency to 1.0.0 < x < 1.5
OpenAI updated the api to 1.5. https://github.com/openai/openai-python/releases/tag/v1.5.0
Looks like the new version updates the Chat Completion type with a new field `logprobs`
> [py] pin openai dependency to < 1.5

- typescript/package.json
[ts] Pin OpenAI to 4.11.1
Pin OpenAI Typescript dependency to 4.11.1.
Tested the Function Call Stream demo where OpenAI was set to openai@4.23.0
This failed due to a missing attribute `function_call` from type `ChatCompletionMessageParam`. Not entirely sure  if this breaks library atm.
Previously We've been working with `4.11.1`.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/524).
* #520
* __->__ #524
> [ts] Pin OpenAI to 4.11.1

- python/src/aiconfig/schema.py
- python/tests/test_programmatically_create_an_AIConfig.py
Refactor update_model() API to be more user friendly and flexible
See The last part of https://github.com/lastmile-ai/aiconfig/issues/503
This greatly makes the `update_model()` API way more flexible. Instead of needing to set the entire ModelSettings (which can be annoying because you have to first retrieve the settings from the prompt to even set the modelMetadata to pass into your argument), you can now do each part individually:
1. Set both the model name and model settings: `update_model(name="my_name", settings="my_settings")` --> pass in prompt_name arg to update at prompt-level, do not pass to update at AI-Config level
2. Set the model name only: `update_model(name="my_name")` --> pass in prompt_name arg to update at prompt-level, do not pass to update at AI-Config level
3. Set …
> Refactor update_model() API to be more user friendly and flexible

- cli/aiconfig-editor/pages/api/aiconfig/save.ts
[editor] Fix Save to Properly Serialize
When opening a file in the editor we load the config into an AIConfigRuntime and send that to the client. On the client, we are modifying this serialized object and sending it to the server on save. Previously, save was just JSON serializing this to a string to save directly, which resulted in some fields (e.g. CallbackManager) being saved as well. Instead, this PR updates save to properly serialize to an AIConfig and leverages the config save method to ensure proper contents are saved to disk. As a bonus, this will also result in implicit validation of the config structure (when we add validation via the schema that will be explicit as well)
- Make a change in the editor & save, ensuring only that change is persisted (no more CallbackManager)
--- …
> [editor] Fix Save to Properly Serialize

- cli/aiconfig-editor/package.json
- cli/aiconfig-editor/pages/api/aiconfig/save.ts
- cli/aiconfig-editor/src/components/EditorContainer.tsx
- cli/aiconfig-editor/src/components/aiconfigReducer.ts
- cli/aiconfig-editor/src/components/prompt/model_settings/ModelSettingsRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/model_settings/ModelSettingsSchemaRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/attachments/Attachment.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/attachments/AttachmentContainer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/attachments/AttachmentMetadata.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/attachments/AttachmentUploader.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/schema_renderer/PromptInputAttachmentsSchemaRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- cli/aiconfig-editor/src/components/prompt/prompt_metadata/PromptMetadataRenderer.tsx
- cli/aiconfig-editor/src/hooks/useSchemaState.ts
- cli/aiconfig-editor/src/utils/dropzoneHelpers.ts
- cli/aiconfig-editor/src/utils/promptUtils.ts
- cli/aiconfig-editor/yarn.lock
[editor] Move aiconfig state to reducer
Implement an aiconfigReducer for managing the client-side AIConfig state, with UPDATE_PROMPT_INPUT as the first action. Note that we won't be propagating dispatch through to nested components for 2 main reasons:
1. Actions should be dispatched from the "root" EditorContainer so that they can also propagate event data to the server-side config. The root will be the interface between client and server
2. We will want to support custom user-provided PromptContainers and PromptInputRenderers but want to make it hard for such components to accidentally modify state unrelated to their prompt. As a result, we should leverage props for passing callbacks to these components instead of allowing them to dispatch arbitrary actions
Based on the above, the common …
> [editor] Move aiconfig state to reducer

- cookbooks/Getting-Started/travel.aiconfig.json
- python/src/aiconfig/default_parsers/openai.py
[ez] Check for nullable system prompt
We should really have automated tests more in our cookbooks to catch these issues, weird
This is NOT a thorough solution, just quickly unblocking. Filed an issue to investigate deeper and make sure we have better null-checks: https://github.com/lastmile-ai/aiconfig/issues/543
> [ez] Check for nullable system prompt

- python/src/aiconfig/eval/common.py
- python/src/aiconfig/eval/lib.py
- python/src/aiconfig/eval/metrics.py
- python/src/aiconfig/eval/openai.py
- python/tests/mocks.py
- python/tests/test_eval.py
[AIC-py][eval] bundle of small easy fixes
- freeze dataclasses
- wire up eval fn timeout further (there is a little more to go)
- move mock aiconfig runtime to separate file
-
see https://docs.google.com/document/d/15gx4vVmKVgI5bDHjSDd8xCQmTGcC8RrtLU0iCa32AIQ/edit
> [AIC-py][eval] bundle of small easy fixes

- cli/aiconfig-editor/src/components/SettingsPropertyRenderer.tsx
- cli/aiconfig-editor/src/shared/prompt_schemas/OpenAIChatModelParserPromptSchema.ts
Fix a bug in the settings renderer copied from workbooks -- currently, just opening the settings tab and saving the workbook will persist a model settings object for the prompt. The cause of this is the use of the `useEffect` for handling changes -- `useEffect` will always run once on mount of the component so it was always persisting the empty settings on mount.
To fix, just check that the value has actually changed before persisting it to the config.
- Open settings & save config without touching anything. See the config has no changes
- Change system prompt and save, ensure it's persisted to the config
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/551).
* #552
* __->__ #551
> [editor] Only Persist Changed Model Settings

- extensions/Gemini/python/requirements.txt
- extensions/Gemini/python/src/aiconfig_extension_gemini/Gemini.py
4/n Update output serialization with pb
When saving outputs to config, get the underlying protobuf of Gemini's response object and save as a dict
Also added some comments cc: @rossdanlm
When doing `aiconfig.save()`, pydantic is unable to deserialze the output metadata which contains a protobuf from Gemini's response. Gemini response object is a wrapper around a protobuf. Need to convert to an object that is compatible with pydantic.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/558).
* __->__ #558
* #534
* #531
* #532
> 4/n Update output serialization with pb

- extensions/Gemini/python/src/aiconfig_extension_gemini/Gemini.py
2/n Gemini Serialize()
Implemented the serialize() method of the Gemini Model parser
The gemini api is a bit trickier than previous api's we've seen before. Using the OpenAI api as a comparison point, the Gemini api is a little bit more complex.
The request takes in a contents field, which can have various types. This is because the api supports
- one shot prompts
- one shot prompting but with multiple "parts"
- multi-turn conversation with multiple parts
- multi-modal one shot with multiple parts (out of scope of this diff)
Note: `part` refers to some form of data. Either a string, a proto, a blob, or mime typed data. Gemini api has done a good job in supporting a wide array of use cases.
For simplicity, I've limited the serialize() functionality to string objects or list/dict objects …
> 2/n Gemini Serialize()

- cli/aiconfig-editor/src/components/SettingsPropertyRenderer.tsx
- cli/aiconfig-editor/src/components/property_controls/UnionPropertyControl.tsx
- cli/aiconfig-editor/src/shared/prompt_schemas/OpenAIChatModelParserPromptSchema.ts
Handle 'union' properties in the settings renderer to support properties that could be one of a union of types, rendering a `UnionPropertyControl` component whenever the property type is `union`. This required two main considerations:
1. Use a callback for setting the state/value instead of an effect; this ensures the value is set when they change instead of when the component mounts
2. Render a UnionPropertyControl with a render prop to render nested SettingsPropertyRenderers based on the property types (rendering SettingsPropertyRenderer directly in UnionPropertyControl could cause a cycle)
- Set both values and ensure the correct value is set in the config:
https://github.com/lastmile-ai/aiconfig/assets/5060851/05202282-f6f9-4dae-834c-be47be6aed43
> [editor] Union Settings Property

- python/src/aiconfig/Config.py
- python/src/aiconfig/model_parser.py
[py] Batch Execution fix inconsistent outputs
1. Resolved an inconsistency between the prompt object in the deep copy and the one used for execution. Ensures the correct Prompt object is used during Batch Execution.
2. Also added an extra step of clearing outputs inside run_batch, similarly to #490
-  Python SDK checks for the existence of Prompt objects within the AIConfigRuntime, evaluating more than just their names.
- In Batch Execution, a deep copy of AIConfigRuntime is created, which also duplicates the Prompt objects. This update addresses the issue where previously a stale prompt object might have been used.
- rebased onto [this commit](https://github.com/lastmile-ai/aiconfig/pull/553/files) and tested with the python notebook provided by @2timesJay. The batch execution operated …
> [py] Batch Execution fix inconsistent outputs

- cookbooks/Gemini/Gemini.ipynb
- extensions/Gemini/python/pyproject.toml
- extensions/Gemini/python/requirements.txt
- extensions/Gemini/python/src/aiconfig_extension_gemini/Gemini.py
[extensions] gemini bump extension package version; update dependencies before publish
- bump pyproject toml
- Removed @override, this doesn't exist outside of python 3.12
- removed copy from requirements.txt, this is included in python; does not need to be pip installed.
To update public release with updated functionality to serialize and deserialize() for GEmini Model parser
Run through the Gemini cookbook succesfully with local pip install
> [extensions] gemini bump extension package version; update dependencies before publish

- python/requirements.txt
- python/src/aiconfig/Config.py
Unpin requests dependency and fix jason validator from load_from_workbook() API
Unpin `requests` dependency and fix jason validator from `load_from_workbook()` API
This diff addresses two separate issues, but one was needed before I could debug the second.
1. Before you'd get an error if trying to do JSON model validator because struct is now a dict, so instead we are just using `**` directly into `cls` where it'll be validated in the init file for `AIConfigRuntime` obj since it's a BaseModel.
2. Also did some investigation into why `requests` was pinned to v 2.30.0. The only difference I could find between that and v2.31.0 is that in 2.31.0 it doesn't seem to support `https:` and would only support `http:`. However, I tried testing this with both versions, and it still seems to work, so …
> Unpin requests dependency and fix jason validator from load_from_workbook() API

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/editor/server/server_utils.py
- python/src/aiconfig/scripts/aiconfig_cli.py
[AIC-py][editor] split server into 2 files
This is getting kind of unweildy. Move most of the hleper functions into server_utils,
leaving the core server stuff (mainly endpoints).
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/580).
* __->__ #580
* #579
* #576
* #575
> [AIC-py][editor] split server into 2 files

- python/requirements.txt
- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/scripts/aiconfig_cli.py
[editor] Enable CORS for /api/* requests
Sending a request to `localhost:8080/api/load` on the client is currently failing due to CORS (cross origin from localhost:3000). To fix, just enable all origins for the api requests for now, following https://flask-cors.readthedocs.io/en/latest/#using-json-with-cors. We can consider restricting the allowed origins as needed
Testing: Can now send a request from the client and get a response ('Done' right now) instead of CORS error
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/585).
* __->__ #585
* #584
> [editor] Enable CORS for /api/* requests

- python/src/aiconfig/scripts/aiconfig_cli.py
[editor] Fix argparsify command
When running the cli command, I was getting an error that `argparsify` doesn't support `subparser_record_types` command. So, change it to supported `subparser_rs`
Can now run `aiconfig edit --aiconfig-path=cli/aiconfig-editor/travel.aiconfig.json --server-port=8080 --server-mode=debug_servers` successfully
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/584).
* #585
* __->__ #584
> [editor] Fix argparsify command

- python/src/aiconfig/editor/client/package.json
- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_outputs/PromptOutputsRenderer.tsx
- python/src/aiconfig/editor/client/src/utils/api.ts
- python/src/aiconfig/editor/client/yarn.lock
Hit the `api/load` endpoint on the server port (with temporary hard-coded file path until we can load without path param) and ensure the editor loads:
> [editor] Load AIConfig on Client from Python Server

- python/requirements.txt
- python/src/aiconfig/Config.py
- python/src/aiconfig/util/config_utils.py
- typescript/lib/config.ts
- typescript/lib/utils.ts
- typescript/package.json
- typescript/yarn.lock
Add YAML serialization to aiconfig
YAML is a superset of JSON, and allows for much better readability. We can easily support YAML for AIConfig with our existing JSON schema.
I have also created a PR to add AIConfig schema to schemastore: https://github.com/SchemaStore/schemastore/pull/3474. Once that gets approved, it will automatically hook up syntax validation for *.aiconfig.yml/*.aiconfig.yaml, *.aiconfig.json in VSCode and other IDEs.
Test Plan:
(Tried in both TS and Python)
Validated idempotence of the following:
```
from aiconfig import AIConfigRuntime
config = AIConfigRuntime.load('travel.aiconfig.json')
config.save("travel.aiconfig.yaml", mode="yaml")
config = AIConfigRuntime.load('travel.aiconfig.yaml')
config.save("travel2.aiconfig.json")
config.save()
``` …
> Add YAML serialization to aiconfig

- python/src/aiconfig/schema.py
- schema/aiconfig.schema.json
- typescript/types.ts
[RFC] Output data type
Add some structure to the outputs that allow the frontend to know how to render them.
Still need to update the Python types, and modelparsers to return data in this type.
> [RFC] Output data type

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_generation.py
- python/src/aiconfig/default_parsers/hf.py
[easy][extensions][py][hf] 3/n Local Inference model parser changes
This diff is a copy paste of the diff below except for one difference:
1. ModelParser `id` name and class name
HuggingFace Extension contains a `local_inference` and a `remote_inference_client`.
`Remote_inference_client` and the core huggingface model parser in the sdk are the same implementation with the one difference of model parser id. The extension model parser id is `HuggingFaceTextGenerationClient`.
Note: Both of these model parsers are for Text Generation only. Other huggingface tasks are not supported on the inference-endpoint by aiconfig yet.
Some context onto why there's two extensions, one was supposed to serve as a guide and easy to write model parser. This guide has yet to be written.
--- …
> [easy][extensions][py][hf] 3/n Local Inference model parser changes

- python/src/aiconfig/default_parsers/hf.py
[py][model parser][hf]1/n type hints
Updated type hints in python sdk core model parser
This model Parser has not been updated for a while. Taking this upto par with the rest of the library
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/587).
* #597
* #588
* __->__ #587
> [py][model parser][hf]1/n type hints

- python/src/aiconfig/default_parsers/hf.py
[py][model parser][hf] 2/n callbacks
- Added callbacks to model parser.
- It doesn't look like there is any other issues with this specific model parser at the moment. More investigation required into logging/callbacks, parameterization as seen with mixtral issues.
This model Parser has not been updated for a while. Taking this upto par with the rest of the library
Ran through the getting started. Modified the config to use HuggingFace model parser and mixtral model
Note: Input prompt said generate 10 activities, got 15.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/588).
* #597
* __->__ #588
* #587
> [py][model parser][hf] 2/n callbacks

- python/src/aiconfig/schema.py
[AIC-py] optional: add prompt at index
add p3, add p4 at index 1.
```
[Prompt(name='get_activities', input='Tell me 10 fun attractions to do in NYC.', metadata=None, outputs=[]),
Prompt(name='p4', input='thep', metadata=None, outputs=[]),
Prompt(name='gen_itinerary', input='Generate an itinerary ordered by {{order_by}} for these activities: {{get_activities.output}}.', metadata=PromptMetadata(model='gpt-4', tags=None, parameters={'order_by': 'geographic location'}), outputs=[]),
Prompt(name='p3', input='thep', metadata=None, outputs=[])]
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/599).
* #600
* __->__ #599
> [AIC-py] optional: add prompt at index

- python/src/aiconfig/schema.py
[issue #454][AIC-py] get default model if no prompt model
Reproduced error
Confirmed now this uses gpt-3.5-turbo:
```
"default_model": "gpt-3.5-turbo"
{
"name": "get_activities",
"input": "Tell me 2 fun attractions to do in {{city}}.",
"metadata": {
"parameters": {
"city": "New York City"
}
}
}
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/600).
* __->__ #600
* #599
> [issue #454][AIC-py] get default model if no prompt model

- python/src/aiconfig/Config.py
- typescript/lib/config.ts
Add schema explicitly for JSON
Adding the $schema property to JSON with the schemastore schema. Currently our schema has just one version but in the future we should respect the schema that the config already has or introduce proper versioning.
Test Plan:
```
from aiconfig import AIConfigRuntime
config = AIConfigRuntime.load('travel.aiconfig.json')
config.save()
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/598).
* __->__ #598
* #589
> Add schema explicitly for JSON

- python/src/aiconfig/editor/client/src/utils/api.ts
In development, the client will be served via a node process from `react-scripts` at localhost:3000 by default. The python server will be at localhost:8080 by default.
In 'prod', the client will be bundled and statically served by the python server at the same port as the python server.
So, for prod we should make requests to '/api/*' which will resolve to the hostname/port of the server that served the JS.
For dev, we can just hardcode to the correct server port for now.
`yarn build` in `aiconfig/python/src/aiconfig/editor/client`
Then run the prod server mode: `aiconfig edit --aiconfig-path=cli/aiconfig-editor/travel.aiconfig.json --server-mode='prod'`
and see the editor at localhost:8080 sending correct requests
Simultaneously, start up on another port: …
> [editor] Fix Client Request API Endpoint to Work for Any Prod Port

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/travel.aiconfig.json
This test config is being removed from under the `/cli` dir in #622 where the entire `/cli` dir is being removed. So, move the file here to use for testing
`aiconfig edit --aiconfig-path=python/src/aiconfig/editor/travel.aiconfig.json --server-mode='debug_servers'` correctly loads the editor
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/623).
* #622
* __->__ #623
> [editor] Move Demo Editor travel.aiconfig.json to editor dir

- python/src/aiconfig/scripts/aiconfig_cli.py
[editor] Functionality to run server on multiple configs without specifying port
Before creating the server process, check if the port to be used is taken. If so, find the next available one before continuing
for context: this builds on top of #619 
When running the editor, user should be able to open multiple configs.
Under the hood this means spinning up another server in an unused port. Frontend already supports dynamic ports.
1. yarn build in aiconfig/python/src/aiconfig/editor/client
2. Open two aiconfigs with "prod" editor"
| Getting Started aiconfig | Chain Of Verification aiconfig|
|------------|-------------|
| ![Screenshot 1](https://github.com/lastmile-ai/aiconfig/assets/141073967/ae710711-17f6-498f-a5cb-6eee04baa8eb) |  ![Screenshot …
> [editor] Functionality to run server on multiple configs without specifying port

- cookbooks/HuggingFace/hf.py
- cookbooks/HuggingFace/python/hf.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_generation.py
- extensions/llama/python/llama.py
- python/src/aiconfig/default_parsers/dalle.py
- python/src/aiconfig/default_parsers/hf.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/default_parsers/palm.py
- python/src/aiconfig/default_parsers/parameterized_model_parser.py
[eng week] Set run output type to be list[Output] instead of Output
This diff is the same as #343, rebased onto main. Sapling decided to create a new pr.
Makes it more scalable. The Prompt schema already refers to `outputs` as `List[Output]` anyways
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/617).
* #618
* __->__ #617
> [eng week] Set run output type to be list[Output] instead of Output

- python/src/aiconfig/schema.py
- typescript/types.ts
[RFC] Add "function" as an explicit kind of output data
This can help us distinguish function calling from regular strings quickly -- since function calling is now supported across multiple models, it deserves to be a top-level output kind in the schema.
For example, current models that support it:
* GPT-3.5, GPT-4, GPT-4V
* Gemini
* [Mixtral (using Anyscale endpoints)](https://docs.endpoints.anyscale.com/guides/function-calling/#:~:text=With%20Anyscale%20Endpoints%2C%20you%20can,parameters%20to%20pass%20to%20it.)
* There will be more to come
> [RFC] Add "function" as an explicit kind of output data

- extensions/HuggingFace/typescript/hf.ts
- typescript/__tests__/parsers/hf/hf.test.ts
- typescript/demo/function-call-stream.ts
- typescript/lib/parsers/hf.ts
- typescript/lib/parsers/openai.ts
- typescript/lib/parsers/palm.ts
- typescript/package.json
- typescript/yarn.lock
[typescript] Save output.data with text content instead of response data
This comes after Sarmad's schema updates in https://github.com/lastmile-ai/aiconfig/pull/589. To keep diffs small and easier to review, this simply converts from model-specific outputs --> pure text. I have a diff in https://github.com/lastmile-ai/aiconfig/pull/610 which converts from pure text --> `OutputData` format.
We only needed to update the `hf.py` and `openai.py`, because `palm.py` already returns output in the form of `string | null` type.
Ran yarn automated tests, but there aren't any specifically for openai. I also ran the typescript demos to make sure that they still work. Run these commands from `aiconfig` top-level dir:
```
npx ts-node typescript/demo/function-call-stream.ts
npx ts-node …
```
> [typescript] Save output.data with text content instead of response data

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/editor/server/server_utils.py
- python/src/aiconfig/editor/travel.aiconfig.json
[bug fix][issue #627] pass the correct method arg name down to aiconfig save
Fix the argument name: "path" -> "config_filepath".
Also add a couple of related path fixes to make
other endpoints more robust.
Test:
Send requests to /load_model_parser_module, /load, and /save
with valid and invalid paths, and with incorrectly-named arguments.
Also make sure /load runs with no arguments.
Client code:
```
import requests
for url in [
'http://localhost:8080/api/load',
'http://localhost:8080/api/save',
'http://localhost:8080/api/load_model_parser_module',
]:
for data in [
{},
{
"path": "/Users/jonathan/Projects/aiconfig/my_aiconfig_model_registry.py"
},
{
"config_filepath": "fake"
},
{
"path": "python/src/aiconfig/editor/travel.aiconfig.json"
},
{
"path": …
```
> [bug fix][issue #627] pass the correct method arg name down to aiconfig save

- extensions/Gemini/python/src/aiconfig_extension_gemini/Gemini.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_generation.py
- extensions/llama/python/llama.py
- python/src/aiconfig/default_parsers/hf.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/default_parsers/palm.py
- python/tests/parsers/test_openai_util.py
[python][non-image]Save output.data with text content instead of response data
Same as last diff except now for Python.
Going to do the image outputs next diff because those actually require updating the data as a key-value pair with kinds and values
For extensions,
- Gemini and Llama-Guard are already in text output format, so not need to do any changes
- updated Llama and the HuggingFace ones (non-image)
Updated automated tests
> [python][non-image]Save output.data with text content instead of response data

- cookbooks/HuggingFace/hf.py
- cookbooks/HuggingFace/python/hf.py
- extensions/Gemini/python/src/aiconfig_extension_gemini/Gemini.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_2_image.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_generation.py
- extensions/LLama-Guard/python/python/src/aiconfig_extension_llama_guard/LLamaGuard.py
- extensions/llama/python/llama.py
- python/src/aiconfig/ChatCompletion.py
- python/src/aiconfig/default_parsers/dalle.py
- python/src/aiconfig/default_parsers/hf.py
- python/src/aiconfig/default_parsers/palm.py
- python/src/aiconfig/model_parser.py
[python][image] Save output.data images in OutputData format, not just strings
This will make it easy for Ryan on frontend to know exactly what data type we need. This is also backwards compatible for existing AIConfigs that have data saved only as a text string
##test
Automated tests
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/608).
* __->__ #608
* #632
> [python][image] Save output.data images in OutputData format, not just strings

- cookbooks/HuggingFace/hf.py
- cookbooks/HuggingFace/python/hf.py
- extensions/Gemini/python/src/aiconfig_extension_gemini/Gemini.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_2_image.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_generation.py
- extensions/LLama-Guard/python/python/src/aiconfig_extension_llama_guard/LLamaGuard.py
- extensions/llama/python/llama.py
- python/src/aiconfig/ChatCompletion.py
- python/src/aiconfig/default_parsers/dalle.py
- python/src/aiconfig/default_parsers/hf.py
- python/src/aiconfig/default_parsers/palm.py
- python/src/aiconfig/model_parser.py
[ez] Add `List[Prompt]` output type to all serialize methods
This caused confusion because typing wasn't clearly defined: https://github.com/lastmile-ai/aiconfig/pull/608#discussion_r1436528231
I also noticed that the `palm.py` one didn't actually return `prompts`, so I added it there too
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/632).
* #608
* __->__ #632
> [ez] Add `List[Prompt]` output type to all serialize methods

- schema/aiconfig.schema.json
- typescript/common.ts
Better typing for AIConfig schema
We had `JSONValue` defined as possibly `unknown` type, which made the schema generator ignore that type entirely.
This change removes that requirement, while still allowing flexibility for what gets assigned to `JSONObject`.
Regenerated the schema with `yarn gen-schema` and we get better typings now.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/635).
* #636
* #634
* __->__ #635
> Better typing for AIConfig schema

- python/src/aiconfig/__init__.py
- python/src/aiconfig/schema.py
- schema/aiconfig.schema.json
- typescript/common.ts
- typescript/types.ts
Export OutputData type
Need to export this so we can set it as explicit typing and not break typescript. Also this just makes it easier to manage now. Also removed the `[]` form from the function_call, because that's just a value not an array.
I also rebased on top of https://github.com/lastmile-ai/aiconfig/pull/631 (changed `unknown` --> `undefined`) because the schema wasn't be generated properly otherwise
Also made the python version `OutputData` also encompass function calls just like in typescript
```
cd typescript
yarn gen-schema
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/634).
* #636
* __->__ #634
* #635
> Export OutputData type

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_2_image.py
- python/src/aiconfig/__init__.py
- python/src/aiconfig/default_parsers/dalle.py
- python/src/aiconfig/schema.py
- schema/aiconfig.schema.json
- typescript/lib/parsers/openai.ts
- typescript/types.ts
Update output schema to not use {"string": string_value} as output data
See comment in https://github.com/lastmile-ai/aiconfig/pull/610#discussion_r1437099426
Now we're just going to directly check for the type being a pure string and not embedded within the `OutputData` object. I also renamed `OutputData` --> `OutputDataWithValue` to make this more explicit and easier to understand
Rebuilt the schema using `yarn gen-schema` from `aiconfig/typescript` dir
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/637).
* #610
* __->__ #637
> Update output schema to not use {"string": string_value} as output data

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/ParametersRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptActionBar.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptOutputBar.tsx
- python/src/aiconfig/editor/client/src/components/prompt/RunPromptButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/model_settings/ModelSettingsRenderer.tsx
Adding the [MantineProvider](https://mantine.dev/theming/mantine-provider/) around the editor to allow customizing theme/styles from the root component. This will allow differentiation between local editor and gradio
- Load editor without issue
- Temporarily set theme={{primaryColor: "red"}} and see the correct changes
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/640).
* __->__ #640
* #639
* #638
> [editor] Add MantineProvider to Unblock Styling Work

- python/src/aiconfig/editor/client/src/components/prompt/PromptActionBar.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptOutputBar.tsx
- python/src/aiconfig/editor/client/src/components/prompt/RunPromptButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/model_settings/ModelSettingsRenderer.tsx
[editor] Run Prompt Button UI
Adding the Run prompt button to the UI; will connect the callbacks/server request in subsequent PR
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/639).
* #640
* __->__ #639
* #638
> [editor] Run Prompt Button UI

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptActionBar.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/RunPromptButton.tsx
- python/src/aiconfig/editor/client/src/utils/aiconfigStateUtils.ts
- python/src/aiconfig/editor/client/src/utils/api.ts
Setting up the callbacks for `run_prompt`. The request succeeds but currently the response is not correct -- the aiconfig returned doesn't have the outputs. This is on main, so will land this and test with https://github.com/lastmile-ai/aiconfig/pull/615
A subsequent PR will also need to link local typescript aiconfig to our editor package.json in order to have the updated output types until we can publish the updated package. With the linking, I'll then add output rendering.
- Make sure /run request succeeds:
https://github.com/lastmile-ai/aiconfig/assets/5060851/2cacc07c-3bfe-4a63-8e74-f912b64260dd
> [editor] Set Up run_prompt Callbacks

- extensions/HuggingFace/typescript/hf.ts
- typescript/demo/function-call-stream.ts
- typescript/lib/parsers/hf.ts
- typescript/lib/parsers/openai.ts
- typescript/lib/parsers/palm.ts
[typescript] Use OutputDataWithValue type for function calls
After discussion and based on comments, we are going to keep pure string form as is, but still need to support non-pure string types to make sure that they're supported. Specifically images (which we don't have on ts) and function calls.
I didn't need to update the hugging face files because those already are just pure text
##Test plan
Pass automated tests, running these commands from `aiconfig` top-level dir
```
npx ts-node typescript/demo/function-call-stream.ts
npx ts-node typescript/demo/demo.ts
npx ts-node typescript/demo/test-hf.ts
```
Also run `yarn test` from typescript dir
> [typescript] Use OutputDataWithValue type for function calls

- cookbooks/HuggingFace/hf.py
- cookbooks/HuggingFace/python/hf.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_generation.py
- extensions/HuggingFace/typescript/hf.ts
- extensions/llama/python/llama.py
- extensions/llama/typescript/llama.ts
- python/src/aiconfig/default_parsers/dalle.py
- python/src/aiconfig/default_parsers/hf.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/default_parsers/palm.py
- python/src/aiconfig/default_parsers/parameterized_model_parser.py
- typescript/lib/config.ts
- typescript/lib/modelParser.ts
- typescript/lib/parameterizedModelParser.ts
- typescript/lib/parsers/hf.ts
- typescript/lib/parsers/openai.ts
[easy][ts] 2/n Set run output type to be Output[] instead of Union
Updating the types in the ts sdk to return `Output[]` instead of `Output | Output[]`
Run method should always return a array of outputs, even if its just one output.
The Prompt schema already refers to `outputs` as `outputs?: Output[];` anyways
Ran tests without errors. No type errors on compilation either
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/618).
* __->__ #618
* #617
> [easy][ts] 2/n Set run output type to be Output[] instead of Union

- cookbooks/llama/python/README.md
- extensions/llama/python/pyproject.toml
[ez] Rename llama extension to aiconfig_extension_llama
TSIA, we shouldn't be making this as part of the generalized `python_aiconfig` module since this is an extension
Will publish this package after it's been stamped
> [ez] Rename llama extension to aiconfig_extension_llama

- python/src/aiconfig/editor/client/package.json
- python/src/aiconfig/editor/client/src/components/prompt/model_settings/ModelSettingsConfigRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/model_settings/ModelSettingsSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputDataSchemaRenderer.tsx
- python/src/aiconfig/editor/client/yarn.lock
[easy] Reference local version of aiconfig package for local editor
While we iterate on the aiconfig schema and SDK, it's better to reference the latest code for the local editor (typescript side) to ensure we are in sync on the schema updates coming in.
It also means we don't need to publish to npm/pypi until we have let the changes bake.
> [easy] Reference local version of aiconfig package for local editor

- extensions/Gemini/python/src/aiconfig_extension_gemini/Gemini.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_generation.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_generation.py
- extensions/LLama-Guard/python/python/src/aiconfig_extension_llama_guard/LLamaGuard.py
- extensions/llama/python/llama.py
- python/src/aiconfig/default_parsers/hf.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/default_parsers/palm.py
- python/tests/parsers/test_openai_util.py
[python] Use OutputDataWithValue type for function calls
This is extending https://github.com/lastmile-ai/aiconfig/pull/605 where I converted from model-specific response types --> pure strings. Now I'm going to also support function calls --> OutputData types
Same as last diff (https://github.com/lastmile-ai/aiconfig/pull/610) except now for python files instead of typescript
Don't need to do this for the image outputs since I already did that in https://github.com/lastmile-ai/aiconfig/pull/608
Actually like typescript, the only model parser we need to support for function calling is `openai.py`
> [python] Use OutputDataWithValue type for function calls

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/ParametersRenderer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptName.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_outputs/PromptOutputsRenderer.tsx
- python/src/aiconfig/editor/client/src/shared/types.ts
- python/src/aiconfig/editor/client/src/utils/aiconfigStateUtils.ts
- python/src/aiconfig/editor/client/src/utils/api.ts
- python/src/aiconfig/editor/server/server.py
[editor] Save without Requiring File Path from Client
The client currently doesn't know the file path that its config is saved at, so there's no way for the client to specify the 'path' to save the config at when sending the `save` request.
For now, updating the `save` endpoint to default to saving the config to the path specified in its associated AIConfigRuntime.
As we update the UX we should consider:
- Supporting changing config name/path from the client
- Sending the current path to the client on load
- Made changes to input (which are reflected in the server-side config)
- Click save, and ensure the config contents are saved to the config on disk
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pu …
> [editor] Save without Requiring File Path from Client

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/utils/aiconfigStateUtils.ts
- python/src/aiconfig/editor/client/src/utils/api.ts
[editor] Connect UPDATE_PROMPT_INPUT to update_prompt endpoint
Hook up the `UPDATE_PROMPT_INPUT` action to the server `update_prompt` endpoint, sending requests with a 250ms debounce so that we don't spam the server and avoid potential overlap.
We don't have server-side endpoints for updating specific parts of the prompt right now (not sure if that would be any major improvement), so we currently need to send a Prompt constructed with the updated input as a spread into the current prompt in state. We still maintain the UI state in the reducer instead of passing in this new spread prompt to the reducer from this callback since the reducer should be the source of truth for UI state and will ensure the proper immutable state flow is maintained. We can also add other state values (e.g. …
> [editor] Connect UPDATE_PROMPT_INPUT to update_prompt endpoint

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/ParametersRenderer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/utils/aiconfigStateUtils.ts
- python/src/aiconfig/editor/client/src/utils/api.ts
[editor][easy] Use JSONObject import from 'aiconfig'
Fix import path to import from "aiconfig" instead of "aiconfig/dist/common" and don't redefine JSONObject in parameters renderer
- Load model settings and parameters drawers & set some values without issue
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/643).
* #647
* #644
* __->__ #643
* #642
> [editor][easy] Use JSONObject import from 'aiconfig'

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/ParametersRenderer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptName.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_outputs/PromptOutputsRenderer.tsx
- python/src/aiconfig/editor/client/src/shared/types.ts
- python/src/aiconfig/editor/client/src/utils/aiconfigStateUtils.ts
- python/src/aiconfig/editor/client/src/utils/api.ts
[editor] Prompt Name Component
Implement the Prompt Name component, which is currently just updating state -- need endpoint to be implemented server side before we can call it.
As part of this change, I've update the `ClientAIConfig` type to remove the `renderData` and custom output typing (in preparation for updated AIConfig output types). We still need `ClientAIConfig` and `ClientPrompt` type since our client state needs to have some custom properties. In this case, we need unique ids associated with each prompt so that we can properly render them in a list. Using name would cause the entire prompt container to fully remount every time the name input changes (and that also loses focus on the input). I've updated to use an `_ui` key on prompt for this and using helper methods for …
> [editor] Prompt Name Component

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_generation.py
[ez] Remove fixed TODO comments in HF text_generation local inference model parser
This was fixed in https://github.com/lastmile-ai/aiconfig/pull/410, but forgot to remove the TODO, doing it in this diff
> [ez] Remove fixed TODO comments in HF text_generation local inference model parser

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/editor/server/server_utils.py
Remove declaration of generic T from server.py
Not being used, let's get rid of it dawg!
I also ran the linter based on Jonathan's command from this comment: https://github.com/lastmile-ai/aiconfig/pull/613#discussion_r1437724642
```
fd --glob '*.py'  python/src/aiconfig/editor/server | xargs python -m 'scripts.lint' --mode=fix --files
```
^ (btw you can install fd on Mac using `brew install fd`, looks pretty cool). It actually seems pretty cool https://github.com/sharkdp/fd?tab=readme-ov-file
> Remove declaration of generic T from server.py

- cookbooks/Function-Calling-OpenAI/typescript/function-calling-with-openai.ts
- cookbooks/HuggingFace/typescript/hf.ts
- extensions/HuggingFace/typescript/hf.ts
- extensions/llama/typescript/llama.ts
- typescript/__tests__/config.test.ts
- typescript/__tests__/parsers/hf/hf.test.ts
- typescript/__tests__/parsers/palm-text/palm.test.ts
- typescript/demo/demo.ts
- typescript/demo/function-call-stream.ts
- typescript/demo/test-hf.ts
- typescript/lib/config.ts
- typescript/lib/modelParser.ts
- typescript/lib/parsers/hf.ts
- typescript/lib/parsers/openai.ts
- typescript/lib/parsers/palm.ts
[ts] Change `serialize` output from `Prompt | Prompt[]` to `Prompt[]`
TSIA, already did this for Python in https://github.com/lastmile-ai/aiconfig/pull/632, just doing for ts now too
Run the typescript demos to make sure that they continue to work. Run these commands in terminal from the `aiconfig` top-level dir
```bash
export OPENAI_API_KEY=sk-XYZ #set your API key, which you can get from https://platform.openai.com/api-keys
npx ts-node typescript/demo/function-call-stream.ts
npx ts-node typescript/demo/demo.ts
npx ts-node typescript/demo/test-hf.ts
```
^Make sure delete any generated files so we don't include them in your GH push requests
Now enter into the `aiconfig/typescript` dir and run these commands to make sure tests pass and yarn compiles:
```bash
yarn test
yarn build
rm -rf …
```
> [ts] Change `serialize` output from `Prompt | Prompt[]` to `Prompt[]`

- python/src/aiconfig/editor/server/server.py
[AIC-py][Bug fix][editor] simplify and add missing await to run endpoint
Currently we're not awaiting `run()`. This awaits the run method call.
Also, I'm taking the opportunity to simplify the code by removing some abstractions.
Later if we simplify more and end up with repetition we can refactor again
to dedup.
Test:
```
url = "http://localhost:8080/api/run"
for data in [
{},
{    "prompt_name": "get_activities"},
{
"prompt_name": "get_activities",
"params": {
"city": "karachi"
}
}
]:
print(f"\n\n{url=}, {data=}")
response = requests.post(url, json=data)
print(f"\n{response=}"),
import json
response_json = json.loads(response.text)
print(f"{response_json=}")
print(f"{response_json['message']=}")
aic = response_json.get('aiconfig', {})
print("AIC:", aic) …
```
> [AIC-py][Bug fix][editor] simplify and add missing await to run endpoint

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/components/prompt/AddPromptButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/ModelSelector.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptMenuButton.tsx
- python/src/aiconfig/editor/client/src/hooks/useLoadModels.ts
- python/src/aiconfig/editor/client/src/utils/aiconfigStateUtils.ts
- python/src/aiconfig/editor/client/src/utils/api.ts
[editor] Support Deleting Prompt
Add the UI side for deleting a prompt, with placeholder to call the server endpoint once it's implemented
https://github.com/lastmile-ai/aiconfig/assets/5060851/b3e682dd-a3ed-45c1-b153-b4b6e2094616
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/665).
* #667
* #666
* __->__ #665
* #662
> [editor] Support Deleting Prompt

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/components/prompt/AddPromptButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/ModelSelector.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/hooks/useLoadModels.ts
- python/src/aiconfig/editor/client/src/utils/api.ts
[editor] Model Selector
Implement the model selector and add a placeholder call to the future api endpoint for updating the model.
https://github.com/lastmile-ai/aiconfig/assets/5060851/812f3a10-aaac-4ec3-9f1f-4d21ebc99e9f
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/662).
* #667
* #666
* #665
* __->__ #662
> [editor] Model Selector

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/components/prompt/AddPromptButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/ModelSelector.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptActionBar.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptMenuButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/RunPromptButton.tsx
- python/src/aiconfig/editor/client/src/hooks/useLoadModels.ts
- python/src/aiconfig/editor/client/src/shared/types.ts
- python/src/aiconfig/editor/client/src/utils/aiconfigStateUtils.ts
- python/src/aiconfig/editor/client/src/utils/api.ts
[editor] Run Prompt (non-streaming)
With non-streaming /run endpoint properly returning the response now, we can update the client config with the resulting output. We can also leverage the client-side `_ui` state for maintaining 'isRunning' state to show a spinner / disable the execute button for now (TODO: we may need to handle canceling execution as well).
https://github.com/lastmile-ai/aiconfig/assets/5060851/67fa793a-9a60-4285-a7d1-69fff633d6a6
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/667).
* __->__ #667
* #666
* #665
* #662
> [editor] Run Prompt (non-streaming)

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/components/prompt/AddPromptButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/ModelSelector.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptMenuButton.tsx
- python/src/aiconfig/editor/client/src/hooks/useLoadModels.ts
- python/src/aiconfig/editor/client/src/utils/aiconfigStateUtils.ts
- python/src/aiconfig/editor/client/src/utils/api.ts
[editor] Use Prompt ID Instead of Index for Client-side State Actions
We can uniquely identify prompts in client-side state using their client-side id, so let's use that instead of index for referencing them in the actions. This should be a bit more robust than using index.
Went through all relevant actions and made sure they work as expected
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/666).
* #667
* __->__ #666
* #665
* #662
> [editor] Use Prompt ID Instead of Index for Client-side State Actions

- extensions/Gemini/python/src/aiconfig_extension_gemini/Gemini.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_generation.py
- extensions/HuggingFace/typescript/hf.ts
- python/src/aiconfig/default_parsers/hf.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/default_parsers/palm.py
- python/tests/parsers/test_openai_util.py
- typescript/__tests__/parsers/hf/hf.test.ts
- typescript/lib/parsers/hf.ts
- typescript/lib/parsers/openai.ts
- typescript/lib/parsers/palm.ts
Just updating the `rawResponse` property name to `raw_response` for snake_case consistency in the schema. All other changes here are just auto-formatted
`pytest`
```
=========================================================== 88 passed, 38 warnings in 3.28s ===========================================================
```
`yarn test`
```
(aiconfig) ryanholinshead@Ryans-MBP typescript % yarn test 
$ jest --runInBand
PASS  __tests__/parsers/hf/hf.test.ts
HuggingFaceTextGeneration ModelParser
✓ uses HuggingFace API token from environment variable if it exists (9 ms)
✓ serializing params to config prompt (1 ms)
✓ serialize callbacks (1 ms)
✓ deserializing config prompt to params (1 ms)
✓ deserialize callbacks (1 ms)
✓ run prompt, non-streaming (4 ms)
✓ run prompt, streaming (2 …
```
> rawResponse -> raw_response for snake_case consistency

- python/src/aiconfig/editor/README.md
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/GlobalParametersContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/components/prompt/model_settings/ModelSettingsSchemaRenderer.tsx
[1/n] Global parameters renderer
Use ParametersRenderer to modify global parameters.
Currently still updating the entire parameters object. Next up, will fix the ParametersRenderer component to update each parameter separately.
> [1/n] Global parameters renderer

- python/src/aiconfig/editor/client/src/components/AIConfigContext.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptName.tsx
[editor] Prevent Setting Duplicate Names
Many of the AIConfig API methods rely on specifying the prompt name. We should be careful not to allow duplicate prompt names in the editor to prevent any issues, so add an error in the UI if the prompt name matches an existing prompt name:
https://github.com/lastmile-ai/aiconfig/assets/5060851/8bb4a659-755e-44cf-93f8-b00d27070cf0
> [editor] Prevent Setting Duplicate Names

- python/src/aiconfig/editor/client/src/components/GlobalParametersContainer.tsx
- python/src/aiconfig/editor/client/src/components/ParametersRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptActionBar.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
[easy] Simplify update parameters callback
Have updateParameters take a JSONObject. Makes it much cleaner to use elsewhere.
ParametersRenderer simply converts its ParametersArray to JSONObject before triggering the update.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/674).
* __->__ #674
* #673
> [easy] Simplify update parameters callback

- python/src/aiconfig/editor/server/server_utils.py
- python/src/aiconfig/registry.py
[editor] Initialize Empty Config with a First Prompt
Currently, starting the editor without specifying a file path will result in an empty editor UI without any prompts.
This PR updates it to start the config with a prompt whose model is the first supported model in the registry.
> [editor] Initialize Empty Config with a First Prompt

- python/src/aiconfig/schema.py
- python/src/aiconfig/util/params.py
- python/tests/test_parameter_api.py
- python/tests/test_programmatically_create_an_AIConfig.py
[python] Created `get_parameters` API
**Disclaimer:** I know this is 400+ lines changed, but ~300 of those are just adding/refactoring automated tests!!!
We already had `get_prompt_parameters`, but this isn't good enough if parameters aren't defined locally and we want to bubble up to the aiconfig defaults. See comment in https://github.com/lastmile-ai/aiconfig/pull/661#discussion_r1437941729.
This is important so that we can ensure we have valid params if not defined in the correct section of our AIConfig schema. This is similar in theme to https://github.com/lastmile-ai/aiconfig/pull/600
The only callsite we have today for this is in python in the `params.py` function, so I updated that callsite too. I don't know why it doesn't exist in Typescript (cc @rholinshead) but I also added this …
> [python] Created `get_parameters` API

- python/src/aiconfig/schema.py
- python/src/aiconfig/util/params.py
- python/tests/test_parameter_api.py
- python/tests/test_programmatically_create_an_AIConfig.py
[python] Updated `set_parameter()` to work if parameters haven't been defined before
Before this function would have failed to set any parameters if:
1. The prompt_name was passed in but `prompt.metadata` (possible) or `prompt.metadata.parameters` (not possible because it defaults to `{}`) was `None`
2. The prompt_name was not passed in (so update aiconfig) but the `aiconfig.metadata.parameters` was `None` (this is actually never possible because we default to using `{}`, but still just good to be thorough and future-proof)
See example below
Added automated tests: `pytest -vv`
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/670).
* #693
* #692
* #691
* #690
* #688
* __->__ #670
* #668
> [python] Updated `set_parameter()` to work if parameters haven't been defined before

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/editor/server/server_utils.py
- python/src/aiconfig/schema.py
- python/src/aiconfig/util/params.py
- python/tests/test_parameter_api.py
- python/tests/test_programmatically_create_an_AIConfig.py
Create set_parameter endpoint
TSIA, this relies on https://github.com/lastmile-ai/aiconfig/pull/670 being unblocked
```
curl http://localhost:8080/api/set_parameter -d '{"prompt_name":"get_activities", "parameter_name": "city", "parameter_value": "New York"}' -X POST -H 'Content-Type: application/json'
```
Notice that the parameters are now set. We already have automated testing from https://github.com/lastmile-ai/aiconfig/pull/670 so we know the functionality works as long as this is connected to the client (pretty great!)
https://github.com/lastmile-ai/aiconfig/assets/151060367/1be05d7e-63fe-4d6d-9036-6f8d4d004134
--- …
> Create set_parameter endpoint

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/editor/server/server_utils.py
- python/src/aiconfig/schema.py
- python/src/aiconfig/util/params.py
- python/tests/test_parameter_api.py
- python/tests/test_programmatically_create_an_AIConfig.py
Create set_name endpoint
TSIA
```
curl http://localhost:8080/api/set_name -d '{"name":"cool_new_name"}' -X POST -H 'Content-Type: application/json'
```
https://github.com/lastmile-ai/aiconfig/assets/151060367/efcb7ceb-e390-4208-93b3-3effd5d66f8b
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/692).
* #693
* __->__ #692
* #691
* #690
* #688
* #670
* #668
> Create set_name endpoint

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/ConfigNameDescription.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputDataSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/utils/api.ts
- python/src/aiconfig/editor/client/src/utils/constants.ts
[editor] Support adding prompt at the top of the config
Add the 'AddPromptButton' at index 0 to support adding a prompt at the top of the config:
https://github.com/lastmile-ai/aiconfig/assets/5060851/76a28aa6-20ce-44e7-bbce-1714b5865a2c
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/682).
* #686
* __->__ #682
* #681
* #680
> [editor] Support adding prompt at the top of the config

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/ConfigNameDescription.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/utils/api.ts
- python/src/aiconfig/editor/client/src/utils/constants.ts
[editor] Config Name & Description UI
[editor] Config Name & Description UI
Add the UI for changing config name / description, similar to workbook title UI:
https://github.com/lastmile-ai/aiconfig/assets/5060851/f0f49638-d0c5-4d88-8edd-c0bbb0294f7c
If config name is not set, keep the name / description in Edit state until the name is set
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/680).
* #686
* #682
* #681
* __->__ #680
> [editor] Config Name & Description UI

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/ConfigNameDescription.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputDataSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/utils/api.ts
- python/src/aiconfig/editor/client/src/utils/constants.ts
[editor] Add placeholder to empty text prompt input
Note the figma has the text "Type a prompt. (e.g. show me an astronaut riding a horse on the moon)", however that could be confusing for any model that doesn't have an image output. So, let's just use 'Type a prompt' for now
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/681).
* #686
* #682
* __->__ #681
* #680
> [editor] Add placeholder to empty text prompt input

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/schema.py
Create set_parameters endpoint
Created a new method in SDK called `set_parameters` that iterates through a hash table and calls `set_parameter` on each parameter key-value pair
```
curl http://localhost:8080/api/set_parameters -d '{"prompt_name":"get_activities", "parameters": {"city":"New York", "sort_by":"geographical_location"}}' -X POST -H 'Content-Type: application/json'
```
https://github.com/lastmile-ai/aiconfig/assets/151060367/979f1e5c-437b-4a33-80cc-cb6fcda13c02
> Create set_parameters endpoint

- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
Copy over all the default models to the temporary mapping of models to prompt schemas and apply the existing `OpenAIChatModelParserPromptSchema` to all models supported by the `OpenAIChatModelParser`. Subsequent PRs should implement the prompt schemas for the remaining parsers and uncomment the models to add the mapping.
Fast-following after MVP:
- define these schemas in python as static reference on the relevant model parser classes
- implement an endpoint get_prompt_schemas for the client to call and get a list of static prompt schemas (to be JSON parsed into objects on the client) and the mapping of model->schema to use for referencing
- Create a new prompt with gpt-4-0613 and ensure correct settings UI
- Toggle to some other gpt chat variants and ensure correct settings UI
> [editor] Starting Point for Remaining Prompt Schemas

- python/src/aiconfig/editor/client/package.json
- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/ConfigNameDescription.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/JSONEditor.tsx
- python/src/aiconfig/editor/client/src/components/JSONRenderer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputJSONRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputDataSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_outputs/JSONOutput.tsx
- python/src/aiconfig/editor/client/src/utils/api.ts
- python/src/aiconfig/editor/client/src/utils/constants.ts
- python/src/aiconfig/editor/client/yarn.lock
[editor] JSON Renderer for Prompt Input
Add a toggle-able JSON editor for prompt inputs so that users can see/modify the input JSON directly. This sets up the JSONEditor component which can be reused in other places (e.g. prompt model settings). This component takes in a schema object to provide validation of the input -- we should investigate and update the implementation to just take a reference to a definition in our config schema instead of needing to duplicate the schema definition for PromptInput but I wasn't able to get that working within a reasonable time box.
https://github.com/lastmile-ai/aiconfig/assets/5060851/c5e14ac0-0771-41f5-adea-4369b886ef00
--- …
> [editor] JSON Renderer for Prompt Input

- python/src/aiconfig/editor/server/server.py
[editor][server endpoints][2/n]: Add params arg to run command and check for undefined prompt_name
TSIA, pretty simple otherwise we'd be using empty params field and that would error. For the future, I created issue https://github.com/lastmile-ai/aiconfig/issues/671 where we shouldn't even need to pass in params into run and this works implicitly
```
curl http://localhost:8080/api/run -d '{"prompt_name":"get_activities"}' -X POST -H 'Content-Type: application/json'
```
Without params
https://github.com/lastmile-ai/aiconfig/assets/151060367/7233a4db-9042-4fa9-affb-0f854ae8a50e
With params …
> [editor][server endpoints][2/n]: Add params arg to run command and check for undefined prompt_name

- python/src/aiconfig/editor/client/src/components/prompt/PromptActionBar.tsx
[editor] Set isRunning on RunPromptButton in Settings Drawer
Previously, the RunPromptButton within the expanded action bar was clickable when running the prompt, so just pass the isRunning prop to fix:
https://github.com/lastmile-ai/aiconfig/assets/5060851/408ac180-d3ef-4fe7-bd10-b476081a11a0
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/709).
* #710
* __->__ #709
> [editor] Set isRunning on RunPromptButton in Settings Drawer

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/utils/api.ts
- python/src/aiconfig/schema.py
[editor] Persist Setting Params
[editor] Persist Setting Params
Update the set_parameters implementation to clear existing parameters before setting the new ones (otherwise, we end up with a ton of duplicates). Then, connect the parameters callbacks to the endpoint.
- Set and update global and prompt-level parameters, reload to ensure persisted values server-side:
https://github.com/lastmile-ai/aiconfig/assets/5060851/19b061a3-1cff-4e66-a2fb-43bfe662fd5b
> [editor] Persist Setting Params

- python/src/aiconfig/editor/client/src/components/SettingsPropertyRenderer.tsx
It's confusing to have the 'No settings available' text when there's no renderer available for the type. Instead, just skip renderer for the property for now. We'll add a JSON editor toggle to the settings drawer to allow editing any settings, though it won't benefit from a schema since the prompt schema is not direct 1:1 with JSON schema.
> [editor][easy] Remove Confusing 'No Settings Available' Text for Missing Settings Property Renderer

- python/src/aiconfig/schema.py
- python/tests/test_programmatically_create_an_AIConfig.py
Summary:
This pull request addresses a critical flaw in the add_output method within the Python SDK. Currently, the method incorrectly adds None to the output list when the Output parameter is None, which contradicts the intended behavior. The expected functionality is for the method to reject None as an invalid output or, alternatively, raise an exception.
Changes Made:
- Modified the add_output method to raise an exception when the Output parameter is None.
Context:
This change ensures that the add_output method behaves as expected, providing more robust and predictable behavior when handling output parameters.
Related Issues:
Closes #529 
Test Plan:
New test similar to `test_add_output_existing_prompt_no_overwrite` but with overwrite needs to be added.
Things left to complete:
> Add error handling for `add_ouput` in Python SDK

- python/src/aiconfig/schema.py
- python/tests/test_programmatically_create_an_AIConfig.py
Summary:
This pull request adds ability to add multiple outputs to prompt for Python SDK.
Changes Made:
Added the add_outputs method to add multiple outputs to a prompt.
Related Issues:
Closes #153
Test Plan:
> Feat: Add method to add multiple outputs to a prompt in AIConfig

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/DalleImageGenerationParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
[editor] Add DalleImageGenerationParserPromptSchema
Add the prompt schema for dall-e-2 to match `/opt/homebrew/Caskroom/miniconda/base/envs/aiconfig/lib/python3.12/site-packages/openai/resources/images.py`:
```
def generate(
self,
*,
prompt: str,
model: Union[str, Literal["dall-e-2", "dall-e-3"], None] | NotGiven = NOT_GIVEN,
n: Optional[int] | NotGiven = NOT_GIVEN,
quality: Literal["standard", "hd"] | NotGiven = NOT_GIVEN,
response_format: Optional[Literal["url", "b64_json"]] | NotGiven = NOT_GIVEN,
size: Optional[Literal["256x256", "512x512", "1024x1024", "1792x1024", "1024x1792"]] | NotGiven = NOT_GIVEN,
style: Optional[Literal["vivid", "natural"]] | NotGiven = NOT_GIVEN,
user: str | NotGiven = NOT_GIVEN,
extra_headers: Headers | None = None,
extra_query: Query | None = None, …
```
> [editor] Add DalleImageGenerationParserPromptSchema

- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/utils/constants.ts
[editor] Fix Error Message Handling
Just update the error type to not rely on being an instance of `Error`, and just to use the {message?: string} type
- Intentionally raise error in /save `return HttpResponseWithAIConfig(message="ERROR", code=500, aiconfig=None).to_flask_format()` then attempt to save & see correct error notification
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/716).
* __->__ #716
* #715
* #710
> [editor] Fix Error Message Handling

- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/utils/constants.ts
[editor] Connect Prompt Name to /update_prompt
Connect the onChangePromptName callback to the server with /update_prompt request. Note the special handling here:
Since most AIConfig API methods depend on unique prompt names, we can't update the prompt name in the config on every change (or else we could end up using a not-yet-existing prompt name for other actions). Instead, we maintain the prompt name input in the client side prompt name component state and then update the client AIConfig state after the response has returned successfully.
Note: Realized as part of this that the debounce value returns the prev debounce result, so we actually need to handle the async response dispatch event with a callback to the debounce function.
Make sure updating prompt name works now …
> [editor] Connect Prompt Name to /update_prompt

- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/utils/constants.ts
[editor] Handle Run Prompt Errors
When running a prompt results in an error, update the running state to false to ensure it doesn't get stuck in endless 'running' state.
Also, fix handling of the error notification:
- Missing <Notification/> component in the app
- Miss-handling caught object type (somehow not instance of error, just a {message: ".."} object)
- See run prompt error for dall-e-2, stops the running state and shows a notification with the message
https://github.com/lastmile-ai/aiconfig/assets/5060851/d156a774-9c6c-412a-9e6c-645c269065ca
As a follow-up, we should render a nicer error output as part of the prompt output to be persisted in the UI (until rerun or reload)
--- …
> [editor] Handle Run Prompt Errors

- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
Was incorrectly indexing .aiconfig from the resulting aiconfig (which types fine since AIConfig is completely open)
> [editor][hotfix] Fix Debounced Update Prompt Callback

- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
`debounced` callbacks won't propagate thrown errors so we should use an `onError` callback to handle those. This PR handles them for updating config name and description.
- Update /set_name endpoint to return error:
```
return HttpResponseWithAIConfig(
#
message=f"Failed to set name (TEST)",
code=500,
aiconfig=None,
).to_flask_format()
```
- Update /set_description endpoint to return error:
```
return HttpResponseWithAIConfig(
#
message=f"Failed to set description (TEST)",
code=500,
aiconfig=None,
).to_flask_format()
```
See notifications:
https://github.com/lastmile-ai/aiconfig/assets/5060851/b1299566-ad16-4d8a-ad91-702d0b163393
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/728).
* __->__ #728 …
> [editor] Debounced Error Handling for Config Name and Description

- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
[editor] Debounced Error Handling for Prompt and Global Parameters
`debounced` callbacks won't propagate thrown errors so we should use an `onError` callback to handle those. This PR handles them for updating prompt and global parameters.
Added the following in /set_parameters endpoint to return an error:
```
return HttpResponseWithAIConfig(
#
message=f"Failed to set parameters (TEST)",
code=500,
aiconfig=None,
).to_flask_format()
```
See notifications:
https://github.com/lastmile-ai/aiconfig/assets/5060851/89ec3c82-a9cf-423f-81c7-9c419763a128
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/726).
* #728
* #727
* __->__ #726
* #725
> [editor] Debounced Error Handling for Prompt and Global Parameters

- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
[editor][easy] Fix Prompt Name Error Message
Missed on place for retrieving the message from the caught error (not an instanceof Error), so fix it.
Tested by returning an error response in update_prompt:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/727).
* #728
* __->__ #727
* #726
* #725
> [editor][easy] Fix Prompt Name Error Message

- python/src/aiconfig/editor/travel.aiconfig.json
This prompt was just being used for getting the PromptSchema rendering figured out and is no longer needed since we don't actually support gpt4-v as a default model yet. It just added confusion due to errors when running
> [editor][easy] Remove gpt4-v example prompt

- python/src/aiconfig/editor/client/src/components/AIConfigContext.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/shared/types.ts
- python/src/aiconfig/editor/client/src/utils/constants.ts
- python/src/aiconfig/editor/travel.aiconfig.json
A common action when using an editor UI is to hit CMD+s or CTRL+s to save. In browsers, this will by default open up the browser save window to save the web page itself. In this PR, we override this default behaviour and instead call the /save endpoint for the config if it's dirty
https://github.com/lastmile-ai/aiconfig/assets/5060851/a2bf656b-2209-49e0-a404-31b23b836abd
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/735).
* __->__ #735
* #734
* #733
> [editor] Handle CMD/CTRL + S to Save

- python/src/aiconfig/editor/client/src/components/AIConfigContext.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/shared/types.ts
[editor] Add 'dirty' Config State
Update the client-side config _ui state to maintain `isDirty` state, which is set to true whenever a client-side config mutation happens and then set to false whenever a successful config save happens. Use this value to disable the button and show appropriate tooltip
https://github.com/lastmile-ai/aiconfig/assets/5060851/dfcb57bd-282d-4622-bd10-ec4a281c213c
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/733).
* #735
* #734
* __->__ #733
> [editor] Add 'dirty' Config State

- python/src/aiconfig/editor/client/src/components/AIConfigContext.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/shared/types.ts
- python/src/aiconfig/editor/client/src/utils/constants.ts
[editor] Autosave at 15s Interval
Set up an interval to autosave the config every 15s from the client. Note that the interval is technically cleared & recreated each time the `isDirty` state changes, but that's fine because this will also handle the case where changes are made right when a successful save response comes back, or if a save fails (doesn't clear dirty state) another attempt will be made automatically after 15s.
https://github.com/lastmile-ai/aiconfig/assets/5060851/dfcb57bd-282d-4622-bd10-ec4a281c213c
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/734).
* #735
* __->__ #734
* #733
> [editor] Autosave at 15s Interval

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/PaLMTextParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
Add the prompt schema for PaLM text models (text-bison). Note that our PaLMTextParser implementation is currently not using fully valid completion params (created https://github.com/lastmile-ai/aiconfig/issues/736 for that), so just selected the valid ones in accordance with https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/text
> [editor] PaLMTextParserPromptSchema

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_2_image.py
- python/src/aiconfig/default_parsers/dalle.py
- python/src/aiconfig/default_parsers/hf.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/default_parsers/palm.py
- python/src/aiconfig/default_parsers/parameterized_model_parser.py
Fix image model parsers issue for output type not being correct
I made this mistake when editing the outputs in image output format (initially in https://github.com/lastmile-ai/aiconfig/pull/608, but actual mistake came in https://github.com/lastmile-ai/aiconfig/pull/637). It's becuase I set this as Output TYPE (`OutputDataWithValue`), not Output CLASS (`OutputDataWithStringValue`)
This highlights the need for:
1. Better automated tests. We currently have `load()` and `serialize()`, but not for run: https://github.com/lastmile-ai/aiconfig/pull/294 . I thought this was pretty simple change so didn't manually test
Follow dev README to setup the local editor: https://github.com/lastmile-ai/aiconfig/tree/main/python/src/aiconfig/editor#dev, then run this command (or just do it manually with …
> Fix image model parsers issue for output type not being correct

- python/src/aiconfig/editor/client/src/components/prompt/AddPromptButton.tsx
Custom model support is a fast-follow post-MVP so remove the button that will eventually show the info modal for adding custom model parsers
> [editor] Temporarily Remove 'Add New Model' Option in AddPromptButton

- python/pyproject.toml
- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/editor/server/server_utils.py
- python/src/aiconfig/scripts/aiconfig_cli.py
[AIC-py][editor] test+prod CLI packaging
This bundles a few simple changes to make CLI installation and usage easier.
The main thing is adding the aiconfig script to the build config, which is tested
using a test pypi package.
- test publish script
- add script to build file that runs cli main
- had to refactor main slightly to enable this
- open in browser on server start
- only reload server in debug mode
- default prod server mode so you dont have to give it at cli
I built python-aiconfig-test 1.1.22. Install:
`pip3 install --index-url https://test.pypi.org/simple --extra-index-url https://pypi.org/simple python-aiconfig-test==1.1.22 --force`
Run:
`aiconfig edit`
Editor opens in browser
> [AIC-py][editor] test+prod CLI packaging

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextGenerationParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/OpenAIChatModelParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/PaLMChatParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
Previously, the model search was doing exact match, including capitalization. So, searching 'hu' would not show the "HuggingFaceTextGenerationParser".
Fix by making both search and model names lowercase when filtering:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/756).
* __->__ #756
* #755
* #754
> [editor] Fix Model Search to Ignore Casing

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/OpenAIChatModelParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/PaLMChatParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
[editor] PaLMChatParserPromptSchema
Implement the Prompt Schema for PaLM Chat, using the supported params with defaults from https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/text-chat, selecting those that are defined in the `refine_chat_completion_params` of palm.py:
```
def refine_chat_completion_params(model_settings):
supported_keys = {
"candidate_count",
"examples",
"model",
"temperature",
"top_k",
"top_p",
"context",
}
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/754).
* #756
* #755
* __->__ #754
> [editor] PaLMChatParserPromptSchema

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextGenerationParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/OpenAIChatModelParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/PaLMChatParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
[editor] HuggingFaceTextGenerationParserPromptSchema
Adding the PromptSchema for HuggingFaceTextGenerationParser, with supported properties from `refine_chat_completion_params` in the parser implementation. Types obtained from https://github.com/huggingface/huggingface_hub/blob/a331e82aad1bc63038194611236db28fa013814c/src/huggingface_hub/inference/_client.py#L1206 and defaults obtained from https://huggingface.co/docs/api-inference/detailed_parameters if they're listed
Note, this is for the default/core parser which uses inference API. We'll need to add the other prompt schemas for the extension models for gradio.
Will update the hf prompt UX to support actual 'model' in a subsequent diff
--- …
> [editor] HuggingFaceTextGenerationParserPromptSchema

- cookbooks/Anyscale/Function_Calling_with_Mixtral.ipynb
- cookbooks/Anyscale/README.md
- cookbooks/Anyscale/getting_started.ipynb
- cookbooks/Anyscale/recommender.aiconfig.json
- cookbooks/Anyscale/travel.aiconfig.json
- cookbooks/Anyscale/travel.aiconfig.yaml
- cookbooks/Anyscale/updated.aiconfig.json
- cookbooks/Function-Calling-OpenAI/README.md
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/anyscale_endpoint.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/schema.py
- typescript/lib/config.ts
- typescript/lib/parsers/anyscale.ts
- typescript/lib/parsers/openai.ts
[bug] Ensure that Output is constructed consistently across streaming and non-streaming
Currently the openai modelparser calls `build_output_data` to properly construct the response from the inference endpoint into an AIConfig OutputData type.
However, it only does this when stream = False. This change adds the same logic to stream = True (and also ensures that the metadata is set consistently and in a loss-less way.
Also updated the same logic for Anyscale Endpoint model parser.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/752).
* __->__ #752
* #748
* #746
* #745
* #743
* #730
> [bug] Ensure that Output is constructed consistently across streaming and non-streaming

- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/anyscale_endpoint.py
Create AnyScale Endpoint modelparser
Simply extend the OpenAIInference modelparser and change the api key and base_url to point to anyscale.
Added utility classes for all the supported models for Anyscale Endpoints: https://docs.endpoints.anyscale.com/category/supported-models
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/730).
* #752
* #748
* #746
* #745
* #743
* __->__ #730
> Create AnyScale Endpoint modelparser

- cookbooks/Anyscale/README.md
- cookbooks/Anyscale/getting_started.ipynb
- cookbooks/Anyscale/travel.aiconfig.json
- cookbooks/Anyscale/travel.aiconfig.yaml
- cookbooks/Function-Calling-OpenAI/README.md
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/anyscale_endpoint.py
- typescript/lib/config.ts
- typescript/lib/parsers/anyscale.ts
- typescript/lib/parsers/openai.ts
[Cookbook] Add Anyscale Endpoint cookbook
Clone the Getting Started cookbook and adapt it for Anyscale.
Next up we will also add a cookbook for function calling using Anyscale.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/746).
* #752
* #748
* __->__ #746
* #745
* #743
* #730
> [Cookbook] Add Anyscale Endpoint cookbook

- cookbooks/Anyscale/Function_Calling_with_Mixtral.ipynb
- cookbooks/Anyscale/README.md
- cookbooks/Anyscale/getting_started.ipynb
- cookbooks/Anyscale/recommender.aiconfig.json
- cookbooks/Anyscale/travel.aiconfig.json
- cookbooks/Anyscale/travel.aiconfig.yaml
- cookbooks/Anyscale/updated.aiconfig.json
- cookbooks/Function-Calling-OpenAI/README.md
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/anyscale_endpoint.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/schema.py
- typescript/lib/config.ts
- typescript/lib/parsers/anyscale.ts
- typescript/lib/parsers/openai.ts
[Cookbook] Simple Function calling example with Mixtral-8x7B
Along with some fixes to function calling using OpenAI and Anyscale modelparsers
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/748).
* #752
* __->__ #748
* #746
* #745
* #743
* #730
> [Cookbook] Simple Function calling example with Mixtral-8x7B

- python/src/aiconfig/editor/server/server_utils.py
[bug fix][AIC-py] add missing global model settings on init
Adding prompt with a model name to a new AIConfig makes it invalid
because essentially the name is a dangling foreign key to the AIConfig's global
model settings mapping.
Immediate fix:
When we add prompt_1, also add a default global mapping entry for each
registered model.
Better fix: Reject updates to AIConfig that would make it invalid.
(inside add_prompt). However, this could break existing code
that adds a prompt and then immediately adds the missing model, like we're doing
in this PR.
In the future, we should make AIConfig more constrained by definition
so that this kind of invalid object can't exist to begin with.
Test: run server, type into prompt_1, it runs
> [bug fix][AIC-py] add missing global model settings on init

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/__init__.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_summarization.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_translation.py
[AIC-py] hf mt model parser
text translation sans streaming. Streaming is not trivial here
Test:
```
import asyncio
from aiconfig_extension_hugging_face.local_inference.text_translation import HuggingFaceTextTranslationTransformer
from aiconfig import AIConfigRuntime, InferenceOptions, CallbackManager
mp = HuggingFaceTextTranslationTransformer()
AIConfigRuntime.register_model_parser(mp, "translation_en_to_fr")
config = AIConfigRuntime.load("/Users/jonathan/Projects/aiconfig/test_hf_transl.aiconfig.json")
config.callback_manager = CallbackManager([])
def print_stream(data, _accumulated_data, _index):
print(data, end="", flush=True)
async def run():
print("no stream")
options = InferenceOptions(stream=False)
out = await config.run("test_hf_trans", options=options)
print("Output:\n", out) …
```
> [AIC-py] hf machine translation (text to text) model parser

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/__init__.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_summarization.py
[RFC][AIC-py] hf summarization model parser
Very similar to text gen
Test:
```
...
{
"name": "test_hf_sum",
"input": "HMS Duncan was a D-class destroyer ...", # [contents of https://en.wikipedia.org/wiki/HMS_Duncan_(D99)]
"metadata": {
"model": {
"name": "stevhliu/my_awesome_billsum_model",
"settings": {
"min_length": 100,
"max_length": 200,
"num_beams": 1
}
}
}
},
...
}
```
```
import asyncio
from aiconfig_extension_hugging_face.local_inference.text_summarization import HuggingFaceTextSummarizationTransformer
from aiconfig import AIConfigRuntime, InferenceOptions, CallbackManager
mp = HuggingFaceTextSummarizationTransformer()
AIConfigRuntime.register_model_parser(mp, "stevhliu/my_awesome_billsum_model")
config = AIConfigRuntime.load("/Users/jonathan/Projects/aiconfig/cookbooks/Getting-Sta …
```
> [RFC][AIC-py] hf summarization model parser

- python/src/aiconfig/Config.py
- python/tests/aiconfigs/GPT4 Coding Assistant_aiconfig.json
The default model parser registry was registering GPT-4 with capitals and was only used in this example config used for testing. Let's just fix that config to use "gpt-4" (lowercase) and remove the duplicate/confusing capitalized model.
`pytest`
```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================================================== 103 passed, 38 warnings in 1.59s =======================================================================================
```
> [aiconfig] Remove Duplicate GPT-4 Model from Default Registry

- python/src/aiconfig/editor/client/src/components/prompt/AddPromptButton.tsx
Quick UI fixes from bug bash:
- Add 'Add prompt' label to button:
- Limit menu height with scroll area:
https://github.com/lastmile-ai/aiconfig/assets/5060851/4d8a126f-06fc-4e01-a2be-6e1a3e5499b6
> [editor] AddPromptButton UI Update

- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
Noticed in bug bash for the example aiconfig file, modifying the model settings for the first prompt fails.
The error was thrown if setting the model settings when the prompt has no model set; when this happens we need to set the model name to the default model in the config and then we can set the remaining settings.
```
aiconfig edit --aiconfig-path=python/src/aiconfig/editor/travel.aiconfig.json --server-mode='debug_servers'
```
Edit settings for the first prompt and make sure it succeeds and sets correct config data:
```
"name": "get_activities",
"input": "Tell me 10 fun attractions to do in NYC.",
"metadata": {
"model": {
"name": "gpt-3.5-turbo",
"settings": {
"system_prompt": "test"
}
},
"parameters": {}
},
```
> [editor] Fix Prompt Model Name Check

- python/src/aiconfig/editor/client/src/components/JSONEditor.tsx
- python/src/aiconfig/editor/client/src/components/prompt/model_settings/ModelSettingsRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_outputs/JSONOutput.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_outputs/PromptOutputWrapper.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_outputs/PromptOutputsRenderer.tsx
Set up the JSON Editor for model settings, allowing toggling between the schema-backed UI if the schema is available or defaulting to the JSON editor if no schema is available.
https://github.com/lastmile-ai/aiconfig/assets/5060851/98503fa0-4a37-43db-9cb4-b0856665aeeb
> [editor] JSON Renderer for Model Settings

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/CopyButton.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_outputs/PromptOutputWrapper.tsx
- python/src/aiconfig/editor/client/src/utils/api.ts
- python/src/aiconfig/editor/client/src/utils/constants.ts
- python/src/aiconfig/editor/server/server.py
[editor] Server Status Heartbeat
Implement a `server_status` endpoint to use as a heartbeat for the client to know if the server is down; if the request fails, we'll show an error banner at the top of the config to warn the user that the server's in a bad state & some remediation steps (copy important work & restart editor)
QUESTION: Once the server status is marked as error, do we want to keep the heartbeat going (is it possible for the server to recover without user manually restarting it?)
- Load editor, ensure good status and no banner shown
- CMD+C in CLI to shut down the editor. Make sure client shows the error banner
- Start editor again. Client reloads and shows no error
> [editor] Server Status Heartbeat

- cookbooks/Basic-Prompt-Routing/assistant_app.py
- cookbooks/Cli-Mate/cli-mate.py
- cookbooks/HuggingFace/hf.py
- cookbooks/HuggingFace/python/hf.py
- cookbooks/Wizard-GPT/wizard-gpt.py
- python/src/aiconfig/ChatCompletion.py
- python/src/aiconfig/Config.py
- python/src/aiconfig/callback.py
- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/model_parser.py
- python/src/aiconfig/scripts/aiconfig_cli.py
- python/src/aiconfig/scripts/run_aiconfig.py
- python/src/aiconfig/util/params.py
- python/tests/mocks.py
- python/tests/parameterization/test_parameterization.py
- python/tests/parsers/test_dalle_parser.py
- python/tests/parsers/test_openai_util.py
- python/tests/parsers/test_parser.py
- python/tests/test_library_helpers.py
- python/tests/test_load_config.py
- python/tests/test_parameter_api.py
- python/tests/test_programmatically_create_an_AIConfig.py
- python/tests/test_registry.py
- python/tests/test_resolve.py
- python/tests/test_run_config.py
- python/tests/test_util/test_params.py
- python/tests/util/file_path_utils.py
Run python autoformatter on entire Python libraries
I just got tired of doing this manually every time. We should just eventually make a script to do this, can do later. Filed a task: https://github.com/lastmile-ai/aiconfig/issues/771
This includes the cookbooks
cc jonathan I couldn't just do a clean
```
fd --glob '*.py'  cookbooks/* | xargs python -m 'scripts.lint' --mode=fix --files
```
because there's an issue with llama extension:
```
rossdancraig@Rossdans-MBP aiconfig % fd --glob '*.py'  cookbooks/llama | xargs python -m 'scripts.lint' --mode=fix --files
Running autoflake
[Errno 2] No such file or directory: '/Users/jonathan/Projects/aiconfig/extensions/llama/python/llama.py'
Running isort
Broken 1 paths
Running black
Usage: black [OPTIONS] SRC ...
Try 'black -h' for help.
Error: …
```
> Run python autoformatter on entire Python libraries

- extensions/Gemini/python/src/aiconfig_extension_gemini/Gemini.py
- python/src/aiconfig/util/config_utils.py
- python/tests/test_util/test_config_util.py
Make `get_api_key_from_environment` return nullable
Sometimes key is not defined or set, we need to do this to unblock https://github.com/lastmile-ai/aiconfig/pull/769
The functionality is still unchanged because the optional param `required` defaults to true
Pass all automated tests (which it didn't before)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/772).
* #769
* __->__ #772
> Make `get_api_key_from_environment` return nullable

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/__init__.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_generation.py
Fix wrong import name in Hugging Face model parser extension
This was bad, now it's fixed
Run `pytest` automated tests
Before
```
INTERNALERROR> extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/__init__.py:3: in <module>
INTERNALERROR>     from .remote_inference_client.text_generation import HuggingFaceTextGenerationClient
INTERNALERROR> E   ImportError: cannot import name 'HuggingFaceTextGenerationClient' from 'aiconfig_extension_hugging_face.remote_inference_client.text_generation' (/Users/rossdancraig/Projects/aiconfig/extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_generation.py)
```
After
```
======================================================== 103 passed, 13 warnings in 1.94s …
```
> Fix wrong import name in Hugging Face model parser extension

- cookbooks/HuggingFace/hf.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_generation.py
- python/src/aiconfig/default_parsers/hf.py
Fix issue where hugging face response was not correct type
Turned out to be a typing issue that python did not actually help with.
I also had to adjust the way we load in hugging face key because I got rate limited. We NEED to have more clear way to set API keys in `aiconfig/.env` file though, or else people won't know how to use it! cc @tanya-rai let's add an FAQ/README similar to what we have in the cookbooks: https://github.com/lastmile-ai/aiconfig/blob/3dcf70bcddda7f7041c3bfb6e5d4b6c9a7abd4ab/cookbooks/Getting-Started/getting_started.ipynb?short_path=dcb1340#L23-L25
We need to do this for keys
- HUGGING_FACE_API_TOKEN
- ANYSCALE_ENDPOINT_API_KEY
- OPENAI_API_KEY
- GOOGLE_API_KEY
Connected to local editor (you'll have to modify the `max_tokens` setting) and runs now. We should also …
> Fix issue where hugging face response was not correct type

- python/src/aiconfig/editor/client/package.json
- python/src/aiconfig/editor/client/src/utils/oboeHelpers.ts
- python/src/aiconfig/editor/client/yarn.lock
- python/src/aiconfig/editor/server/queue_iterator.py
- python/src/aiconfig/editor/server/server.py
Get basic streaming to work for run
Building upon what Ryan investigated in https://github.com/lastmile-ai/aiconfig/pull/651, all the frontend changes are from him I just rebased onto his PR
This is a bit tricky becasue we have to support:
1. streaming models --> use a queue iterator for passing the output text
2. non-streaming models --> still yield, just don't use a queue iterator and wait for run command to finish
General flow:
1. Parse prompts from client
2. Define stream callback with queue iterator
3. Start thread to run aiconfig without blocking main thread from accessing queue iterator
4. Create a copy of the original AIConfig so we can write partially streamed outputs, yield and display it without risk of race conditions
5. Wait for queue iterator to start containing data, or …
> Get basic streaming to work for run

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/utils/aiconfigStateUtils.ts
- python/src/aiconfig/editor/client/src/utils/oboeHelpers.ts
Add client-side handling for streaming outputs. We currently derive whether the request should stream by checking settings. Not a huge fan of this since:
- it couples client with config runtime logic for getting the 'stream' value
- assumes 'stream' setting is used by the models
This is sufficient for now, I think. Note that I do think it's nice to allow the editor user to toggle between stream/no stream since it will be useful for debugging their model parser
- Error handling: added `return HttpResponseWithAIConfig(message="No AIConfig loaded", code=400, aiconfig=None).to_flask_format()` in /run with 'stream' set to true and ensured error is shown as notification and run state is stopped on the client
- Non-streaming model (dall-e) run correctly
- Streaming works for models with stream …
> [editor] Streaming Outputs

- python/src/aiconfig/editor/client/package.json
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/JSONEditorToggleButton.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/components/prompt/RunPromptButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/model_settings/ModelSettingsRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_outputs/PromptOutputsRenderer.tsx
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/DalleImageGenerationParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/OpenAIChatModelParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/PaLMChatParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/PaLMTextParserPromptSchema.ts
- python/src/aiconfig/editor/client/yarn.lock
[editor] Add Output Error Rendering
Adding some basic rendering for Error output types if they're ever added to any configs. Also, propagate server run errors through the client as (client-only) Error outputs to display for the relevant prompt:
- Raise an exception in the api/run method on the server and ensure it propagates to the output
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/803).
* __->__ #803
* #802
* #801
* #800
* #799
> [editor] Add Output Error Rendering

- python/src/aiconfig/editor/client/package.json
- python/src/aiconfig/editor/client/src/components/JSONEditorToggleButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- python/src/aiconfig/editor/client/yarn.lock
[editor] ErrorBoundary Renderer for PromptInput
With the ability to set arbitrary JSON for the prompt input, if we have a PromptSchema which states what the input should look like, we should be able to do some basic validation that the input at least matches the general type (for now, compare 'string' PromptInput vs object -- in the future, we could do some basic validation against the schema).
If there is any error with rendering the schema-based rendering for the input, we can use ErrorBoundary to fallback to an error message informing the user that the format is invalid and to toggle to JSON editor to fix.
Toggling to the JSON editor will clear the error state and try to render the correct Schema renderer when toggling back.
Note that in dev mode, these errors are still propagated to a …
> [editor] ErrorBoundary Renderer for PromptInput

- python/src/aiconfig/editor/client/package.json
- python/src/aiconfig/editor/client/src/components/JSONEditorToggleButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/model_settings/ModelSettingsRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- python/src/aiconfig/editor/client/yarn.lock
[editor] ErrorBoundary Renderer for ModelSettings
With the ability to set arbitrary JSON for the model settings, if we have a PromptSchema which states what the setting types should be, the settings renderer will assume those types match the config settings JSON. If the JSON doesn't actually match the schema types, it's possible for the settings renderer to throw an error. If that happens, we can use an ErrorBoundary to fallback to an error message informing the user that the format is invalid and to toggle the JSON editor to fix.
Toggling to the JSON editor will clear the error state and try to render the correct Schema renderer when toggling back.
Note that in dev mode, these errors are still propagated to a top-level error screen which you can dismiss to show the fallback. In prod, …
> [editor] ErrorBoundary Renderer for ModelSettings

- python/src/aiconfig/editor/client/package.json
- python/src/aiconfig/editor/client/src/components/JSONEditorToggleButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/model_settings/ModelSettingsRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/DalleImageGenerationParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/OpenAIChatModelParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/PaLMChatParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/PaLMTextParserPromptSchema.ts
- python/src/aiconfig/editor/client/yarn.lock
[editor][easy] Add 'model' to relevant Prompt Schemas
There is still some investigation needed to know how to handle model vs parser nicely in the editor UX. For now, let's just expose the 'model' option in the settings for those parsers that support it to ensure the usage of those parsers won't be blocked.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/801).
* #803
* #802
* __->__ #801
* #800
* #799
> [editor][easy] Add 'model' to relevant Prompt Schemas

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/AnyscaleEndpointPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextGenerationParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/OpenAIChatModelParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/aiconfigStateUtils.ts
- python/src/aiconfig/editor/server/server.py
Make all outputs in "streaming" format
Doing this to make it easier for Ryan to parse with a singular unified output format, regardless of whether the model parser actually supports streaming or not.
- moved `runPromptStream` -> `runPrompt`, overriding the old definition of `runPrompt` by now passing in an `enableStreaming` flag
- still relying on `isStreamingSupported()` function to set the `enableStreaming` param to true or false
- default to `stream` param being `True` on backend server (however this has no effect for non-streaming models like Dall-E)
Test that both streaming and non-streaming settings work as expected, as well as test that a model which does not support streaming (ex: Dall-E) still works. Now when user hasn't explicitly clicked the "stream" setting, it will default to …
> Make all outputs in "streaming" format

- extensions/HuggingFace/python/requirements.txt
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/__init__.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_2_speech.py
[AIC-py] add hf text 2 speech parser
```
{
"name": "NYC Trip Planner",
"description": "Intrepid explorer with ChatGPT and AIConfig",
"schema_version": "latest",
"metadata": {
"models": {
"gpt2": {
"model": "gpt2",
"max_tokens": 3000,
"system_prompt": "Some random system prompt"
},
"suno/bark": {
"model": "suno/bark"
}
},
"model_parsers": {
"suno/bark": "HuggingFaceText2SpeechTransformer"
},
"default_model": "gpt2"
},
"prompts": [
{
"name": "test_tts",
"input": "the quick brown fox",
"metadata": {
"model": {
"name": "suno/bark",
"settings": {}
}
}
}
]
}
mp = HuggingFaceText2SpeechTransformer()
ModelParserRegistry.register_model_parser(mp)
config = AIConfigRuntime.load("/Users/jonathan/Projects/aiconfig/test_hf_t2s.aiconfig.json")
config.callback_manager = CallbackManager([])
options = …
```
> [AIC-py] add hf text 2 speech parser

- python/src/aiconfig/editor/server/server.py
[editor][server] 1/n endpoint clear outputs
server endpoint to clear outputs from server side aiconfig state (changes not persisted to disk).
1. Run Prompt
2. Clear outputs.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/790).
* #791
* __->__ #790
> [editor][server] 1/n endpoint clear outputs

- python/src/aiconfig/schema.py
[py][easy] Set Deleted Outputs as None
Inside the python sdk, `delete_output` previously set attribute outputs of prompts to []. While this does delete the outputs, it also retains an empty list as the value of prompt.output
When executing config.save(),  the config would have persisted empty arrays. This behaviour is not what we want.
Instead, set to None. When config.save() is called, None values can be ignored and removed from the resulting aiconfig.json
1. Run prompt
2. delete output
3. Save config.validate that config doesn't have "outputs" field for config
| ipynb  | resulting config |
| <img width="768" alt="Screenshot 2024-01-08 at 3 26 05 PM" src="https://github.com/lastmile-ai/aiconfig/assets/141073967/616d8fce-bf54-488b-8cc4-57b83b76744b">  | …
> [py][easy] Set Deleted Outputs as None

- python/src/aiconfig/editor/client/src/Editor.tsx
- python/src/aiconfig/editor/client/src/components/EditorContainer.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/utils/api.ts
[edtior][client] 2/n clear outputs functionality
added a button that clears all outputs.
- added an action
- call to server api
- Run prompt
- validate config has an output
- clear outputs
- validate config cleared outputs.
https://github.com/lastmile-ai/aiconfig/assets/141073967/f1622528-5a77-49cd-80a3-581520229a7f
> [edtior][client] 2/n clear outputs functionality

- cookbooks/HuggingFace/hf.py
- python/src/aiconfig/default_parsers/dalle.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/default_parsers/palm.py
- python/src/aiconfig/model_parser.py
- python/tests/parsers/test_openai_util.py
Explicitly set "model" property for models that support it
This change allows us to automatically set the "model" for the following model parsers:
* OpenAI
* Anyscale Endpoint
* Hugging Face text generation
* PaLM
* Dall-E
Without this change the local editor breaks because if a user doesn't explicitly specify the "model" property in settings metadata, inference fails for (some of) the above model parsers. This isn't ideal, because the user has already selected the model they want to use from the model selector, so shouldn't need to additionally specify a model id as well.
There is still a larger issue of how we distinguish a model ID from a model parser ID. Filed #782 to come up with a proper fix for that.
> Explicitly set "model" property for models that support it

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/DalleImageGenerationParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextGenerationParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/PaLMChatParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/PaLMTextParserPromptSchema.ts
[editor][easy] Add Descriptions to Prompt Schemas
Add descriptions to the other prompt schemas for the core models. Also, fix some of the hugging face properties to have correct ranges based on the documentation (tested those ranges are valid by setting the values to 80 or so and running HF prompt).
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/814).
* #818
* #815
* __->__ #814
> [editor][easy] Add Descriptions to Prompt Schemas

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/DalleImageGenerationParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceText2ImageDiffusorPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextGenerationParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/PaLMChatParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/PaLMTextParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
[editor] HuggingFaceText2ImageDiffusorPromptSchema
Add the PromptSchema for HuggingFaceText2ImageDiffusor. Note that there are several settings which are going to have to just be supported programatically since modelling them with schema types would be pretty hard:
generator, latents, prompt_embeds, negative_prompt_embeds, callback
Each is of a python class-derived type
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/815).
* #818
* __->__ #815
* #814
> [editor] HuggingFaceText2ImageDiffusorPromptSchema

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/__init__.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/image_2_text.py
[AIC-py] hf image2text parser
test
patch https://github.com/lastmile-ai/aiconfig/pull/816
python extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/run_hf_example.py extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/hf_local_example.aiconfig.json
-> "red fox in the woods"
> [AIC-py] hf image2text parser

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/__init__.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/automatic_speech_recognition.py
[extensions][py][hf] 2/n ASR model parser impl
Model Parser for the Automatic Speech Recognition task on huggingface.
Decisions made while implementing:
- manual impl to parse input attachments
- - threw exceptions on every unexpected step. Not sure if this is the direction we want to go with this.
- This diff does not implement serialize() for the model parser (will implement on diff ontop)
Created an mp3 file that says "hi". Used aiconfig to run asr on it.
|<img width="922" alt="Screenshot 2024-01-09 at 7 14 47 PM" src="https://github.com/lastmile-ai/aiconfig/assets/141073967/fe68751d-e20b-41d9-9da5-cc9a32859cba">
|<img width="1461" alt="Screenshot 2024-01-09 at 5 54 33 PM" src="https://github.com/lastmile-ai/aiconfig/assets/141073967/78063a3e-2b9a-4a39-80d9-ef28a7d706cf">|
| …
> [extensions][py][hf] 2/n ASR model parser impl

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/automatic_speech_recognition.py
[extensions][py][hf] 1/n asr scaffolding
Setting up the asr parser class
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/779).
* #780
* __->__ #779
> [extensions][py][hf] 1/n asr scaffolding

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/automatic_speech_recognition.py
[easy][extension][py][hf] add unintended-removed comma
comma was mistakenly removed. Adding it back in.
For context: Doesn't break anything because in python  you can concatenate strings without using the + operator by simply placing them adjacent to each other, like this:
```
"string1" "string2"
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/839).
* #840
* __->__ #839
> [easy][extension][py][hf] add unintended-removed comma

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/attachments/AttachmentUploader.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputAttachmentsSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceAutomaticSpeechRecognitionPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceImage2TextTransformerPromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
[editor] HuggingFaceImage2TextTransformerPromptSchema
Get the input schema implemented so the input renders. Need to add model_settings afterwards
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/848).
* __->__ #848
* #845
* #817
> [editor] HuggingFaceImage2TextTransformerPromptSchema

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceAutomaticSpeechRecognitionPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceImage2TextTransformerPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceText2ImageDiffusorPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceText2SpeechTransformerPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextGenerationParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextGenerationTransformerPromptSchema.ts
> [editor][easy] Add 'model' to HF Prompt Schemas

- extensions/HuggingFace/python/requirements.txt
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/image_2_text.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_2_speech.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_generation.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_summarization.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_translation.py
[HF][5/n] Image2Text: Allow base64 inputs for images
Before we didn't allow base64, only URI (either local or http or https). This is good becuase our text2Image model parser outputs into a base64 format, so this will allow us to chain model prompts!
Rebase and test on https://github.com/lastmile-ai/aiconfig/commit/0d7ae2b32ac2eb75cd41ac91e222c5bb6bb5c918.
Follow the README from AIConfig Editor https://github.com/lastmile-ai/aiconfig/tree/main/python/src/aiconfig/editor#dev, then run these command
```bash
aiconfig_path=/Users/rossdancraig/Projects/aiconfig/cookbooks/Gradio/huggingface.aiconfig.json
parsers_path=/Users/rossdancraig/Projects/aiconfig/cookbooks/Gradio/hf_model_parsers.py
alias aiconfig="python3 -m 'aiconfig.scripts.aiconfig_cli'"
aiconfig edit --aiconfig-path=$aiconfig_path …
```
> [HF][5/n] Image2Text: Allow base64 inputs for images

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_generation.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_summarization.py
[HF][streaming][1/n] Text Summarization
TSIA
Adding streaming functionality to text summarization model parser
Rebase onto and test it with https://github.com/lastmile-ai/aiconfig/pull/852/commits/11ace0a5a31b9404a97965e5fa478d5b19adcb67.
Follow the README from AIConfig Editor https://github.com/lastmile-ai/aiconfig/tree/main/python/src/aiconfig/editor#dev, then run these command
```bash
aiconfig_path=/Users/rossdancraig/Projects/aiconfig/cookbooks/Gradio/huggingface.aiconfig.json
parsers_path=/Users/rossdancraig/Projects/aiconfig/cookbooks/Gradio/hf_model_parsers.py
alias aiconfig="python3 -m 'aiconfig.scripts.aiconfig_cli'"
aiconfig edit --aiconfig-path=$aiconfig_path --server-port=8080 --server-mode=debug_servers --parsers-module-path=$parsers_path
```
Then in AIConfig Editor run the …
> [HF][streaming][1/n] Text Summarization

- extensions/HuggingFace/python/requirements.txt
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_generation.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_summarization.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_translation.py
[HF][streaming][2/n] Text Translation
TSIA
Adding streaming output support for text translation model parser. I also fixed a bug where we didn't pass in `"translation"` key into the pipeline
Rebase onto and test it: https://github.com/lastmile-ai/aiconfig/commit/5b7434483e2521110bbe3cc3380d9b99a6d4e8be.
Follow the README from AIConfig Editor https://github.com/lastmile-ai/aiconfig/tree/main/python/src/aiconfig/editor#dev, then run these command
```bash
aiconfig_path=/Users/rossdancraig/Projects/aiconfig/cookbooks/Gradio/huggingface.aiconfig.json
parsers_path=/Users/rossdancraig/Projects/aiconfig/cookbooks/Gradio/hf_model_parsers.py
alias aiconfig="python3 -m 'aiconfig.scripts.aiconfig_cli'"
aiconfig edit --aiconfig-path=$aiconfig_path --server-port=8080 --server-mode=debug_servers …
```
> [HF][streaming][2/n] Text Translation

- extensions/HuggingFace/python/requirements.txt
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_2_speech.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_generation.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_summarization.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_translation.py
[HF][streaming][3/n] Text2Speech (no streaming, but updating docs on completion params)
Ok this one is weird. Today, streaming is only ever supported on text outputs in Transformers library. See `BaseStreamer` in here: https://github.com/search?q=repo%3Ahuggingface%2Ftransformers%20BaseStreamer&type=code
In the future it may support other formats, but not yet. For example, OpenAI supports it: https://community.openai.com/t/streaming-from-text-to-speech-api/493784
Anyways, I basically here only did some updates to docs to clarify why completion params were null. Jonathan and I synced about this briefly ofline, but I forgot again so wanted to capture it here so no one forgets
--- …
> [HF][streaming][3/n] Text2Speech (no streaming, but updating docs on completion params)

- extensions/HuggingFace/python/requirements.txt
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/image_2_text.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_2_speech.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_generation.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_summarization.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_translation.py
[HF][streaming][4/n] Image2Text (no streaming, but lots of fixing)
This model parser does not support streaming (surprising!):
```
TypeError: ImageToTextPipeline._sanitize_parameters() got an unexpected keyword argument 'streamer'
```
In general, I mainly just did a lot of fixing up to make sure that this worked as expected. Things I fixed:
1. Now works for multiple images (it did before, but didn't process responses for each properly, just put the entire response)
2. Constructing responses to be in pure text output
3. Specified the completion params that are supported (only 2: https://github.com/huggingface/transformers/blob/701298d2d3d5c7bde45e71cce12736098e3f05ef/src/transformers/pipelines/image_to_text.py#L97-L102C13)
Next diff I will add support for b64 encoded image format --> we …
> [HF][streaming][4/n] Image2Text (no streaming, but lots of fixing)

- python/src/aiconfig/editor/client/src/LocalEditor.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptActionBar.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/RunPromptButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputRenderer.tsx
Update the RunPromptButton placement to be beside the input so that it is easy to access (stays in place) regardless of long input/outputs, per discussion in https://github.com/lastmile-ai/aiconfig/pull/844:
- Make sure run and cancel still work
> [editor] RunPromptButton Placement

- python/src/aiconfig/editor/client/src/components/GlobalParametersContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/ModelSelector.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptName.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
Some things that got left out / missed as part of this stack split: https://github.com/lastmile-ai/aiconfig/pull/810/files
Mainly just the labels for prompt name/input/model selector; styling already handles hiding them in local editor and showing them in gradio:
> [editor] Add Missing Styling Changes to Core Components

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceAutomaticSpeechRecognitionPromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
[editor] Updates to  ASR prompt Schema
Adding in changes to the ASR prompt schema. Previously this schema was shipped to unblock.
Couple of changes:
- Support a list of 5 audio formats.
- - Top 5 chosen by [asking GPT](https://lastmileai.dev/workbooks/clr6yqzzy0015pe4ewvgm4ce9)
- - Note: ASR supports FFmpeg to transcribe audio. For now we are choosing a few to start
- Added a few completion params, found while implementing model parser for ASR
- Added a few params for pipeline creation.
TODO:
investigate these types because they may not be primitives
- pipeline creation:
- - "decoder",
- - - I believe this should be an in memory object
- - "feature_extractor"
- - - Same with this, this might have to be an in memory object
- completion params:
- - "generate_kwargs"
- - This is a …
> [editor] Updates to  ASR prompt Schema

- python/src/aiconfig/editor/server/server.py
[bug fix][AIC-py] sort of do exception handling during streaming
This piggybacks on the cancellation during stream flow, which works as far as I've tested.
The frontend gets the message.
> [bug fix][AIC-py] sort of do exception handling during streaming

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/__init__.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/automatic_speech_recognition.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/image_2_text.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_2_image.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_2_speech.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_generation.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_summarization.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_translation.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_generation.py
HF transformers: Small fixes nits
Small fixes from comments from Sarmad + me from these diffs:
- https://github.com/lastmile-ai/aiconfig/pull/854
- https://github.com/lastmile-ai/aiconfig/pull/855
- https://github.com/lastmile-ai/aiconfig/pull/821
Main things I did
- rename `refine_chat_completion_params` --> `chat_completion_params`
- edit `get_text_output` to not check for `OutputDataWithValue`
- sorted the init file to be alphabetical
- fixed some typos/print statements
- made some error messages a bit more intuitive with prompt name
- sorted some imports
- fixed old class name `HuggingFaceAutomaticSpeechRecognition` --> `HuggingFaceAutomaticSpeechRecognitionTransformer`
These are all small nits and shouldn't change functionality
> HF transformers: Small fixes nits

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/__init__.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/automatic_speech_recognition.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/image_2_text.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_2_image.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_2_speech.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_generation.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_summarization.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_translation.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/util.py
- python/src/aiconfig/util/params.py
Fix parameterization issues
Now that we have non-text input model parsers, we can see some issues in our parameterization.
1) ASR and Image-to-Text modelparsers should NOT be `ParameterizedModelParser` instances, since their inputs cannot be parameterized.
2) Parameter resolution logic shouldn't throw errors in the case where it's parsing prompts belonging to regular model parsers.
Test Plan:
Ran the translation prompt for this aiconfig:
```
prompts: [
{
"name": "image_caption",
"input": {
"attachments": [
{
"data": "https://s3.amazonaws.com/lastmileai.aiconfig.public/uploads/2024_1_10_18_41_31/1742/bear_with_honey.png",
"mime_type": "image/png"
},
{
"data": "https://s3.amazonaws.com/lastmileai.aiconfig.public/uploads/2024_1_10_18_41_31/7275/fox_in_forest.png",
"mime_type": "image/png"
} …
```
> Fix parameterization issues

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/__init__.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/automatic_speech_recognition.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/image_2_text.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_2_image.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_2_speech.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_generation.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_summarization.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_translation.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/util.py
Support custom specified models for HF model parsers
The HF prompt schema has been updated in #850 to support a "model" property, which can specify the model to use for a given HF task.
This change updates the model parsers to use this setting.
Test Plan:
Tested with the following prompt:
```
{
"name": "image_caption",
"input": {
"attachments": [
{
"data": "https://s3.amazonaws.com/lastmileai.aiconfig.public/uploads/2024_1_10_18_41_31/1742/bear_with_honey.png",
"mime_type": "image/png"
},
{
"data": "https://s3.amazonaws.com/lastmileai.aiconfig.public/uploads/2024_1_10_18_41_31/7275/fox_in_forest.png",
"mime_type": "image/png"
}
]
},
"metadata": {
"model": {
"name": "HuggingFaceImage2TextTransformer",
"settings": {
"max_new_tokens": 10,
"model": "Salesforce/blip-image-captioning-base"
}
}, …
```
> Support custom specified models for HF model parsers

- python/src/aiconfig/editor/client/package.json
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/yarn.lock
Hook up UI for streaming error handling:
https://github.com/lastmile-ai/aiconfig/assets/5060851/bed5a317-990f-42fb-8f6b-b07bc9e2bb06
https://github.com/lastmile-ai/aiconfig/assets/5060851/969492cc-d9bd-4cf3-be27-e785430ff25e
As part of this, had a remark-gfm issue surface in the output markdown renderer and found that we somehow were using updated version (4.0.0) which differs from (3.0.1) used in lastmile and also appears to have breaking changes (https://stackoverflow.com/questions/77138105/reactmarkdown-remarkgfm-everything-renders-as-expected-except-tables-typee), so bumped it down
> [editor] Streaming Error Output Handling UI

- extensions/HuggingFace/python/requirements.txt
Add sacremoses dependency to HF extension
We'd be getting this issue where the streaming suddenly stops and hangs
I suspect that this is to due being in debug mode instead of prod mode. We also know that debug mode in general gets runtime errors
See doc here for more details on how I investigated, including what commands I used:
https://docs.google.com/document/d/1NJjFMQ1_y9iz7kXEX_yZeY4yYgVsTsMF5IQhThXU87c/edit#heading=h.44hkfutqnu8c
Still, just saw that it was recommened to install this dependency, and there doesn't seem to be an issue with it os just adding it: https://pypi.org/project/sacremoses/
First get the `python-aiconfig-test` module:
```bash
pip3 install --index-url https://test.pypi.org/simple --extra-index-url https://pypi.org/simple python-aiconfig-test==1.1.30 --force
```
I …
> Add sacremoses dependency to HF extension

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/image_2_text.py
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceAutomaticSpeechRecognitionPromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceImage2TextTransformerPromptSchema.ts
Add model setting completion params for Image2Text prompt schema
TSIA, pretty simple actually
Follow the README from AIConfig Editor https://github.com/lastmile-ai/aiconfig/tree/main/python/src/aiconfig/editor#dev, then run these commands:
Make sure also that you don't have the `python-aiconfig-test` installed: `pip3 uninstall python-aiconfig-test`
```bash
aiconfig_path=/Users/rossdancraig/Projects/aiconfig/cookbooks/Gradio/huggingface.aiconfig.json
parsers_path=/Users/rossdancraig/Projects/aiconfig/cookbooks/Gradio/hf_model_parsers.py
alias aiconfig="python3 -m 'aiconfig.scripts.aiconfig_cli'"
aiconfig edit --aiconfig-path=$aiconfig_path --server-port=8080 --server-mode=debug_servers --parsers-module-path=$parsers_path
```
---
Stack created with [Sapling](https://sapling-scm.com). Best …
> Add model setting completion params for Image2Text prompt schema

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/automatic_speech_recognition.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/image_2_text.py
[HF][fix] Use ParameterizedModelParser instead of ModelParser
Fixing this error:
```
Exception: HuggingFaceImage2TextTransformer.run() got an unexpected keyword argument 'callback_manager'
```
This seems like a pretty brittle bug. If we use `ModelParser` isntead of `ParameterizedModelParser`, we get a bug because `callback_manager` is not a supported kwargs for the `run_inference()` method. This gets filtered out by the `ParameterizedModelParser.run()` method (https://github.com/lastmile-ai/aiconfig/blob/0ceb17636bae2b5416e7b415cdc87fd71b5ba3b0/python/src/aiconfig/default_parsers/parameterized_model_parser.py#L48-L54) but these kwags are not accepted  by the `ModelParser.run()` method (https://github.com/lastmile-ai/aiconfig/blob/0ceb17636bae2b5416e7b415cdc87fd71b5ba3b0/python/src/aiconfig …
> [HF][fix] Use ParameterizedModelParser instead of ModelParser

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/util.py
[ez][fix][HF]Explicitly set hf_model to None if it's empty string
Lol literally a 1-line fix.
I tested by removing the model name explicitly from HF model parsers to use the default, but this errored since we're setting it to "" instead of None.
Before
```
model_name=""
```
I got an error saying that no model "" exists, forgot to take screenshot but it was real pls believe me
After
```
model_name=None
No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.
```
https://github.com/lastmile-ai/aiconfig/assets/151060367/db6b35d4-9e03-4ff5-b035-c77263978fd4
--- …
> [ez][fix][HF]Explicitly set hf_model to None if it's empty string

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/automatic_speech_recognition.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/image_2_text.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/util.py
Revert "[HF][fix] Use ParameterizedModelParser instead of ModelParser"
Reverts https://github.com/lastmile-ai/aiconfig/pull/877
This caused a bug because image and audio inputs can't be parametrized. See https://github.com/lastmile-ai/aiconfig/pull/882 for a better fix instead
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/881).
* #885
* #883
* #882
* __->__ #881
* #879
> Revert "[HF][fix] Use ParameterizedModelParser instead of ModelParser"

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/automatic_speech_recognition.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/image_2_text.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/util.py
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/parameterized_model_parser.py
- python/src/aiconfig/model_parser.py
[HF][fix] Allow `kwargs` in `ModelParser.run()`
See https://github.com/lastmile-ai/aiconfig/pull/877 for context, and https://github.com/lastmile-ai/aiconfig/pull/880 for why that original fix needed to be reverted
Just a quick hack to get unblocked. I tried originally to make the ASR and Image2Text ParameterizedModel but that caused other errors.
Before
https://github.com/lastmile-ai/aiconfig/assets/151060367/a23a5d5c-d9a2-415b-8a6e-9826da56e985
After
https://github.com/lastmile-ai/aiconfig/assets/151060367/f29580e9-5cf6-43c5-b848-bb525eb368f2
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/882).
* #885
* #883
* __->__ #882
* #881
* #879
> [HF][fix] Allow `kwargs` in `ModelParser.run()`

- cookbooks/Gradio/huggingface.aiconfig.json
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/automatic_speech_recognition.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/image_2_text.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_2_speech.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/util.py
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/parameterized_model_parser.py
- python/src/aiconfig/model_parser.py
[HF][fix] Small nit fixes to ASR: Remove "model" from completion params, get_output_text in right format
Getting an error saying that "model" param is defined twice, which it is because we're passing it through completion params and again through the explicit model param. This along with the change in  https://github.com/lastmile-ai/aiconfig/pull/879 will ensure that the right model of `None` is passed if the value is empty string.
I also fixed typo in the aiconfig.json file
I also had to change the data field from `"./hi.mp3"` to `"cookbooks/Gradio/hi.mp3"` becuase I can only run the config from the high level `aiconfig` directory due to this line when running the editor: https://github.com/lastmile-ai/aiconfig/blob/b632094618c8f96b186b1849d0036e1313e02c5a/python/src/aiconfig/scripts/aico …
> [HF][fix] Small nit fixes to ASR: Remove "model" from completion params, get_output_text in right format

- cookbooks/Gradio/huggingface.aiconfig.json
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/automatic_speech_recognition.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/image_2_text.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/text_2_speech.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/util.py
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/parameterized_model_parser.py
- python/src/aiconfig/model_parser.py
Use facebook/mms-tts-eng instead of suno/bark in Gradio cookbook for Text2Speech
Bark is ~5GB and took my laptop 30mins to download for the first time. The Facebook MMS (https://huggingface.co/facebook/mms-tts-eng?fbclid=IwAR22U5VSaZ_V7QW4TJe77CM7f4fsTHjqCMjgLKV31wUl66ww1vXYSrEl-MA) is only ~100MB which is way better and at least for cookbook I feel much more worth it to quickly test things out. Yes the output quality is way more memey and "voice AI" stereotype, but I feel the tradeoff is worth it
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/885).
* __->__ #885
* #883
* #882
* #881
* #879
> Use facebook/mms-tts-eng instead of suno/bark in Gradio cookbook for Text2Speech

- python/src/aiconfig/Config.py
Delete unused callback_manager argument from run commands
This is an extension of https://github.com/lastmile-ai/aiconfig/pull/881
Now once this is removed, only the `run-with_dependencies` kwarg should be used and this will unblock Sudhanshu from completing https://github.com/lastmile-ai/aiconfig/issues/664
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/886).
* #887
* __->__ #886
> Delete unused callback_manager argument from run commands

- CHANGELOG.md
- python/pyproject.toml
- typescript/package.json
Updated CHANGELOG for v1.1.11
TSIA, doing this so we can package a new release!
I messed up v1.1.4 for typescript sorry. I also messed up and didn't realize I needed to run `yarn build` from within the editor dir itself, so need to repackage python to v1.1.11
> Updated CHANGELOG for v1.1.11

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/editor/server/server_utils.py
[bug fix] [AIC-py] issue #889
Root cause: here (https://github.com/lastmile-ai/aiconfig/blob/49ac58d0111a3f4df79d72786002a55ad8b585f1/python/src/aiconfig/editor/server/server.py#L159),
we set the path to save at from the aiconfig instance's path field
if no path is given in the HTTP request.
However, the field will be None if the file did not exist when the server is initialized.
Why is that? Because if we're in the file create branch here (https://github.com/lastmile-ai/aiconfig/blob/49ac58d0111a3f4df79d72786002a55ad8b585f1/python/src/aiconfig/editor/server/server_utils.py#L221-L234)
then the aiconfig gets initialized and saved, but the field name is None.
You can see the field gets set to None in the AIConfigRuntime init.
Hacky fix (this PR): set the runtime field name right after …
> [bug fix] [AIC-py] issue #889

- aiconfig-docs/docs/editor.md
Adding the AIConfig editor docs to AIConfig documentation
Sections covered:
- Set up the Editor
- Open the AIConfig Editor
- Edit and save AIConfigs
- Run prompts
- Chain prompts
- Create prompt templates
Still to do:
- Adding video to the documentation
- FAQ section for troubleshooting issues
- List of environment variable mapping for different model parsers
> Andrew lastmile patch 12

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/schema.py
[editor] Only stream output, not entire AIConfig
This will be a bug for anything that streams multiple return outputs, but for now we don't have that and all our models which support streaming only output a single output
Ok wow yea, even on Chrome this is *noticeably* faster!
https://github.com/lastmile-ai/aiconfig/assets/151060367/3613c2e5-8a8c-43c8-994d-d7ae62469594
> [editor] Only stream output, not entire AIConfig

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_generation.py
- python/src/aiconfig/default_parsers/hf.py
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
Connect local HF model parser prompt input schemas to the right classnames
We did a bit of changing of classnames, so just updating here, as well as re-ordering some of the imports
Also important to note is that we currently don't have this for the remote inference text generation class:
https://github.com/lastmile-ai/aiconfig/blob/2364ee32d340a105b4485fa134086f9093d42384/extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_generation.py#L124
I'll handle that next diff, as well as rename that class (and test that it works without model name specified). For now I just copy pasted the remote_inference/text_generation.py --> hf.py (core parser). Just to show that they're indeed the same functionality and that core parser can be deleted
Before …
> Connect local HF model parser prompt input schemas to the right classnames

- python/requirements.txt
- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/editor/server/server_utils.py
- python/src/aiconfig/scripts/aiconfig_cli.py
[AIC-py][editor] server: persistent local cfg + telemetry flag, endpoints
Test:
- Start the server with and without flag and with no file, see that it gets created with correct contents
- start the server with and without flag with existing file, with both true and false
- hit both endpoints, check responses and that the file contents are changed
https://github.com/lastmile-ai/aiconfig/assets/148090348/b36c3c00-c14b-4cde-8449-60386f2be1eb
> [AIC-py][editor] server: persistent local cfg + telemetry flag, endpoints

- README.md
- aiconfig-docs/docs/editor.md
- aiconfig-docs/docs/getting-started.md
[docs] update to correct command
missing equal signs in 'aiconfig edit --aiconfig-path={file_name}' in documentation
> [docs] update to correct command

- python/src/aiconfig/scripts/aiconfig_cli.py
- python/src/aiconfig/scripts/rage/rage.py
[AIC-py] cli rage
This just tells the user how to open an issue. I don't want to do anything automatically
because (a) user trust, and (b) it's much harder to implement without additional bugs.
This is mostly bedside manner. If the user is raging, they are angry.
Troll them a little bit to lighten the mood first.
https://github.com/lastmile-ai/aiconfig/assets/148090348/2369306f-3af7-49f5-96bb-0ac9be323b51
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/870).
* #903
* __->__ #870
* #869
> [AIC-py] cli rage

- python/requirements.txt
[bug fix] bump lastmile utils to 0.0.20
get_logger doesn't import. this bump adds that function and should fix main.
> [bug fix] bump lastmile utils to 0.0.20

- python/src/aiconfig/editor/client/src/components/SettingsPropertyRenderer.tsx
[editor][client] render array objects in settings properly
Upon loading the OpenAI function calling aiconfig, the editor client does not render the function data. This is because the functions are an array, and the client does not initialize array data.
In this diff, if the Settings data is an array with an initial value, properly set/intiailize and render the array data (inside SettingsPropertyRenderer)
Also updated the object renderer/settings to render json editor for an unspecified Json
Load the function calling aiconfig and open the model settings drawer. Notice the functions get rendered.
Modified function call information inside the json editor. Tested the save was successful.
https://github.com/lastmile-ai/aiconfig/assets/141073967/f477f970-3de1-4c7b-adb4-eba1a8ca0bce
> [editor][client] render array objects in settings properly

- python/src/aiconfig/editor/client/src/components/prompt/RunPromptButton.tsx
[1/n] Disable Run Button: UI Display
For now no functionality, just setting up the visual UI display, will connect next PR. Doing this to make PRs smaller and easier to review + land
When setting `disabled` to True
When setting `disabled` to False, still works as before
https://github.com/lastmile-ai/aiconfig/assets/151060367/1c6ad683-8c50-46aa-9760-8eea8bd40fed
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/905).
* #907
* __->__ #905
> [1/n] Disable Run Button: UI Display

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputRenderer.tsx
- python/src/aiconfig/editor/client/src/shared/types.ts
[2n] Disable Run Button: Create runningPromptId field to determine if button should be disabled
I did a few things:
1. Create a new state id `runningPromptId` to check which prompt is running, making sure to set these correctly on run prompt actions
2. Read from this state in the AIConfigEditor and passed it as a prop down to the `RunPromptButton`
Question: Is there a better way of doing step #2 so that we don't need to keep piping it?
Make sure that:
1. When you are running a prompt, you can still cancel it
2. When another prompt is running, you can't run any other prompt
3. When prompt is complete (or cancelled or errored), all the prompts can run again
https://github.com/lastmile-ai/aiconfig/assets/151060367/6e9a9cbf-6469-4ecb-ba74-1ede2ed1a292
--- …
> [2/n] Disable Run Button: Create runningPromptId field to determine if button should be disabled

- python/src/aiconfig/editor/client/src/LocalEditor.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/utils/oboeHelpers.ts
- python/src/aiconfig/editor/server/server.py
Delete `aiconfig_complete` stream response, replace with `aiconfig`
Before we used to not support streaming, so when we would return `aiconfig` it would be from a blocking hanging operation. This meant that we needed to set `isRunning` prompt state to be true while we were waiting, but now we don't need to do that anymore after we migrated all run events to return in streaming response format, even for non-streaming models: https://github.com/lastmile-ai/aiconfig/pull/806
Also we are now no longer using the `streamApi` helper since we added and are now using `streamingApiChain`, which was added in https://github.com/lastmile-ai/aiconfig/pull/789
Finally, if you want more resources on how streaming is connected, you can check out https://github.com/lastmile-ai/aiconfig/pull/910 which is a …
> Delete `aiconfig_complete` stream response, replace with `aiconfig`

- python/src/aiconfig/editor/client/package.json
- python/src/aiconfig/editor/client/src/LocalEditor.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigContext.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/index.tsx
- python/src/aiconfig/editor/client/src/shared/types.ts
- python/src/aiconfig/editor/client/src/utils/api.ts
- python/src/aiconfig/editor/client/yarn.lock
[editor][client] Enable Telemetry based on User Config settings
This diff builds on top of @rholinshead's starting point for telemetry diff. Most of that looked good to me so I didn't touch it beside @rossdanlm 's .
- Building off of #869, if `allow_usage_data_sharing` is set to True, initialize Datadog Browser logging with a session ID.
- Disabled telemetry in dev mode as per @rholinshead 's comment that the hot reload spams the logs with something like "datadog logging already initialized"
- Moved the initialization logic away from`index.tsx` into `editor.tsx` so that it can be configurable.
1. yarn build
2. run in "prod" mode
3. Edit AIconfig
4. Hit Save button -> validate datadog log sent
repeat with aiconfig.rc set with false logging
|<img width="963" alt="Screenshot 2024-01-12 at 7 …
> [editor][client] Enable Telemetry based on User Config settings

- python/src/aiconfig/editor/client/package.json
- python/src/aiconfig/editor/client/src/LocalEditor.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigContext.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/index.tsx
- python/src/aiconfig/editor/client/src/shared/types.ts
- python/src/aiconfig/editor/client/yarn.lock
[editor] Starting Point for Telemetry
rebased version of #804 onto main
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/864).
* #899
* __->__ #864
> [editor] Starting Point for Telemetry

- python/src/aiconfig/editor/client/src/LocalEditor.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/server/server.py
Add explicit "stop_streaming" event to signal streaming is finished
I think this is cleaner and better for us to deal with. It also breaks down the aiconfig streaming logic to be more explicitly handled for next PR.
See comments about this in
- https://github.com/lastmile-ai/aiconfig/pull/907#discussion_r1451013546
- https://github.com/lastmile-ai/aiconfig/pull/911#discussion_r1451629515
Both the streaming and non-streaming models work the same as before
https://github.com/lastmile-ai/aiconfig/assets/151060367/2c3fd802-e95e-417c-ac80-7b6e18983520
> Add explicit "stop_streaming" event to signal streaming is finished

- python/src/aiconfig/editor/client/src/LocalEditor.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/prompt/RunPromptButton.tsx
- python/src/aiconfig/editor/client/src/contexts/AIConfigContext.tsx
2/n: Read-only mode: Connect context to Run Prompt button
Created a new value that gets read from props in `AIConfigEditor` and passed into AIConfigContext to be read by downstream components. Going to do this diff stack each component 1 at a time for easier review +  unblocking
I decided not to use a tooltip for read-only mode. Instead planning to add a big text at top saying that you're in read-only mode, and you won't be able to make any changes
Still works as before
Read-only shows no tooltip
Not in read-only and running a prompt shows a tooltip
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/916).
* __->__ #916
* #913
> 2/n: Read-only mode: Connect context to Run Prompt button

- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
Refactor ConsolidateAIConfig to only take in specificed sub-actions
I was having some trouble converting everything to `STREAM_AICONFIG_CHUNK` so I'm just doing really easy steps to keep diffs easy to review and test. You'll see final code changes at end of diff stack.
No functional changes, but I want to use the `CONSOLIDATE_AICONFIG` event to pass in nested action `STREAM_AICONFIG_CHUNK` action later in stack, without requiring me to pass it in directly to the `aiconfigReducer`. By separating these, they can be distinct types and easier to manage
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/917).
* #928
* #926
* #925
* #924
* #922
* #921
* #920
* #919
* #918
* __->__ #917
> Refactor ConsolidateAIConfig to only take in specificed sub-actions

- python/src/aiconfig/editor/client/src/LocalEditor.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/server/server.py
[ez] Rename `aiconfig` stream response to `aiconfig_chunk` response
I was having some trouble converting everything to `STREAM_AICONFIG_CHUNK` so I'm just doing really easy steps to keep diffs easy to review and test. You'll be able to see final result at end of diff stack
Just doing very simple name coy and replace, no functional changes
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/918).
* #928
* #926
* #925
* #924
* #922
* #921
* #920
* #919
* __->__ #918
* #917
> [ez] Rename `aiconfig` stream response to `aiconfig_chunk` response

- python/src/aiconfig/editor/client/src/LocalEditor.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/server/server.py
Replace RUN_PROMPT with STREAM_AICONFIG_CHUNK inside of streaming implementation
This is the exact same logic, but I'm just going to do this as intermediate step to keep things clear and easy to review
No functional changes, streaming and non streaming models still work
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/919).
* #928
* #926
* #925
* #924
* #922
* #921
* #920
* __->__ #919
* #918
* #917
> Replace RUN_PROMPT with STREAM_AICONFIG_CHUNK inside of streaming implementation

- python/src/aiconfig/editor/client/src/LocalEditor.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/server/server.py
Implement STREAM_AICONFIG_CHUNK action
This is the biggest part of this diff stack. The functionality is still exactly the same as before, but now we can call it directly instead of as a sub-action within `"CONSOLIDATE_AICONFIG"`. I think this is much cleaner.
Another benefit is this removes the need for having to check the `isRunning` flags within the consolidated `"RUN_PROMPT"` sub-action, since we now know that the only time we can call that is through the beginning and the end (non-streaming end). Next PR I am going to split this into two separate Actions:
1. `"RUN_PROMPT_START"`
2. `"RUN_PROMPT_SUCCESS"`
Streaming and non-streaming models still work. Can cancel, it'll end, etc
https://github.com/lastmile-ai/aiconfig/assets/151060367/cf29ee99-9ede-4c5e-99a7-a7f7816adfe1
---
Stack …
> Implement STREAM_AICONFIG_CHUNK action

- python/src/aiconfig/editor/client/src/LocalEditor.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/server/server.py
Minor nits to cancellation error message
Put the prompt name in quotes. Also specifying that we're resetting outputs only, not the entire prompt or AIConfig. Also refreshed the AIConfig to make sure that changes are propagated.
I also noticed that if you don't refresh the text lingers there. This gets fixed automatically with the next PR in diff stack!
Before
After
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/921).
* #928
* #926
* #925
* #924
* #922
* __->__ #921
* #920
* #919
* #918
* #917
> Minor nits to cancellation error message

- python/src/aiconfig/editor/client/src/LocalEditor.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/server/server.py
Rename RUN_PROMPT to RUN_PROMPT_START
Keeping diff small and easy to review. With last diff, we removed out the ambiguity of when `RUN_PROMPT` is called, and now it's only ever called at the beginning of run prompt flow
Same as before (exact same videos), simple re-naming, no functional changes
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/925).
* #928
* #926
* __->__ #925
* #924
* #922
* #921
* #920
* #919
* #918
* #917
> Rename RUN_PROMPT to RUN_PROMPT_START

- python/src/aiconfig/editor/client/src/LocalEditor.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/aiconfigReducer.ts
- python/src/aiconfig/editor/client/src/reducers/actions.ts
- python/src/aiconfig/editor/client/src/reducers/aiconfigReducer.ts
- python/src/aiconfig/editor/server/server.py
Split Action Types and AIConfigReducer into it's own folder
I just feel having the action type definitions vs. the reducer implementation make this a lot easier to read. You can now have file side by side instead of having to jump back and forth across the same one. I also merged the run commands together under the `RunPromptAction` type to make things cleaner as well. This will make it easier next diff once I merge logic together for the run prompts
I also cleaned up the `UPDATE_PROMPT_INPUT` implementation inside of the aiConfigReducer because it wasn't passing in the correct input type anyways, so now that's cleaner too.
Everything works the same as before
https://github.com/lastmile-ai/aiconfig/assets/151060367/46c11941-c055-4307-99b2-3cd6202b78cb
--- …
> Split Action Types and AIConfigReducer into it's own folder

- python/src/aiconfig/__init__.py
- python/src/aiconfig/schema.py
- typescript/types.ts
[rfc][sdk] 1/n Standardize Input Schema - Input Attachment Data
Starting point of standardizing Input Schema for prompts
This diff introduces the type `AttachmentDataWithStringValue` to python and typescript sdk which will allow attachments to have structure as well as validation in python (pydantic validation).
> [rfc][sdk] 1/n Standardize Input Schema - Input Attachment Data

- python/src/aiconfig/editor/client/src/LocalEditor.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/contexts/AIConfigContext.tsx
[ez] Rename logEvent handler to logEventHandler
There's the type `logEvent` and the handler `logEvent` which can be confusing. Having this as it's own separate variable name names it clear that this is a handler, not a type.
no functional changes
> [ez] Rename logEvent handler to logEventHandler

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/prompt/AddPromptButton.tsx
Center the Add Prompt button
This took so long, literally this was the "how do you center a div" meme. I also did a few others things, mainly:
1. Make the entire grey-out hover area clickable and opening the menu, not simply the space around the `+` icon
2. Made the very first top `+` menu item hover the entire width. Before it would only have greyed hover over area around the `+` icon
There were basically 2 main parts that took me a while:
1. Had to update `display` from `"inline-block"` to `"flex"`. After this you don't even need to set `width: "100%"`, but I just kept it there anyways to make it obvious.
2. Even after doing that, the menu itself wasn't spread to 100%, and would only be wrapped around the `+` icon. The `Menu` component in mantine does not take regular styles …
> Center the Add Prompt button

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
[3/n] Read-only mode: Connect context to Add Prompt button
For now I'm just returning empty component. It looks a bit weird to me right now, but I think that's becuase the background color of the prompt cells should be darker than the background color of the notebook itself. Once that's fixed it'll look better I think. From the Figma: https://www.figma.com/file/7YVa6KpEDgptj8DiAc5BaU/AiConfig-Editor?type=design&node-id=271-4785&mode=design
Change `readOnly = false` to `readOnly = true`
Before
After
Before
After
> [3/n] Read-only mode: Connect context to Add Prompt button

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
[4/n] Read-only mode:  Remove Clear Output and Save buttons
TSIA
Change `readOnly = false` to `readOnly = true`
Before
After
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/936).
* __->__ #936
* #935
> [4/n] Read-only mode:  Remove Clear Output and Save buttons

- typescript/types.ts
[easy] [ts][sdk] export `AttachmentDataWithStringValue` type
`AttachmentDataWithStringValue` was created in #929
Wasn't exported. This diff exports it
> [easy] [ts][sdk] export `AttachmentDataWithStringValue` type

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/prompt/AddPromptButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/ModelSelector.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/hooks/useLoadModels.ts
Make the `callbacks` prop optional so that we don't need to pass a huge callbacks object with no-ops in readonly mode (can just do <AIConfig config={config} readOnly/>)
With callbacks prop, make sure all actions work
Without callbacks prop, ensure all callback related options are just no-op'd and don't send any requests
> [editor] Make AIConfigEditor callbacks Prop Optional

- python/requirements.txt
- python/src/aiconfig/eval/common.py
- python/src/aiconfig/eval/lib.py
- python/src/aiconfig/scripts/run_aiconfig.py
- python/tests/test_eval.py
[AIC-py][eval][1/n] generalize to take params dict input
We should be able to take an arbitrary params dict, not just a single input
associated with "{{the_query}}".
This generalizes UserTestSuiteWithInputs to allow a dict, and makes the necessary
internal changes to respect that (while being near-perfectly type safe :D)
lib: unit tests. The tests are pretty thorough, checking dynamic types that are
not checkable statically, and fuzzy testing the possible inputs using
the hypothesis library.
This also affects this script which is not e2e tested, so I did that manually.
run_aiconfig script:
`python -m 'aiconfig.scripts.run_aiconfig' travel_aiconfig_test_suite_settings.json food`
...
```
1. Savour culinary delights at Chelsea Market.
2. Sample diverse food at Smorgasburg weekend market.
3. …
```
> [AIC-py][eval][1/n] generalize to take params dict input

- python/src/aiconfig/editor/client/src/LocalEditor.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/ConditionalWrapper.tsx
- python/src/aiconfig/editor/client/src/shared/types.ts
- python/src/aiconfig/editor/client/src/themes/AIConfigEditorThemeProvider.tsx
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
- python/src/aiconfig/editor/client/src/themes/LocalTheme.ts
Add an optional 'mode' prop to the AIConfigEditor to use for telemetry and predefined styling (for 'local' editor, 'gradio' or 'vscode') which can be used when we package the editor for external use. I decided to make this optional so that we can support custom styles for external deployments (we can document the classes to use), rather than defaulting to 'local', but we can revisit if we don't want to support that level of customizability.
> Add 'mode' Prop to AIConfigEditor & Map to Associated Theme

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/prompt/AddPromptButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptsContainer.tsx
[editor] Move PromptsContainer to its Own Component to Prevent Future useStyles Issues
See #953 for additional context, but the gist is that this is functionally a no-op, but moving the PromptsContainer div into a component so that useStyles can be used with the correct theme overrides if we do update the styles to leverage theme overrides in the future, rather than re-debugging why it doesn't work from within AIConfigEditor.
- Tested functionality of all actions/callbacks within the editor to make sure everything works as expected
- Ensure the 'sm' styles are applied when my browser window is small:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/953).
* __->__ #953
* #952
> [editor] Move PromptsContainer to its Own Component to Prevent Future useStyles Issues

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/prompt/AddPromptButton.tsx
I noticed with the refactor for 'mode' with theme, that the hover styles aren't properly applied to the div around AddPromptButton. 
The reason for this is because we're styling with `useStyles` at the top of AIConfig, which means the styles object is constructed immediately on import of AIConfigEditor. At that point, the `theme` passed into the styles function is the default mantine theme, which takes colorScheme from the system settings. For local editor we are hard-coding colorScheme to dark for now, but that happens within the MantineProvider that is rendered by the AIConfigEditor (so, excludes AIConfigEditor). To fix, we can just move the applicable styles to the AddPromptButton, which is cleaner anyway since they applied to a duplicated 'div' around the button.
A couple notes:
- …
> [editor] Fix AddPromptRow Hover Style

- python/src/aiconfig/editor/client/src/LocalEditor.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/shared/types.ts
[editor] add telemetry for more events
As discussed offline, we want to enable telemetry in the local editor for the following events:
- RUN_PROMPT_START
- RUN_PROMPT_CANCEL
- RUN_PROMPT_ERROR
- RUN_PROMPT_SUCCESS
This diff implements the logging telemetry for those events.
- Add mode "local" to all telemetry sent from local editor in prod mode
- Send telemetry log events after dispatching rather than before, so that the client render action gets called first.
- - This technically shouldn't matter since these are all async calls.
- Note: This only implements logging for Local Editor. Next up is to add the datadog initialization to Gradio Workbook
1. yarn build -> run editor in 'prod' mode
2. run prompt, cancel, rerun to success. Check telemetry sent to datadog. …
> [editor] add telemetry for more events

- cookbooks/Gradio/huggingface.aiconfig.json
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/automatic_speech_recognition.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/image_2_text.py
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/attachments/AttachmentContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/attachments/AttachmentUploader.tsx
[editor] 4/n refactor input attachments to use new input data type
- update renderer to acknowledge new type
- On New attachment, update aiconfig to use new values to input data when new file is updated
- updated Gradio AIConfig by removing and adding files.
Note: This diff doesn't test or change base64 functionality but should techncially be possible. <audio> HTML taglets you pass base64 source. Unsure about image
1. edit config
2. reupload files & run. note: the incorrect rendering is due to the old aiconfig with the now incorrect input attachment data type
https://github.com/lastmile-ai/aiconfig/assets/141073967/eff42748-e3e6-48df-b90b-34bac4e997c4
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pul …
> [editor] 4/n refactor input attachments to use new input data type

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/automatic_speech_recognition.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/image_2_text.py
[extensions] 3\n Image 2 text
With a new input attachment type `AttachmentDataWithStringValue` defined, This diff updates the HF image to text Model parser to validate input is in the expected form/type.
Also made some updates to to make input attachment validation clearer.
Sapling removed the dependency pr. Depends on
#929
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/940).
* #944
* __->__ #940
* #932
> [extensions] 3\n Image 2 text

- python/src/aiconfig/editor/client/src/components/ParametersRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptsContainer.tsx
7/n Read-only mode: Prompt Menu (Left side triple dots)
- Add ReadOnly prop to the Prompt Menu (triple dots on the left side of the component)
1. Pass readOnly=True prop in `AIConfigEditor`
| readOnly={false}  | readOnly={true} |
| <img width="1172" alt="Screenshot 2024-01-18 at 1 24 10 PM" src="https://github.com/lastmile-ai/aiconfig/assets/141073967/86842c3d-b864-45ef-bce4-77435c5d0518">  | <img width="1127" alt="Screenshot 2024-01-18 at 1 25 33 PM" src="https://github.com/lastmile-ai/aiconfig/assets/141073967/38c9ef53-dfe8-4eb8-b7f2-5f87adf2a708"> |
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/961).
* #962
* __->__ #961
* #957
> 7/n Read-only mode: Prompt Menu (Left side triple dots)

- python/src/aiconfig/editor/client/src/components/ParametersRenderer.tsx
[easy][editor][client] 6/n Read-only mode: Global Parameters
- refactor `isReadonly` -> `readOnly` inside `ParametersRenderer.tsx`
- useState() to get readOnly bool
1. Pass readOnly=True prop in `AIConfigEditor`
| readOnly={false}  | readOnly={true} |
| <img width="981" alt="Screenshot 2024-01-18 at 11 29 08 AM" src="https://github.com/lastmile-ai/aiconfig/assets/141073967/07747d6a-37d1-4b00-a5fb-ae8475c19044">  | <img width="1044" alt="Screenshot 2024-01-18 at 11 32 28 AM" src="https://github.com/lastmile-ai/aiconfig/assets/141073967/673abdb3-7048-444c-9ba2-8ad746181478"> |
Built ontop of #939
#961 is next on the stack
--- …
> [easy][editor][client] 6/n Read-only mode: Global Parameters

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/image_2_text.py
Fix ambiguous Image type errors
Reference: Reference: https://stackoverflow.com/questions/58236138/pil-and-python-static-typing
When we do
```python
from PIL import Image
```
this is the model PIL.Image. If we want the class (and type), we have to do Image.Image. I just used aliases to make things easier to read.
This wasn't erroring before because Python has fake types, and it only errored on Pydantic when we tried to create Gradio class. Probalby also tons of other runtime issues we have that Python hasn't uncovered, smh
Python itself has no functional changes, just errors for pydantic which has strict typing checks. I'm going to go through Ryan's setup for gradio workspace and make sure it works, but think we can just land this for now to get unblocked
> Fix ambiguous Image type errors

- python/src/aiconfig/editor/client/src/themes/AIConfigEditorThemeProvider.tsx
The theme is always light by default unless passing in a colorScheme. We need to use this mantine hook `useColorScheme` which does the media query for system (browser) settings, same as in lastmile.
- Ensure local editor remains the same for branding, regardless of system color theme:
- Ensure gradio properly reflects system theme now:
> [editor] Default Theme ColorScheme to Match User System Settings

- python/src/aiconfig/editor/client/src/reducers/aiconfigReducer.ts
Currently, if you update the model for a prompt all settings are wiped out on the client. On the server (and in sdk), we actually retain all of the settings when the model name changes.
This PR updates the client to match that logic, retaining the existing prompt model settings.
https://github.com/lastmile-ai/aiconfig/assets/5060851/2c0f9c51-1f30-4247-98d4-0caaa59f6de9
In the future, both server/sdk and client should leverage the prompt schemas for the models to retain only the supported settings in order to prevent errors (example client code below for reference)
```
case "UPDATE_PROMPT_MODEL": {
return reduceReplacePrompt(dirtyState, action.id, (prompt) => {
// When updating the model for a prompt, retain existing settings that
// are supported by the new model (if a schema exists for …
```
> Fix UPDATE_MODEL action to retain settings

- aiconfig-docs/docs/editor.md
- aiconfig-docs/docs/getting-started.md
- python/src/aiconfig/editor/client/src/components/GlobalParametersContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptActionBar.tsx
Our documentation and editor seems to go back and forth between variables and parameters, sometimes both. Standardizing on one: `parameters` for now, but we can swap to `variables`.
> Text edits for Variables -> Parameters

- python/src/aiconfig/editor/client/src/components/JSONEditorToggleButton.tsx
- python/src/aiconfig/editor/client/src/components/JSONRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputConfigRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/attachments/AttachmentContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/attachments/AttachmentUploader.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputAttachmentsSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputDataSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
8/n Read-only mode: Input rendering
Attempted to add read-only functionality wherever applicable to input renderings.
| ![image1](https://github.com/lastmile-ai/aiconfig/assets/141073967/31405238-bbd1-42c0-a5fc-58102fe05021) | ![image2](https://github.com/lastmile-ai/aiconfig/assets/141073967/bb8d6543-25d0-4b61-826b-ded9ddab4295) |
| --- | --- |
| ![image1](https://github.com/lastmile-ai/aiconfig/assets/141073967/dcec6c8b-fbe8-4aea-b2f1-f55153866385) | ![image2](https://github.com/lastmile-ai/aiconfig/assets/141073967/8e90c287-3304-484e-8831-496b0f5cd2a8) |
| ![image1](https://github.com/lastmile-ai/aiconfig/assets/141073967/38e2fc27-bb39-4143-8dc1-67876110f1c6) | ![image2](https://github.com/lastmile-ai/aiconfig/assets/141073967/34d4db13-74b5-4617-bb5c-5c851e41afb8) |
| …
> 8/n Read-only mode: Input rendering

- python/src/aiconfig/Config.py
Re-arrange model ordering
Great idea by Ankush. Having all these chat-gpt variants is annoying at the top of the editor. Have the cooler ones at the top instead!!!
Way better ordering now
> Re-arrange model ordering

- extensions/HuggingFace/python/requirements.txt
- extensions/LLama-Guard/python/requirements.txt
- python/requirements.txt
Change typo in huggingface-hub imports, remove pinned deps from llama-guard
Got some issues before:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiconfig-extension-llama-guard 0.0.2 requires torch==2.1.0, but you have torch 2.1.2 which is incompatible.
aiconfig-extension-llama-guard 0.0.2 requires transformers==4.35.2, but you have transformers 4.36.2 which is incompatible.
```
Which are now fixed.
Also the `huggingface_hub` lib package uses hypen, not underscore: https://pypi.org/project/huggingface-hub/
Ran the HuggingFace cookbook:
```bash
rossdancraig@Rossdans-MBP aiconfig % cd /Users/rossdancraig/Projects/aiconfig/cookbooks/HuggingFace/python …
```
> Change typo in huggingface-hub imports, remove pinned deps from llama-guard

- python/src/aiconfig/default_parsers/openai.py
- python/tests/parsers/test_openai_util.py
- python/tests/test_run_config.py
[sdk][python] Refactor OpenAI model paser to use client abstraction
- Refactor OpenAI Model parser to use an OpenAI Client construct instead of the weird default base client in the OpenAI Library
- - This change will make it easier to reuse this model parser with other model providers that are compatible with the OpenAI Library/client (such as OpenAI azure)
- Marked 2 tests as xfail because they currently break with this change and need to be updated to not break with client changes
TODO: investigate how to update mock tests to handle a client.
1. Run streaming in local editor with gpt-4
https://github.com/lastmile-ai/aiconfig/assets/141073967/2133a8cd-1c6f-4816-9286-1556272363a6
2. Validate Function Calling Notebook
> [sdk][python] Refactor OpenAI model paser to use client abstraction

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/__init__.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/image_2_text.py
[hf inference] Implement HuggingFaceImage2TextRemoteInference
Implement `HuggingFaceImage2TextRemoteInference` for running hf image-to-text models via inference API for gradio.  The api takes in an image of various supported types: `Union[str, Path, bytes, BinaryIO]`. For now, just implementing support for path and uri since it's not needed for gradio and my python skills aren't great.
Build/install the local hugging face package with these changes
```
(hf) ryanholinshead@Ryans-MacBook-Pro aiconfig % cd extensions/HuggingFace
pip3 install build && cd python && python -m build && pip3 install dist/*.whl
pip3 install -e .
```
Register these parsers in `/Users/ryanholinshead/Projects/aiconfig/cookbooks/Gradio/hf_model_parsers.py` then run aiconfig editor with the local parsers and gradio …
> [hf inference] Implement HuggingFaceImage2TextRemoteInference

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/__init__.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/automatic_speech_recognition.py
[hf inference] ASR remote inference model parser impl
Implementation of the HuggingFaceAutomaticSpeechRecognition Model parser using the inference endpoint to run inference. Python API takes in bytes as well as path, skip binary for now.
Very similar to #1018
1. Temporarily add model parser to Gradio Cookbook model parser registry.
```
asr = HuggingFaceAutomaticSpeechRecognitionRemoteInference()
AIConfigRuntime.register_model_parser(
asr, asr.id()
)
```
2. run AIConfig Edit on Gradio example
`python3 -m 'aiconfig.scripts.aiconfig_cli' edit --aiconfig-path=cookbooks/Gradio/huggingface.aiconfig.json --parsers-module-path=cookbooks/Gradio/hf_model_parsers.py --server-mode=debug_servers`
> [hf inference] ASR remote inference model parser impl

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceAutomaticSpeechRecognitionRemoteInferencePromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
[hf inference] Prompt Schema ASR
Prompt Schema for HuggingFaceAutomaticSpeechRecognition Model Parser using the inference endpoint
Surprisingly, the python api only supports one parameter: the model.
1. Temporarily add model parser to Gradio Cookbook model parser registry.
```
asr = HuggingFaceAutomaticSpeechRecognitionRemoteInference()
AIConfigRuntime.register_model_parser(
asr, asr.id()
)
```
2. run AIConfig Edit on Gradio example
`python3 -m 'aiconfig.scripts.aiconfig_cli' edit --aiconfig-path=cookbooks/Gradio/huggingface.aiconfig.json --parsers-module-path=cookbooks/Gradio/hf_model_parsers.py --server-mode=debug_servers`
> [hf inference] Prompt Schema ASR

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/SettingsPropertyRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/ModelSelector.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptName.tsx
- python/src/aiconfig/editor/client/src/components/property_controls/UnionPropertyControl.tsx
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
In Gradio, we'll register the remote model parsers with the task name and register local models to start. So, we need to have the prompt schema map from task name to the remote parser schemas:
https://github.com/lastmile-ai/aiconfig/assets/5060851/3cf7246c-58e2-42ca-9c61-ee9d5ffd644c
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1029).
* __->__ #1029
* #1028
* #1027
* #1026
> [editor] Support Task-based HF Model Names in Prompt Schema Mapping

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
If no save callback is provided to the editor (e.g. Gradio) we shouldn't show the save button at all
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1026).
* #1029
* #1028
* #1027
* __->__ #1026
> [editor][ez] Don't show Save button if no save callback provided

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/prompt/ModelSelector.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptName.tsx
Implement readonly state for the prompt name and model selector inputs. Just disabling the text inputs since there's no styling/markdown that we'd want to apply with the TextRenderer
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1027).
* #1029
* #1028
* __->__ #1027
* #1026
> [editor][ez] Readonly state for PromptName and ModelSelector

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/SettingsPropertyRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/ModelSelector.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptName.tsx
- python/src/aiconfig/editor/client/src/components/property_controls/UnionPropertyControl.tsx
Make sure each of the settings field renderers are disabled in readonly state:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1028).
* #1029
* __->__ #1028
* #1027
* #1026
> [editor] Readonly State for Prompt Model Settings Renderer

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
Share button [1/n]: Create button UI
Doesn't do anything when you click it now, but just setting up the UI and tooltip. Will add upload feature next PR
Run these commands from the `aiconfig` dir:
```bash
aiconfig_path  =./cookbooks/Gradio/huggingface.aiconfig.json
parsers_path=./cookbooks/Gradio/hf_model_parsers.py
aiconfig edit --aiconfig-path=$aiconfig_path --server-port=8080 --server-mode=debug_servers --parsers-module-path=$parsers_path
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1031).
* #1037
* #1035
* #1032
* __->__ #1031
> Share button [1/n]: Create button UI

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
Move !readOnly check to entire header grouping at top for all buttons
Doing this makes it easier to manage rather than gating each one individually
No functional changes
ReadOnly mode
Regular mode (with share button shown)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1032).
* #1037
* #1035
* __->__ #1032
* #1031
> Move !readOnly check to entire header grouping at top for all buttons

- python/src/aiconfig/default_parsers/gemini.py
[sdk][python] 1/n Gemini -> core sdk starting point
- This diff copy pastes the source code for the Gemini Model parser.
- - Removed the the auto register to model parser
- doesn't link with the sdk in any way. Just makes class importable. Trying to import this will break/throw.
- more to come on top
Taken from extensions/gemini/gemini.py.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/973).
* #1023
* #987
* #986
* __->__ #973
> [sdk][python] 1/n Gemini -> core sdk starting point

- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
Gradio components are rendered within an iframe in HF spaces. With the editorBackground minHeight currently set to 100vh, this makes the containing div's height expand outside the bounds of the iframe in gradio and result in an endless page.
To fix, just make the height 100% of the containing element (iframe in this case).
In styles.css in gradio-workbook, I set
```
div.editorBackground {
min-height: 400px;
height: 100%;
background-color: green
}
```
to override the `editorBackground` styles with higher specificity. Then, publish the component to load in the workspace:
https://github.com/lastmile-ai/aiconfig/assets/5060851/f436bb87-a0d8-4887-95c0-68839237feb3
Note that we can now see the bottom of the page, as well as the notifications! Note that notifications are relative to the page …
> Fix GradioWorkbook Height

- extensions/HuggingFace/python/README.md
- extensions/HuggingFace/python/pyproject.toml
[extensions] Update Public release of HuggingFace Extension 0.0.4 ->0.0.5
With the recent addition of the Inference Endpoint (Remote Inference) Model parsers, this extension is in need of a new public publish.
0.0.4 -> 0.0.5
https://pypi.org/project/aiconfig-extension-hugging-face/0.0.5/
> [extensions] Update Public release of HuggingFace Extension 0.0.4 ->0.0.5

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceAutomaticSpeechRecognitionRemoteInferencePromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceImage2TextRemoteInferencePromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceText2ImageRemoteInferencePromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceText2SpeechRemoteInferencePromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextGenerationRemoteInferencePromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextSummarizationRemoteInferencePromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextTranslationRemoteInferencePromptSchema.ts
Hardcode default models for HuggingFace Remote Inference schemas
HuggingFace Remote Inference Model parsers utilized the Remote Inference endpoint.
When a model is not provided, it uses a default model. For now, hardcode the default model into the prompt schema, such that the user sees the "default model". This will help improve user experience
Found the models by calling the Inference Endpoint API:
There probably is a way to do something similar in Typescript and such implement it in the schema.
Verify selecting the 7 tasks populates the model field
https://github.com/lastmile-ai/aiconfig/assets/141073967/69ed36f5-2259-41b9-a535-d0819bb91997
> [editor] Hardcode default models for HuggingFace Remote Inference schemas

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_generation.py
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/prompt/ModelSelector.tsx
- python/src/aiconfig/editor/client/src/contexts/AIConfigContext.tsx
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextGenerationRemoteInferencePromptSchema.ts
- python/src/aiconfig/editor/client/src/themes/AIConfigEditorThemeProvider.tsx
Per gradio dogfooding. The default value for max_new_tokens is set to 20 by the hugging face text_generation API. This isn't a good default limit for use in gradio workbooks, so set to a more reasonable 400. Note that we set the default in 2 places here:
1. In the PromptSchema, default is set to 400 to show in the UI what the default is. This default, if untouched, *does not* propagate to the parser since otherwise any default setting value in the schemas would be persisted to the config
2. In the parser implementation itself -- this is where the default is set/used for the run call. In the future once we have prompt schemas moved to the parser layer we can have a common process of grabbing all defaults from the schemas to use
- Ensure default is now 400 (and not persisted to config if …
> Default to 400 max_new_tokens for HF Text Generation Remote Inference Parser

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/prompt/ModelSelector.tsx
- python/src/aiconfig/editor/client/src/contexts/AIConfigContext.tsx
- python/src/aiconfig/editor/client/src/themes/AIConfigEditorThemeProvider.tsx
Set Model Selector Label to 'HuggingFace Task' for 'gradio' Mode
Per dogfood feedback, it's confusing for the model selector label and placeholder to say 'Model' while the parser is registered based on task name. As a temporary improvement, this PR uses 'HuggingFace Task" terminology instead of model. Long-term, once the model -> model parser mapping UX is available, we should undo this and have the model copy back in the selector.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1046).
* #1047
* __->__ #1046
> Set Model Selector Label to 'HuggingFace Task' for 'gradio' Mode

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/global/ShareButton.tsx
Share Button [7/n]: Display loading UI
Created a separate component for the shareButton to manage the `isLoading` state and show that in the UI
Rebase on then do: https://github.com/lastmile-ai/aiconfig/pull/1045
Go to `aiconfig/python/src/aiconfig/editor/client` and run this command:
```
rm -rf node_modules && yarn && yarn build
```
Then go to `aiconfig` dir and run this command:
```
aiconfig_path  =./cookbooks/Gradio/huggingface.aiconfig.json
parsers_path=./cookbooks/Gradio/hf_model_parsers.py
aiconfig edit --aiconfig-path=$aiconfig_path --server-port=8080 --server-mode=debug_servers --parsers-module-path=$parsers_path
```
No Error Testing
https://github.com/lastmile-ai/aiconfig/assets/151060367/1e9f4b90-a9e9-4c60-a813-afa2a46a1b5a
Error Testing …
> Share Button [7/n]: Display loading UI

- python/src/aiconfig/editor/client/src/components/global/ShareButton.tsx
Share Button [8/n] Show modal on UI click
Showing the modal after button  returns a URL. I'm pretty annoyed, wasn't able to get it:
1. Show up right beside the Share button
2. Have it look beautiful in the modal
3. Have the copy button be displayed on the right side (I was able to use position absolute, but now the label does not work and it's also not aligned with the padding for the X close button)
https://github.com/lastmile-ai/aiconfig/assets/151060367/9fba2b38-0602-4a92-b77a-2d8624d8fe34
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1049).
* __->__ #1049
* #1044
> Share Button [8/n] Show modal on UI click

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/shared/types.ts
- python/src/aiconfig/editor/client/src/themes/AIConfigEditorThemeProvider.tsx
In Gradio, the theme/colors for the UI can be specified as part of the user's HuggingFace account settings. That theme value is propagated through gradio custom components as a theme_mode='system' | 'dark' | 'light' value (system by default). Our aiconfig-editor code already dynamically changes colors for gradio theme based on system theme. However, it doesn't currently have a way to dynamically change based on HF theme settings. This PR adds a 'themeMode' prop to the AIConfigEditor with which root components can override the dark/light theme used by the editor.
With this landed, we'll then be able to pass the prop from the Gradio component and fix the HF space theme issues
https://github.com/lastmile-ai/aiconfig/assets/5060851/f6141e64-ea83-44e5-bc5c-60aa1997d16a
- In LocalEditor, set …
> [editor] Support ThemeMode Override

- python/src/aiconfig/util/params.py
[python] Update Parameterization to pull outputs regardless of input
Today parameterization will skip prompts if the input is not parameterizable. Instead, update to paramterize outputs even if the input is not parameterizable.
Typescript sdk already does something similar.
Run with HF Remote Inference models
> [python] Update Parameterization to pull outputs regardless of input

- python/requirements.txt
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/claude.py
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/ClaudeBedrockPromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
[editor] Claude Bedrock Prompt Schema
https://github.com/lastmile-ai/aiconfig/assets/141073967/29c1faa7-7d13-412f-8606-9ad556eb1c52
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1050).
* __->__ #1050
* #1039
> [editor] Claude Bedrock Prompt Schema

- python/requirements.txt
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/claude.py
[python] Claude Model Parser
Model Parser for Claude on AWS Bedrock
Claude on Bedrock can be called with the
- `anthropic_bedrock` python library
- AWS' `Boto3` Library
- Chose to use the `anthropic_bedrock` library because it has good abstractions and type hints
Claude on Bedrock only supports Text Completions, turn style [prompts are not supported](https://docs.anthropic.com/claude/reference/claude-on-amazon-bedrock#:~:text=Messages%20in%20Amazon%20Bedrock)
- Added Claude model parser as a core parser.
- added dependency on `anthropic_bedrock`
using prompt schema from diff ontop
https://github.com/lastmile-ai/aiconfig/assets/141073967/29c1faa7-7d13-412f-8606-9ad556eb1c52
--- …
> [python] Claude Model Parser

- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/openai.py
[fix] Update model parsers to config runtime on AIConfigRuntime.create() call
Pretty good bug fix. If we define a model + model parser in a config and create it using `create()` instead of `load()` then this fails
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1078).
* __->__ #1078
* #1071
> [fix] Update model parsers to config runtime on AIConfigRuntime.create() call

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/ConfigNameDescription.tsx
- python/src/aiconfig/editor/client/src/components/GlobalParametersContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptsContainer.tsx
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
- python/src/aiconfig/editor/client/src/themes/LocalTheme.ts
With the change in #1077, update the title/description component to have the same left padding as the global parameters bar
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1081).
* __->__ #1081
* #1077
> [editor][rfc] Match Title Left Padding to Parameters Bar

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/GlobalParametersContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptsContainer.tsx
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
- python/src/aiconfig/editor/client/src/themes/LocalTheme.ts
[editor] Fix Padding on Parameters Bar
We were wrapping some components in a Container (which adds padding on the sides), but not the global parameters bar. This resulted in weird padding differences between the parameters and cells:
To fix, just remove these inner containers and instead wrap the entire editor contents in a container, plus fix the left margin on parameters container:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1077).
* #1081
* __->__ #1077
> [editor] Fix Padding on Parameters Bar

- python/src/aiconfig/Config.py
- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/editor/server/server_utils.py
- python/src/aiconfig/scripts/aiconfig_cli.py
- typescript/lib/config.ts
[4/n] Add 'start' command to aiconfig server and CLI
The current aiconfig CLI has an 'edit' command which starts both the frontend and backend servers, and also loads the aiconfig from disk.
In the same vein, this diff introduces a 'start' command that is used to just start the aiconfig server. This is used by the vscode extension to spawn a server when an aiconfig file is opened.
Unlike the 'edit' command, 'start':
* Doesn't load the aiconfig on server init. Instead, the /api/load_content endpoint is called to initialize.
* Doesn't search for open ports. The vscode client is responsible for finding an open port. This is because the client needs to be in control of the server lifecycle.
A small change that was also added to this diff: using `dotenv` to load an env file.
Test Plan:
* At …
> [4/n] Add 'start' command to aiconfig server and CLI

- python/src/aiconfig/Config.py
- typescript/lib/config.ts
[2/n] Add to_string method to AIConfigRuntime
Allow saving an AIConfigRuntime to a string by creating a `to_string` method that encapsulates the core business logic of the `save` method.
This is needed for VSCode extension (top of stack), which sends the state of the AIConfigRuntime to the editor as a string for management (the IDE is responsible for managing the document, and for saving it to disk).
Test Plan:
Tested out getting started ipynb with:
save JSON:
```
config = AIConfigRuntime.load('travel.aiconfig.json')
config.save('travel2.aiconfig.json')
```
save YAML:
```
config.save('travel2.aiconfig.yaml', mode="yaml")
```
to JSON string:
```
config_str = config.to_string()
print(config_str)
```
to YAML string:
```
config_yaml = config.to_string(mode="yaml")
print(config_yaml)
```
For …
> [2/n] Add to_string method to AIConfigRuntime

- python/src/aiconfig/Config.py
- typescript/lib/config.ts
[1/n] Add load_json and load_yaml methods to AIConfigRuntime
Allow loading an AIConfigRuntime from a string. There's already a `loadJSON` method in the TS SDK.
This is needed for VSCode extension (top of stack), which gets the state of the document from the editor (and which can contain unsaved changes that aren't present on the filesystem).
Test Plan:
Tested out getting started ipynb with:
load JSON:
```
config = AIConfigRuntime.load('travel.aiconfig.json')
```
load YAML:
```
config.save('travel.aiconfig.yaml', mode="yaml")
yaml_str = ""
with open('travel.aiconfig.yaml') as file:
yaml_str = file.read()
config = AIConfigRuntime.load_yaml(yaml_str)
```
Made sure config runtime is valid and tried `config.run`
--- …
> [1/n] Add load_json and load_yaml methods to AIConfigRuntime

- python/src/aiconfig/Config.py
- python/src/aiconfig/editor/server/server.py
- typescript/lib/config.ts
[3/n] Add /api/load_content and /api/to_string endpoints to aiconfig server
These endpoints allow loading an AIConfigRuntime from a string, and serializing it to a string. These will be used at the top of the stack by the VSCode extension.
Test Plan:
* At the top of the stack. Validated locally that these work.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1059).
* #1076
* #1060
* __->__ #1059
* #1058
* #1057
> [3/n] Add /api/load_content and /api/to_string endpoints to aiconfig server

- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
Fix Dark Theme in Gradio
Updating the gradio theme here for 2 style updates:
1. (Most important) Currently, the gradio workbook respects the dark/light theme of the system and/or hugging face space in most places. The exception is text/input (see title input and settings input):
The problem is that gradio itself has some "text" and "input" style selectors which use system theme instead of the hugging face themeMode. This is only a problem for "dark" theme, though.
To fix, we use more specific selectors which *do* take into account the themeMode here (made the changes in gradio-workbook styles.css and copied over here, checking they still work as intended):
https://github.com/lastmile-ai/aiconfig/assets/5060851/596bbd75-dc34-499f-9046-5edaac393d6e …
> Fix Dark Theme in Gradio

- python/src/aiconfig/editor/client/src/components/GlobalParametersContainer.tsx
- python/src/aiconfig/editor/client/src/components/ParametersRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptActionBar.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/model_settings/ModelSettingsRenderer.tsx
The + button for adding parameters currently floats over the parameter inputs (see recording in https://github.com/lastmile-ai/aiconfig/pull/1051). This PR fixes to have the + button in its own row below the inputs:
https://github.com/lastmile-ai/aiconfig/assets/5060851/4c061c2a-8b5d-458b-95e3-66badfc12c31
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1084).
* __->__ #1084
* #1051
> [editor] Fix + Parameter Button Placement

- python/src/aiconfig/editor/client/src/components/GlobalParametersContainer.tsx
- python/src/aiconfig/editor/client/src/components/ParametersRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptActionBar.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/model_settings/ModelSettingsRenderer.tsx
Dynamically Set Settings/Parameters Height to Match Prompt Input/Output Height
This PR implements dynamic max height for the model settings and parameters contents to be bounded by the height of the prompt input/output cell container. I wasn't able to get anything working with pure css so this implementation requires some javascript -- not ideal, due to potential perf hit, but it works.
The main idea is that:
1. In PromptContainer, use a ref for the element containing the input/outputs and calculate its height whenever input or outputs change (using debounce so we don't do this constantly). Set this height in an exported const map, mapped under the prompt id
2. In the PromptActionBar, set the max height of the contents to one of:
a) the calculated height minus height of surrounding action …
> Dynamically Set Settings/Parameters Height to Match Prompt Input/Output Height

- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
The # for the hex color was somehow left off
> [gradio] Add missing # for color

- python/tests/parsers/test_openai_util.py
[python][easy] remove unused mock from serialize() tests
title. Big changes are just indentation.
Calling the default openai client with azure and non-azure openai credentials throws.
> [python][easy] remove unused mock from serialize() tests

- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
In gradio, we'll surface a way for users to use the local model parsers we've created. When they do that, we want the names to be closer to the task name instead of the parser class name. We need to update the promptUtils so that the PromptSchemas are correct for those names.
- Updated hf parser registry to
```
automatic_speech_recognition = (
HuggingFaceAutomaticSpeechRecognitionTransformer()
)
AIConfigRuntime.register_model_parser(
automatic_speech_recognition, "Automatic Speech Recognition (Local)"
)
image_to_text = HuggingFaceImage2TextTransformer()
AIConfigRuntime.register_model_parser(
image_to_text, "Image-to-Text (Local)"
)
text_to_image = HuggingFaceText2ImageDiffusor()
AIConfigRuntime.register_model_parser(
text_to_image, "Text-to-Image (Local)"
)
text_to_speech = …
```
> Support Prompt Schemas for Local Models with Task Names

- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
[gradio] Move Styles into GradioTheme
Ok, this is a long stack of incremental changes to hopefully get gradio styles to look decent / match intended GradioTheme styles once and for all.
This PR moves the styles from gradio's styles.css into the theme so that we can hopefully remove the styles.css in gradio. Note that we nest them under the `div.editorBackground` (meaning, they apply to any elements with those classes and which are also descendants of the div with editorBackground class). This should ensure a high specificity on their selectors.
Check that the buttons have the correct styles:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1095).
* #1109
* #1105
* #1104
* #1103
* #1102
* #1101
* …
> [gradio] Move Styles into GradioTheme

- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
[gradio] Use Function/Return Instead of Inline Theme Object
This is a no-op, just changing `globalStyles: (theme) => { }` into a function that explicitly returns an object, instead of inline returning the object. This will be used in the next PR where we create a variable for use in the styles, outside of the returned object
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1096).
* #1109
* #1105
* #1104
* #1103
* #1102
* #1101
* #1100
* #1099
* #1098
* #1097
* __->__ #1096
* #1095
> [gradio] Use Function/Return Instead of Inline Theme Object

- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
[gradio] Use variable for input border color
Use a variable, `inputBorderColor` for referencing the border color for different inputs so that it can be used without manually repeating the colors based on theme everywhere we want to have the same border color
- Make sure the border for all the inputs are correct (note title is focused so it's orange)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1097).
* #1109
* #1105
* #1104
* #1103
* #1102
* #1101
* #1100
* #1099
* #1098
* __->__ #1097
* #1096
* #1095
> [gradio] Use variable for input border color

- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
[gradio] Fix Classes Specificity
Many of the intended styles within the GradioTheme weren't being applied because gradio itself has classes on things with higher specificity. To fix, we should be able to enforce a higher specificity by having the classes/styles moved to being underneath div.editorBackground as descendants.
This now fixes the input/text areas in most places to match the intended background color (e.g. compare to instruction input in https://huggingface.co/spaces/internlm/internlm2-math-7b in dark mode -- they are the same background color now).
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1098).
* #1109
* #1105
* #1104
* #1103
* #1102
* #1101
* #1100
* #1099
* __->__ #1098
* …
> [gradio] Fix Classes Specificity

- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
[gradio] Fix Border Color for textarea in Settings
Similar to previous PR - fix the settings textarea to have proper border/background color to match other gradio spaces in dark mode:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1099).
* #1109
* #1105
* #1104
* #1103
* #1102
* #1101
* #1100
* __->__ #1099
* #1098
* #1097
* #1096
* #1095
> [gradio] Fix Border Color for textarea in Settings

- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputConfigRenderer.tsx
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
[editor] Add Prompt Label to Config Renderer
Inputs without a schema are currently missing the 'Prompt' label, so add it:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1100).
* #1109
* #1105
* #1104
* #1103
* #1102
* #1101
* __->__ #1100
* #1099
* #1098
* #1097
* #1096
* #1095
> [editor] Add Prompt Label to Config Renderer

- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputConfigRenderer.tsx
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
[editor][rfc] Only Show Outputs Section if There are Outputs
From some feedback, it's kind of weird / confusing / takes up valuable screen real estate to show an 'Outputs' section even if there are no outputs. Let's remove it:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1101).
* #1109
* #1105
* #1104
* #1103
* #1102
* __->__ #1101
* #1100
* #1099
* #1098
* #1097
* #1096
* #1095
> [editor][rfc] Only Show Outputs Section if There are Outputs

- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputConfigRenderer.tsx
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
[gradio] Fix Model Selector 'x' Button Style
The 'x' button is blue with blue highlight. Change to the proper color for the themes with no highlight.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1104).
* #1109
* #1105
* __->__ #1104
* #1103
* #1102
* #1101
* #1100
* #1099
* #1098
* #1097
* #1096
* #1095
> [gradio] Fix Model Selector 'x' Button Style

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
If no `save` callback is provided to the editor we shouldn't have the interval set up to autosave, and should not override the default CMD+S listener.
- Ensure CMD + S and autosave still work correctly
- Remove `save` from the callbacks passed to the editor and ensure CMD+S opens the default browser save again:
- Add console log in the effect to ensure no autosave is attempted
> [editor] Don't Try to Save if No Save Callback

- python/src/aiconfig/Config.py
- python/src/aiconfig/__init__.py
[ez] Export missing default model parsers
Now we can do `from aiconfig import ClaudeBedrockModelParser` for example. I also deleted the `hf.py` file since we now have `aiconfig_extension_hugging_face` for this
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1112).
* #1114
* __->__ #1112
> [ez] Export missing default model parsers

- python/src/aiconfig/editor/client/src/components/prompt/RunPromptButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/model_settings/ModelSettingsRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
When viewing the JSONRenderer for an input and swapping to a model with different input type (based on prompt schema), the error at the top is currently ambiguous: "Invalid input format for model. Toggle JSON editor to update."
This updates to explain how to reset the input / rendering:
https://github.com/lastmile-ai/aiconfig/assets/5060851/02fc09dd-0a3d-4f11-b636-0e8fd213fcf5
https://github.com/lastmile-ai/aiconfig/assets/5060851/4cd82c59-1728-46f7-a484-d40ff0a8a8bd
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1118).
* __->__ #1118
* #1117
> [editor] Clearer Input Type Error Messaging

- python/src/aiconfig/editor/client/src/components/prompt/RunPromptButton.tsx
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
[gradio] Fix readonly RunPromptButton Margin
Pretty annoying, but we have custom margin for the runPromptButton in gradio to account for the Prompt label being shown (by our gradio styles). But in readOnly we don't show the label, but kept the same margin. This ends up looking like this:
To fix, add .runPromptButtonReadOnly class to the button in readOnly and use it to set the margin in the theme:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1117).
* #1118
* __->__ #1117
> [gradio] Fix readonly RunPromptButton Margin

- python/src/aiconfig/editor/client/src/components/ConfigNameDescription.tsx
- python/src/aiconfig/editor/client/src/components/GlobalParametersContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/AddPromptButton.tsx
- python/src/aiconfig/editor/client/src/utils/constants.ts
[editor][ez] Fix AddPromptButton Width
Fix the AddPromptButton so that it no longer extends beyond the left of the prompts. Requires both adding left margin (to offset its left side to match start of the prompt cells) and removing the 100% width (to prevent the right side from extending outside of the container right padding). The width is still the full width of the prompts without explicitly setting width
> [editor][ez] Fix AddPromptButton Width

- python/src/aiconfig/editor/client/src/components/ConfigNameDescription.tsx
Add hoverContainer class to ConfigNameDescription
In https://github.com/lastmile-ai/aiconfig/pull/1121/files, the local hoverContainer class is modified to have vs code-specific styles. Instead, we can add the literal `hoverContainer` class to the elements so that our vscode theme can override the styles with greater specificity
- Make sure existing styles still work
- See class added:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1131).
* #1134
* #1133
* #1132
* __->__ #1131
> Add hoverContainer class to ConfigNameDescription

- python/src/aiconfig/editor/client/src/components/ConfigNameDescription.tsx
- python/src/aiconfig/editor/client/src/components/ParametersRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/AddPromptButton.tsx
Add addPromptRow class to AddPromptButton div
From https://github.com/lastmile-ai/aiconfig/pull/1121/files, the div had hard-coded styles to work in vs code. We can instead apply this `addPromptRow` class to support overriding in vs code theme.
- Make sure current styles still work
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1133).
* #1134
* __->__ #1133
* #1132
* #1131
> Add addPromptRow class to AddPromptButton div

- python/src/aiconfig/default_parsers/gemini.py
[easy] Set Gemini model parser id to the model id being used
title
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1139).
* __->__ #1139
* #1137
> [easy] Set Gemini model parser id to the model id being used

- python/src/aiconfig/default_parsers/gemini.py
[python] temporary Fix Gemini Event loop
Gemini api under the hood saves a reference to the async event loop. This messes with the local editor because we create a new event loop on api/run.
This diff reinitializes the "client" at the run step for the Gemini model parser. I put client in quotes because its not called a client but its analogous to the openai client abstraction.
Run a gemini prompt twice inside local editor.
Before:
After:
run twice, no event loop error
https://github.com/lastmile-ai/gradio-workbook/assets/141073967/39d1d4b2-90c5-4ee1-b1a4-bc35d8528d60
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1137).
* #1139
* __->__ #1137
> [python] temporary Fix Gemini Event loop

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/notifications/NotificationContext.tsx
- python/src/aiconfig/editor/client/src/components/notifications/NotificationProvider.tsx
- python/src/aiconfig/editor/client/src/hooks/useLoadModels.ts
[editor][4/4] Support showNotification Callback
With the previous PRs in place, we can now support the `showNotification` callback to our AIConfigEditor, leveraging it in the context for all `showNotification` calls if provided.
- In LocalEditor, passed in the following:
```
showNotification: (data) => {
window.alert(`Notification: ${JSON.stringify(data)}`);
},
```
Then ran and cancelled a prompt, ensuring the window alert is shown:
- Without passing in the function, ensure notifications use mantine as normal
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1130).
* __->__ #1130
* #1129
* #1128
* #1127
> [editor][4/4] Support showNotification Callback

- python/src/aiconfig/editor/client/src/components/notifications/NotificationContext.tsx
- python/src/aiconfig/editor/client/src/components/notifications/NotificationProvider.tsx
[editor][1/4] Set Up Notification Provider/Context
[editor][1/4] Set Up Notification Provider/Context
For the vs code extension, we want to leverage the vs code notification UX instead of mantine for showing notifications. To support that in a usable way, this PR stack sets up a Notification context which will propagate provided `showNotification` function to any components that request it from context. If there is no `showNotification` provided to the `AIConfigEditor` component we will default to the mantine `showNotification` function as usual.
This PR sets up the context, managing which `showNotification` function to call, and providing it through the context provider. The function takes in an `AIConfigEditorNotification` object, which includes the properties of mantine's …
> [editor][1/4] Set Up Notification Provider/Context

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/notifications/NotificationContext.tsx
- python/src/aiconfig/editor/client/src/components/notifications/NotificationProvider.tsx
[editor][2/4] Wrap AIConfigEditor with NotificationProvider
Wrap the `AIConfigEditor` component core with the `NotificationProvider`, wrapping both with the ThemeProvider to ensure notifications also have the proper theme applied. With the `NotificationProvider` in place, we also remove the mantine `Notifications` component from the AIConfigEditor (it's in the NotificationProvider now).
Ensure notifications still work
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1128).
* #1130
* #1129
* __->__ #1128
* #1127
> [editor][2/4] Wrap AIConfigEditor with NotificationProvider

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/notifications/NotificationContext.tsx
- python/src/aiconfig/editor/client/src/components/notifications/NotificationProvider.tsx
- python/src/aiconfig/editor/client/src/hooks/useLoadModels.ts
[editor][3/4] Update showNotification Calls to Use Context
Update all existing `showNotification` calls to use the `showNotification` from our new `NotificationContext`. By default, this is the same mantine `showNotification` implementation, just with our own mapping of notification type to mantine notification color.
- Ensure notifications still work
- Added onClose, onOpen, and autoClose: false to a notification to make sure they work as expected
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1129).
* #1130
* __->__ #1129
* #1128
* #1127
> [editor][3/4] Update showNotification Calls to Use Context

- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputConfigRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/PromptInputRenderer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
[editor] Support Running Prompt with Shift or CTRL + Enter
From https://github.com/lastmile-ai/aiconfig/pull/1121/files (and also general editor feedback), add support for executing text-input prompts with Shift+Enter (or CTRL+Enter)
https://github.com/lastmile-ai/aiconfig/assets/5060851/e103bf62-3edf-4a03-b2a8-09a7c1b1c9ce
Update: Show notification if trying to run a prompt while a prompt is already running:
- Ensure execution via button (and cancelation) work
- Ensure newlines can be added with enter (no shift/ctrl modifier)
- Ensure shift + enter and ctrl + enter run the prompt; ensure they do not run it when it's already running or when readOnly is true (though can't even edit then anyway)
- Ensure the same for a prompt with no schema (hf facebook/mms-tts-eng)
> [editor] Support Running Prompt with Shift or CTRL + Enter

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/DalleImageGenerationParserPromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
Update the prompt schemas to reflect the differing options between dall-e-2 and dall-e-3, per https://platform.openai.com/docs/api-reference/images/create
Made sure both models work with each option set to different values and with no settings specified
> [ez] Fix dall-e-2 and dall-e-3 Prompt Schemas

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
In vscode there's a white bar at the top of the config in some themes. The cause is a margin-top set on one of the Flex containers. 
We can achieve the same effect using padding-top instead, but will result in the background colour being correct since there's no empty space between the elements now.
Just make sure local editor UI looks the same with margin-top changed to padding-top:
> [vscode] Fix white bar at top of config

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/themes/AIConfigEditorThemeProvider.tsx
[editor] Support Explicit themeOverride for AIConfigEditor Component
From discussion earlier, the packaging devX for cleaning up the vscode theme for the vs code extension is still not in a good enough shape for easy iteration. To unblock Zak on theme work, we can support a themeOverride prop for the AIConfigEditor component and use it for overriding the theme instead of just using the static vs code theme defined. We can propagate the desired theme changes back to the static vs code theme afterwards.
Long-term this may be a nice prop to support anyway for external implementations to easily set the theme without requiring a bunch of css overrides to do so.
- Tested all permutations of existing mode, themeMode and system theme to ensure they all work correctly
- Explicitly set …
> [editor] Support Explicit themeOverride for AIConfigEditor Component

- python/src/aiconfig/editor/client/src/components/global/ShareButton.tsx
For rebranding gradio workbook to notebook, make sure the share button has correct copy
https://github.com/lastmile-ai/aiconfig/assets/5060851/338309b4-d33b-4230-a083-40b83d3fd36a
https://github.com/lastmile-ai/aiconfig/assets/5060851/ef919681-7f3e-4dc9-b5b2-844df98b6f6f
> [gradio] Update Share Copy to 'Notebook'

- vscode-extension/editor/package.json
- vscode-extension/editor/src/VSCodeEditor.tsx
- vscode-extension/editor/src/VSCodeTheme.ts
- vscode-extension/editor/yarn.lock
Bump the aiconfig-editor package to the most recent, which includes a bunch of UI fixes and functionality (open in text editor button, showNotification overrides). Crucially, this also includes the ability to explicitly override the theme with `themeOverride` prop. This will allow us to quickly iterate on the theme in this package without needing to worry about re-packaging the editor or figuring out the package linking stuff (for now). We can propagate the theme back to the static theme value once it's finalized.
For the themeOverride, I just copy/pasted the existing VSCodeTheme and made two minor modifications to editorBackground and global parametersContainer styles to work with the updated styles from the package itself.
> [vscode] Update aiconfig-editor Package to 0.1.21 & Override Theme

- extensions/HuggingFace/python/pyproject.toml
- extensions/llama/python/pyproject.toml
- python/pyproject.toml
Changing all pyproject `requires-python` to 3.10
We have some libraries like `TypeAlias`, `match-case`, and shorthand for Union types (`X | Y` instead of `Union[X, Y]` that require Python 3.10, as flagged by https://github.com/lastmile-ai/aiconfig/issues/1143. Full list of features added to 3.10 listed here: https://docs.python.org/3/whatsnew/3.10.html
We're just going to be consistent for all extensions (even the ones that don't use the 3.10 libraries).
I'm also going to re-publish and build the libraries (and includes this in the release notes!)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1146).
* #1147
* __->__ #1146
> Changing all pyproject `requires-python` to 3.10

- python/requirements.txt
[python] Pin Huggingface-hub dependency version
From #1156, not all versions of the python package huggingface-hub is compatible with the python sdk for AIConfig. We utilize the `InferenceClient` which was introduced sometime in 2023.
This diff pins it on > 0.20.3.
Current use of huggingface-hub is within the hugging face text generation model parser (core model parser).
I ran pip list on my computer to check which version I am developing with locally.
```
ankush@ap-mbp aiconfig % pip list | grep huggingface-hub
huggingface-hub                               0.20.3
```
> [python] Pin Huggingface-hub dependency version

- vscode-extension/editor/src/VSCodeEditor.tsx
- vscode-extension/src/aiConfigEditor.ts
Just familiarizing myself a bit with the vscode extension dev so picked up this quick task. We support custom notifications via `showNotification` callback in the `AIConfigEditor`. For VS Code, we can leverage this callback to use the vs code `showXMessage` api, for X in 'information', 'warning', 'error'.
A caveat with vscode notifications is that they are intended to be very succinct -- they only allow a message string (and they strip newlines). They allow showing additional 'details' string but ONLY for modal UX, which is a bad UX to use compared to the toasts. As a workaround, this PR adds a 'Details' button to the notification toast so that the user can click it and see the full details message in the output log.
https://github.com/lastmile-ai/aiconfig/assets/5060851/1b0536b4-536b-4c44 …
> [vscode] Use VS Code Notifications for showNotification

- vscode-extension/editor/src/VSCodeEditor.tsx
- vscode-extension/editor/src/utils/vscodeUtils.ts
- vscode-extension/src/aiConfigEditor.ts
- vscode-extension/src/util.ts
[vscode] Propagate themeMode for dark/light Theme Switching
VS Code themes have a `ColorThemeKind` which is one of Light, Dark, HighContrast (dark) or HighConstrastLight. We can leverage this to explicitly set the `themeMode` for the `AIConfigEditor`, which will be used for a few things:
- default mantine highlight and text backgrounds
- JSON editor dark/light theme colors
- as needed, can use the theme 'dark' or 'light' in our custom VSCode theme styles to override defaults
Make sure the JSON editor background as well as hover and title text background are correct when changing between themes
https://github.com/lastmile-ai/aiconfig/assets/5060851/195e3d30-e3db-479c-80f5-c3aaddaa6a35
> [vscode] Propagate themeMode for dark/light Theme Switching

- python/src/aiconfig/editor/client/src/themes/LocalTheme.ts
- python/src/aiconfig/editor/client/src/themes/VSCodeTheme.ts
- vscode-extension/editor/src/VSCodeTheme.ts
[editor][vscode][ez] Fix Padding on .ghost Input
The 4px padding makes long text overlapped by the 'x' button. Let's just use the default mantine padding (which already handles preventing overlap).
Next PR, will try to get the inputs set up nicely so that they fit longer text as well
VS Code
Local
> [editor][vscode][ez] Fix Padding on .ghost Input

- vscode-extension/editor/src/VSCodeEditor.tsx
Connect the button & event added in https://github.com/lastmile-ai/aiconfig/pull/1142/files with the callback to reopen the aiconfig editor webview as a text editor to interact with the underlying file directly. 
https://github.com/lastmile-ai/aiconfig/assets/5060851/76a25aa7-566f-491d-9949-b0f2f9ec3b1a
Note, this requires closing and reopening the file in order to re-initialize the aiconfig editor webview for the file. We could potentially add another command to handle this scenario (something like, "AIConfig: Open in Editor" which defaults to current file but shows others in current directory?)
> [vscode] Connect openInTextEditor Callback

- vscode-extension/editor/src/VSCodeTheme.ts
Most of the top buttons in the editor are using 'gradient' as their variant. We have the defaultGradient set to pink in the theme so changing it to match what the vscode button color should be.
> [vscode][ez] Fix Default Gradient Color (for Top Buttons)

- python/src/aiconfig/default_parsers/openai.py
[python]  serialize first assistant message as prompt
A user was building with AIConfig and was attempting to serialize a set of prompts with OpenAI.
Their messages array looked like this
```
{ "role": "assistant", "content": "Welcome, ask me anything." },
{ "role": "user", "content": "Say this is a test" },
...
```
Notice how the first message was an assistant message! Previously serializing this with config.serialize() was not supported.
This diff adds minimal support by allowing serialization of the first assistant message, and creates a prompt with an empty input, and the assistant message as the output.
Execute the user's test code. Also tested deserialize() and run() and they work as expected. No functional changes on that side
| <img width="546" alt="Screenshot 2024-02-07 at 11 42 …
> [python]  serialize first assistant message as prompt

- vscode-extension/package.json
- vscode-extension/python/requirements.txt
- vscode-extension/src/aiConfigEditor.ts
- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
remove hf extension from vscode dependencies
default installation of python fails when building sentencepiece. Remove it for now
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1167).
* __->__ #1167
* #1151
> remove hf extension from vscode dependencies

- vscode-extension/package.json
- vscode-extension/src/aiConfigEditor.ts
- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
[vscode] Use Python path for initialization
Downloading, Installing, and setting up python is not standardardized across users, windows, and mac os. Common differences include:
- python installed as python vs python3
- pip installed as pip vs pip3
To mitigate this problem, retrieve the user's python environment path. This is pulled through the python vscode extension, which is also introduced as a dependency to the vscode extension.
Now we don't have to worry about issues like python vs python3, and the user can select the python environment their vscode uses and AIConfig VSCode editor will also use that.
Note: this diff simply updates the invokation of python to use the right interpreter. Any other changes will come on top.
Notes while testing.
1. If the user installs python for the …
> [vscode] Use Python path for initialization

- vscode-extension/editor/src/VSCodeTheme.ts
[vscode][ez] Override Mantine Menu/Dropdown Styles with VSCode Styles
Update the menu and autoselect dropdowns to have correct theme styles.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1168).
* __->__ #1168
* #1166
* #1165
> [vscode][ez] Override Mantine Menu/Dropdown Styles with VSCode Styles

- vscode-extension/editor/src/VSCodeTheme.ts
[vscode][ez] Fix Propt Input Focus Outline Colour
Looks like this colour was missed when translating to vscode variables, so just use the same outline as other places.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1165).
* #1168
* #1166
* __->__ #1165
> [vscode][ez] Fix Propt Input Focus Outline Colour

- vscode-extension/editor/src/VSCodeTheme.ts
[vscode][ez] Override Mantine Default Input Colors with VSCode Theme
The default mantine input styles (background, color, focus outline, placeholder color) are ok in some cases but can be improved for all themes by using the appropriate theme variables.
https://github.com/lastmile-ai/aiconfig/assets/5060851/0efd596d-759e-4be6-b99c-01a1583d0ae0
https://github.com/lastmile-ai/aiconfig/assets/5060851/6baefd19-a3cf-491c-a2d4-12eae426087f
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1166).
* #1168
* __->__ #1166
* #1165
> [vscode][ez] Override Mantine Default Input Colors with VSCode Theme

- vscode-extension/package.json
- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
[editor] Add 'OpenAI Config File' Command
From discussion in https://github.com/lastmile-ai/aiconfig/pull/1162, it will be handy to have a command for opening an AIConfig file, especially in a couple cases:
1. If wanting to open a `.json` or `.yaml` config file, without the `.aiconfig.` sub-extension in the name
https://github.com/lastmile-ai/aiconfig/assets/5060851/9a851dce-ff45-4ef1-a627-5526fafb5f4b
2. After opening an AIConfig file in a text editor using the 'Open in Text Editor' button, re-opening the file with the AIConfig editor
https://github.com/lastmile-ai/aiconfig/assets/5060851/5c07d02a-233c-48cf-b8c9-234640bec81d
- Above scenarios work
- Also tested opening a json file that doesn't match config spec, the server errors and leaves an empty editor:
This is technically the case …
> [editor] Add 'OpenAI Config File' Command

- vscode-extension/python/requirements.txt
Pin vscode extension to 1.1.22 for aiconfig library
This will fix the google Gemini issue since we pinned it in https://github.com/lastmile-ai/aiconfig/pull/1172
> Pin vscode extension to 1.1.22 for aiconfig library

- vscode-extension/editor/src/VSCodeTheme.ts
Default hover background for the tabs is just the same dark color on all themes:
Fix to use vscode hover theme style:
https://github.com/lastmile-ai/aiconfig/assets/5060851/3ba4ff99-ec39-476f-917f-84fd1c6dce45
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1176).
* __->__ #1176
* #1175
* #1174
* #1173
> [vscode][ez] Override Mantine Tab Hover Background Color

- vscode-extension/editor/src/VSCodeTheme.ts
The thumb/slider for number settings is still using mantine's default blue:
Fix with vscode variables:
https://github.com/lastmile-ai/aiconfig/assets/5060851/de893ff7-4413-4da4-806a-0418daeb072c
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1173).
* #1176
* #1175
* #1174
* __->__ #1173
> [vscode][ez] Override Mantine thumb/slider Colors

- vscode-extension/editor/src/VSCodeTheme.ts
Tab bottom border in the side panel is still mantine's default blue so fix with vs code variable:
https://github.com/lastmile-ai/aiconfig/assets/5060851/fbaa469c-e373-45ea-a9aa-41e4744ac59c
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1174).
* #1176
* #1175
* __->__ #1174
* #1173
> [vscode][ez] Override Mantine Tab Border Bottom Color

- vscode-extension/editor/src/VSCodeTheme.ts
The checkbox background colour when checked is still mantine's default blue:
So fix with vscode variable:
https://github.com/lastmile-ai/aiconfig/assets/5060851/ea2030e7-5c2b-4907-ba22-531c373a02cd
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1175).
* #1176
* __->__ #1175
* #1174
* #1173
> [vscode][ez] Override Mantine Checkbox Checked Background Color

- vscode-extension/src/aiConfigEditor.ts
- vscode-extension/src/util.ts
[rfc] Prevent 'Error starting aiconfig server' notification when closing w/ unsaved changes
Currently, whenever an aiconfig editor webview is closed with unsaved changes, a notifcation shows at the bottom right:
This is caused by the following sequence of events:
1. changeDocumentSubscription happens with the "unsaved" changes being undone; this results in updating webview & server
2. server /load request is sent as a result
3. Another changeDocumentSubscription happens with no changed content (can probably just skip -- in all cases?)
4. Webview disposed, kills editor process
5. /load Request (STILL IN FLIGHT) fails, causing the notification
I spent some time but wasn't able to figure out why changeDocumentSubscription was happening (note -- NOT happening from the notifying dirty). Seems …
> [rfc] Prevent 'Error starting aiconfig server' notification when closing w/ unsaved changes

- vscode-extension/package.json
- vscode-extension/src/extension.ts
- vscode-extension/yarn.lock
[fix] Directly use `fetch` and `formData` in Share VSCode command instead of S3 client
I was never able to figure out how to use unsigned/anonymous credentials on TS. We use UNSIGNED in Gradio for Python backend here (https://github.com/lastmile-ai/gradio-workbook/blob/6911294e91612c2b97d9f77debe0a6cf1039c377/gradioworkbook/backend/gradio_notebook/events.py#L536), but can't ever get that equivalent to work, so just directly going to use post to a website link instead.
To test, I temporarily deleted my `.aws/credentials` file, and restarted my computer
Before
After
When you click the link, it opened this for me: https://lastmileai.dev/aiconfig/clsfea2nt0004pecrbk5rw5lp
> [fix] Directly use `fetch` and `formData` in Share VSCode command instead of S3 client

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/shared/types.ts
Adding `DOWNLOAD_BUTTON_CLICKED` and `SHARE_BUTTON_CLICKED` events to track usage, per gradio GTM doc. The event name follows pattern used by 'SAVE_BUTTON_CLICKED' already.
- In `LocalEditor`, pass through callbacks for share and download and update logging check to allow logging in dev
- Click the buttons and ensure they show up in datadog:
> [gradio] Add Log Events for Download & Share Button Clicks

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/automatic_speech_recognition.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_2_speech.py
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceAutomaticSpeechRecognitionRemoteInferencePromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceText2SpeechRemoteInferencePromptSchema.ts
Update the prompt schemas for ASR and TTS remote inference to match the defaults set in #1221 
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1222).
* __->__ #1222
* #1221
> Update Default Models in HF Prompt Schemas

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/automatic_speech_recognition.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_2_speech.py
The default model parsers for AST and TTS don't work:
- For ASR, `openai/whisper-large-v3` just throws 500 errors (even on the model card in HF)
- For TTS, `suno/bark` requires a HF PRO subscription to run
For now, we can just default to the next-best models for those tasks (based on like count) which support remote inference
- Build the hf extension following its README
- Update aiconfig/cookbooks/Gradio/aiconfig_model_registry.py to have the tts and asr remote parsers added (should register all remote ones by default there?)
```
(aiconfig) ryanholinshead@Ryans-MBP aiconfig % parsers_path=/Users/ryanholinshead/Projects/aiconfig/cookbooks/Gradio/aiconfig_model_registry.py
(aiconfig) ryanholinshead@Ryans-MBP aiconfig % aiconfig edit --server-mode=debug_servers …
```
> Set Working Default Models in HF Parsers

- cookbooks/Gradio/aiconfig_model_registry.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/automatic_speech_recognition.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_2_speech.py
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceAutomaticSpeechRecognitionRemoteInferencePromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceText2SpeechRemoteInferencePromptSchema.ts
Was getting annoyed of manually updating this to test the remote parsers each time. Just copied registration from what we do in Gradio and did a quick check a few worked
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1223).
* __->__ #1223
* #1222
* #1221
> Add Remote Inference Parsers to Gradio Cookbook Parser Registry

- python/pyproject.toml
- python/requirements.txt
bump lm utils to 0.23 for relaxed pydantic version
Issue: https://github.com/lastmile-ai/lastmile-utils/issues/32
LM utils PR: https://github.com/lastmile-ai/lastmile-utils/pull/33
LM utils 0.21 -> 0.22 is safe. It simply adds one utility function.
0.22 -> 0.23 relaxes the pydantic constraint, which should be safe but we should sanity check.
> bump lm utils to 0.23 for relaxed pydantic version

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/conversational.py
[extension]  2/n functionality for single turn prompting
Built out the conversational model parser for remote inference.
HF is in the process of revamping their libraries. Default behaviour of Converstaional is broken
Use the temporary fix is reccomended by HF https://github.com/huggingface/huggingface_hub/issues/2023#issuecomment-1935760040
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1228).
* #1229
* __->__ #1228
* #1227
> [extension]  2/n functionality for single turn prompting

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/global/DownloadButton.tsx
- python/src/aiconfig/editor/client/src/components/global/ShareButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptActionBar.tsx
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
Applying the minor UI tweaks proposed by Zak:
Mainly:
- Group share/download and use icons w/ tooltips (note, applying grouping style only when both are shown)
- Set min-height on top buttons and prompt name/model inputs to 36px
- Set min width of action bar to 32px when closed
> [gradio] Minor UI Tweaks for Clean Up

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/conversational.py
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceConversationalRemoteInferencePromptSchema.ts
[editor] Update HF conversationalprompt schema with parameters
Taken from https://huggingface.co/docs/api-inference/detailed_parameters#conversational-task
Skipped the options dictionary for now, they are not relevant to inference.
https://github.com/huggingface/huggingface_hub/assets/141073967/59039705-64cd-453f-a09c-090c7beef597
continued from: https://github.com/lastmile-ai/aiconfig/pull/1230
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1235).
* __->__ #1235
* #1233
> [editor] Update HF conversational prompt schema with parameters

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/conversational.py
[extension] fixes for conversational model parser
- set the right url for the default conversational model
- define method for construct output
- add "parameters" to chat completion params filter
Default model
Test with flan x5
> [extension] fixes for conversational model parser

- aiconfig-docs/docs/gradio-notebook.md
Changes in version 4.17 and 4.18 break our component so warn users to use 4.16 or lower for now
Also update 'space' to 'Space' in the local parsers section below
> [gradio][docs] Add Warning for using sdk_version 4.16.0

- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_summarization.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/text_translation.py
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextSummarizationRemoteInferencePromptSchema.ts
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceTextTranslationRemoteInferencePromptSchema.ts
The default translation and summarization models are broken for the remote inference client, raising a `KeyError` for `summary_text` and `translation_text`, respectively.
We can hardcode working defaults for these parsers for now, based on the top most "liked" models for the relevant tasks:
NOTE: This translation model requires specifying the target and source lang, otherwise it errors about them missing. I think this is fine for now, for a few reasons:
- it's better than current default of failing without clear error message and with no way to resolve (now, just add tgt and src lang)
- there are very few good translation models in the hub that actually work with inference API and those that do either require the src and tgt lang or are a poor UX/quality:
- if we use this translation …
> [gradio] Set Default Models for Summarization and Translation

- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
Apply style overrides for the checkbox background color to match the other buttons:
> [gradio] Fix Checkbox Style

- python/src/aiconfig/editor/client/src/components/prompt/TextRenderer.tsx
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
In gradio, the links in the description markdown have a couple issues:
- Color is overridden by gradio text color
- Clicking opens the link in the current iframe embed
To fix:
- override link / anchor color in gradio theme to set back to mantine's link colors
- update ReactMarkdown to open links in a new tab by default (applies to editor core as well)
- Make sure clicking opens in new tab and keeps current tab open to the left of the new tab
> [editor][gradio] Fix Markdown Links Target & Color

- python/src/aiconfig/editor/client/src/components/global/DownloadButton.tsx
- python/src/aiconfig/editor/client/src/components/global/ShareButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/prompt_outputs/PromptOutputsRenderer.tsx
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
[gradio] Fix Output List Padding
Gradio has specific output list padding and margin styles which override mantine's:
This causes ordered lists in outputs to extend outside the cell card padding:
We can fix by overriding with mantine's styles at higher specificity:
- Locally, editor output list looks the same on main and in this PR for local and gradio modes:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1251).
* __->__ #1251
* #1250
> [gradio] Fix Output List Padding

- python/src/aiconfig/editor/client/src/components/global/DownloadButton.tsx
- python/src/aiconfig/editor/client/src/components/global/ShareButton.tsx
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
[gradio] Fix Spinner Colors
The loading spinner on the run button, download and share buttons is not clearly visible in gradio right now, especially in light mode:
https://github.com/lastmile-ai/aiconfig/assets/5060851/a7204248-1a8a-4f3a-8d12-e553dd66c03d
To fix, we need to override the stroke for the svg that's used. Also, for running prompt button, updated to make the square in the runPromptButton fill with the gradio color instead of white.
Test in light & dark themeMode:
https://github.com/lastmile-ai/aiconfig/assets/5060851/489745c0-f5bb-4f17-8cfd-d817adc78c9b
https://github.com/lastmile-ai/aiconfig/assets/5060851/e37e543c-c43d-43f6-bf22-4bce4ea08644
--- …
> [gradio] Fix Spinner Colors

- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
Turns out we need to explicitly override padding and margin and not the block/inline start and end:
https://github.com/lastmile-ai/aiconfig/assets/5060851/3a20c384-7fab-494d-b9ee-a9173ad5ca28
> [gradio] Actually Fix ol Padding & Margin

- python/src/aiconfig/editor/client/src/components/prompt/PromptActionBar.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/model_settings/ModelSettingsRenderer.tsx
Currently, the model settings state is retained when changing models in the selector instead of updating to the new defaults:
https://github.com/lastmile-ai/aiconfig/assets/5060851/1c38d6df-96d8-46c1-b164-65e9c16241b8
To fix, we can force the model settings renderer to remount when the prompt model value changes by passing the model name as the `key` prop to the component. Specifically, this handles the scenario outlined in discussion here: https://github.com/lastmile-ai/aiconfig/pull/1256#discussion_r1491743289
https://github.com/lastmile-ai/aiconfig/assets/5060851/60263416-dbb0-41d1-947b-be679e80bf75
> [editor] Remount Model Settings Renderer on Model Change

- vscode-extension/package.json
Following the example outlined in https://github.com/microsoft/vscode/issues/138525#issuecomment-1847679100 to make the view for diff-related views (noted by `git`, `gitlens`, `sapling-diff` as schema at the start of the document URI) fall back to the default diff view
https://github.com/lastmile-ai/aiconfig/assets/5060851/258d5ae6-d5f8-497d-8a99-c44e9be579c1
> [vscode][ez] Use Default Diff View for .aiconfig.json/yaml Diff View

- vscode-extension/package.json
- vscode-extension/src/extension.ts
[vscode] Add category to commands instead of hardcoding "AIConfig" in title
Just cleaner, noticed it when reading through the docs
Also I removed the async logic from the showWelcome page because that was originally to open webview but now with Markdown it's just simple synchronous function
I also tried changing the command to sanity check that chagnes were indeed made, and not just cached from previous values or something
> [vscode] Add category to commands instead of hardcoding "AIConfig" in title

- vscode-extension/editor/src/VSCodeEditor.tsx
- vscode-extension/editor/src/utils/vscodeUtils.ts
- vscode-extension/src/aiConfigEditor.ts
[editor][rfc] Default to readOnly Until Server Is Working
[editor][rfc] Default to readOnly Until Server Is Working
When opening an aiconfig file, we currently open the webview with editable editor component before the server has successfully loaded the config content into state, then show an error message, `"Failed to start aiconfig server. You can view the aiconfig but cannot modify it."` with Retry button. A couple issues with the current state:
- Retry button is only shown once and can't retry again afterwards if it fails again
- Having editable state while the server isn't ready means the user can (confusingly) modify the UI, causing error messages and the changes NOT being reflected in the actual document (because we push to the document from the server) …
> [editor][rfc] Default to readOnly Until Server Is Working

- vscode-extension/src/aiConfigEditor.ts
Apparently, `changeDocumentSubscription` event is also fired even when no `contentChanges` exist. When trying to update aiconfig-editor package to support updating aiconfig state via param (from https://github.com/lastmile-ai/aiconfig/pull/1261), this fact causes a bug where the current input is remounted as I'm typing due to the `changeDocumentSubscription` event being called with no changes. We can fix this by preventing this scenario from updating the webview with duplicate content (which would be serialized as a new, but identical, aiconfig object being passed to the AIConfigEditor component).
This is just 1 of 3 possible ways to resolve this issue. The others are:
2. continue updating webview in this case, but do a deep equality check on the client and no-op instead of setting the …
> [editor][rfc] Skip Updating Webview if there are No Content Changes

- vscode-extension/editor/package.json
- vscode-extension/editor/yarn.lock
Bump the version to now have the changes from #1261. Ensure the editor works. Also, undo/redo now works:
https://github.com/lastmile-ai/aiconfig/assets/5060851/6abb5f4c-072e-491b-84ba-769ebbcd2e42
> [editor] Bump aiconfig-editor Version to 0.2.0

- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
[vscode installation] 1/n Python version validation
Add a helper method to validate the python interpreter version. Simply throws an error on a bad version. Notification dialog in diff on top.
Align's with Python AIConfig's version requirement of python3.10 and higher
Select a python interpreter 3.9, which is less than aiconfig's requirement version of 3.10.
https://github.com/lastmile-ai/aiconfig/assets/141073967/4cfcb153-50aa-40fb-9764-54e964d4b1b8
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1262).
* #1265
* __->__ #1262
> [vscode installation] 1/n Python version validation

- vscode-extension/src/extension.ts
[vscode][2/n] Setup Env Variables: Define env path
Opening a window for user to enter in an `.env` path. Using the home dir for now, but can change to workspace if you want, not a big deal.
Next diffs will implement a static file template and use that when env path doesn't exist. Diff after that I'll deal with existing env path situation
https://github.com/lastmile-ai/aiconfig/assets/151060367/cceadc3a-cd20-4164-b8b2-c8d11b36b5bb
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1280).
* #1284
* #1283
* __->__ #1280
> [vscode][2/n] Setup Env Variables: Define env path

- vscode-extension/src/extension.ts
- vscode-extension/static/env_template.env
[vscode][3/n] Setup Env Variables: Use env template file for new files
If the file does not exist, created a template file with some helper text to help guide people on how to set their environment variables.
Next PR I will handle the use case for when the env file already exists
https://github.com/lastmile-ai/aiconfig/assets/151060367/4608833c-d64f-4906-a7ed-94af12174c6d
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1283).
* #1284
* __->__ #1283
* #1280
> [vscode][3/n] Setup Env Variables: Use env template file for new files

- vscode-extension/src/extension.ts
[vscode][4/n] Setup Env Variables: Add helper text to existing env path
This PR I had some issues with reading the env template, so for now I'm splitting up this logic and will follow up next PR
https://github.com/lastmile-ai/aiconfig/assets/151060367/6aad117f-0c55-4549-8f46-1b438c6ebf4b
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1284).
* #1285
* __->__ #1284
* #1283
* #1280
> [vscode][4/n] Setup Env Variables: Add helper text to existing env path

- vscode-extension/src/extension.ts
[vscode][5/n] Setup Env Variables: Read the text from the env template and append to existing file
TSIA, and making the function async now that we call an await statement
https://github.com/lastmile-ai/aiconfig/assets/151060367/6679e13d-6d58-4ec4-a237-360cb273e59c
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1285).
* __->__ #1285
* #1284
* #1283
* #1280
> [vscode][5/n] Setup Env Variables: Read the text from the env template and append to existing file

- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
[vscode installation] 2/n refactor error message for invalid python install
Added a helper method for showing user friendly error when python install doesn't go well.
Select Interpreter version 3.9.4. Open an editor and expect an error notification.
https://github.com/lastmile-ai/aiconfig/assets/141073967/5bda86e0-690f-4e43-9e94-f9279e3b2f34
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1265).
* #1294
* #1289
* #1290
* __->__ #1265
> [vscode installation] 2/n refactor error message for invalid python install

- vscode-extension/package.json
- vscode-extension/src/extension.ts
- vscode-extension/yarn.lock
[vscode install] 4/n add retry for pip install dependencies
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1294).
* #1289
* __->__ #1294
* #1290
> [vscode install] 4/n add retry for pip install dependencies

- vscode-extension/package.json
- vscode-extension/src/extension.ts
- vscode-extension/yarn.lock
3/n Update Initialize to invoke select interpreter
This diff updates the initialize flow to include the Python interpreter selection step. It ensures dependencies are installed only after the interpreter selection is finalized, accommodating the no-op change where the selected interpreter remains unchanged.
Note: If the extension is not activated, invoking the Initialize AIConfig command for an unknown reason installs dependencies on the pre-selected interpreter path
Extension initializes on Opening An AIConfig
Test select a new interpreter
Test reselecting the same interpreter
https://github.com/lastmile-ai/aiconfig/assets/141073967/1a51ff89-3889-4fd6-8964-c341453ddf68
https://github.com/lastmile-ai/aiconfig/pull/1265
--- …
> 3/n Update Initialize to invoke select interpreter

- vscode-extension/editor/src/VSCodeEditor.tsx
Currently, the webview only notifies the extension of dirty document (on the server) before/after the run request to the server. For long-running/streaming prompts, the request's response is actually returned well before the streaming responses are completed, meaning the document is not actually notified when the stream completes with the new output.
To fix, we can call `notifyDocumentDirty` to [update the text document in the extension with the server state](https://github.com/lastmile-ai/aiconfig/blob/main/vscode-extension/src/aiConfigEditor.ts#L282) whenever any of the stream responses are obtained (excluding `output_chunk` since that happens very frequently and would lead to the extension host loading the file from the server too frequently)
Running a prompt now shows the output in …
> [vscode] Fix Outputs Propagating to Text Document

- vscode-extension/editor/src/VSCodeEditor.tsx
- vscode-extension/editor/src/utils/vscodeUtils.ts
[editor][ez] Fix Resaturation of Editor with Bad Server State
Currently, when re-saturating the webview for an editor with bad server state (e.g. invalid model parsers in the config), the /load call will fail and leave the webview with the loading spinner:
https://github.com/lastmile-ai/aiconfig/assets/5060851/3949274d-fbb1-479f-a54a-9ac8870e617c
To fix, we can serialize the config in webview context and then use it to re-saturate the aiconfig state in the webview:
https://github.com/lastmile-ai/aiconfig/assets/5060851/5d67dc31-7b68-4782-af73-a8b6294a5452
For a webview with working state, note that /load is called successfully after the webview loads and will update the aiconfig state in the editor as needed (now that aiconfig prop updates the editor state)
> [editor][ez] Fix Resaturation of Editor with Bad Server State

- vscode-extension/src/aiConfigEditor.ts
- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
[vscode][7/n] Setup Env Variables: Connect missing API keys error to command
Now it's more intuitive for users to know what needs to be done when they receive this error. I also moved the logic for the command into a utils file so it can be accessed both by activation flow and the error checking flow in the editor
Getting missing API key error
https://github.com/lastmile-ai/aiconfig/assets/151060367/cc6c51e5-d205-4afa-a3b4-dc04f68d4946
Walkthrough commands
https://github.com/lastmile-ai/aiconfig/assets/151060367/bda40b3c-d260-40a2-82da-563d363152b3
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1300).
* __->__ #1300
* #1291
> [vscode][7/n] Setup Env Variables: Connect missing API keys error to command

- vscode-extension/src/extension.ts
[ez][vscode] Remove Initialization Flow from Extension Activation
This diff removes the Initialization flow from ocurring on Extension Activation.
The landing page directs the user to invoke this command.
The Opening an AIConfig may invoke this if dependencies are not installed (not implemented yet)
Invoking the Initialize Command will no longer automatically install dependencies on the pre-selection python interpreter.
https://github.com/lastmile-ai/aiconfig/assets/141073967/04031cdc-2c9d-47e8-b43d-a9d2f6aa769d
> [ez][vscode] Remove Initialization Flow from Extension Activation

- vscode-extension/package.json
- vscode-extension/src/constants.ts
- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
Cache Python interpreter to VS Code settings
Do this after we run the `checkPython()` flow
It's just a simple write. We'll be using it later in two flows:
1. On open/create AIConfig file init to determine if interpter path is set (see Ankush PR in here for more details: https://github.com/lastmile-ai/aiconfig/pull/1301)
2. When updating interpter to loop over existing open AIConfig editor windows
Got this code to update from https://github.com/lastmile-ai/aiconfig/blob/826565f7079bc30e228a1477541ccbf17702d4f6/vscode-extension/src/extension.ts#L398-L402
When AIConfig Editor is activated, check that it's saved to VS Code settings
https://github.com/lastmile-ai/aiconfig/assets/151060367/b7977c08-5a5a-4ca9-bff8-3bce7914e52e
> Cache Python interpreter to VS Code settings

- vscode-extension/editor/package.json
- vscode-extension/editor/yarn.lock
- vscode-extension/src/aiConfigEditor.ts
[rfc] Show readonly Editor Before Server Is Started
Currently when opening an aiconfig file, the file contents / editor webview are not rendered at all until the server is started (or attempted to start). This is because the webview isn't rendered until `resolveCustomTextEditor` returns, and we are awaiting a few server-initialization-related calls within the function.
To fix, we can move the `startEditorServer` into a regular `.then`, which will call the Promise without blocking. Within the `.then` we can handle the resolved promise as normal and do the other things that depend on the server process running.
Another thing worth mentioning is that we previously required the server url to set up the csp for the webview HTML. I'm not sure if we actually need to set the `connect-src …
> [rfc] Show readonly Editor Before Server Is Started

- vscode-extension/editor/package.json
- vscode-extension/editor/yarn.lock
[vscode] Bump aiconfig-editor dependency to 0.2.1
- Fix for not calling getModels callback in readOnly
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1309).
* #1306
* __->__ #1309
> [vscode] Bump aiconfig-editor dependency to 0.2.1

- vscode-extension/src/aiConfigEditor.ts
- vscode-extension/src/utilities/pythonSetupUtils.ts
Check interpreter (initalize if needed) and call install dependency flow before starting editor server
Three main things we do here:
1. Check if interpreter is defined in workspace settings (set in https://github.com/lastmile-ai/aiconfig/pull/1304)
2. Call either `initialize()` or `installDependencies()` depending on that result
3. Implement the `initializePythonFlow()` inside of `resolveCustomTextEditor()`
Before (does not invoke flow)
https://github.com/lastmile-ai/aiconfig/assets/151060367/8f1e308c-975d-4a79-8f9a-127c0322f065
After (does invoke flow)
https://github.com/lastmile-ai/aiconfig/assets/151060367/28f97461-3e7c-4340-af2c-fb4993562c24
> Check interpreter (initalize if needed) and call install dependency flow before starting editor server

- vscode-extension/src/aiConfigEditor.ts
Fix some strict null-checks in error text
Some minor nits, just noticed this when running
```
yarn && yarn compile --strict
```
Before
After
> Fix some strict null-checks in error text

- vscode-extension/src/aiConfigEditor.ts
Realized when looking into restarting the server that the `editorServer` global var was not being set properly (was null on dispose). The problem was using the same name for the resolved started server. This fixes by using a different name
- Ensure the editorServer value is right when disposing the webview
- Close webview and open again and ensure new server at port 8000
- Make changes to JSON for a config and toggle back to the editor webview and see the changes reflected there
> [vscode] Fix Setting editorServer

- vscode-extension/package.json
Delete showWelcome command
This content was deleted in https://github.com/lastmile-ai/aiconfig/pull/1295/files#diff-637aab27a087b4c7cf87e366e6db33051834d74be94b7b5b478817207f9a6df1 so today this command doesn't open anything
Before
https://github.com/lastmile-ai/aiconfig/assets/151060367/58a2ac2d-e8e7-41df-b25d-277741619b83
After
No longer part of AIConfig commands
> Delete showWelcome command

- vscode-extension/package.json
- vscode-extension/src/util.ts
Support .yml file extensions
This was something we noticed at customer offsite where many people tried creating aiconfigs with *.yml extension.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1324).
* __->__ #1324
* #1323
* #1316
> Support .yml file extensions

- vscode-extension/package.json
- vscode-extension/src/aiConfigEditor.ts
- vscode-extension/src/aiConfigEditorManager.ts
- vscode-extension/src/editorServer.ts
- vscode-extension/src/editor_server/editorServer.ts
- vscode-extension/src/editor_server/serverPortManager.ts
- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
- vscode-extension/yarn.lock
When interpreter changes restart all editors if the user selects it. We need to leverage async locking mechanism for managing the server port otherwise each of the simultaneously-restarted servers could end up with duplicate port number.
Seems that even with just the lock it won't work, so need to explicitly manage the starting port in the search (to a reasonable max, before restarting search at 8000 again).
https://github.com/lastmile-ai/aiconfig/assets/5060851/7708c288-2878-420e-9130-4074ca9a11b5
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1328).
* __->__ #1328
* #1319
* #1318
> [3/n] Restart Editor Servers on Python Interpreter Change

- vscode-extension/src/aiConfigEditor.ts
- vscode-extension/src/aiConfigEditorManager.ts
- vscode-extension/src/editorServer.ts
- vscode-extension/src/util.ts
[1/n] Implement Editor Server as Class
Currently we maintain EditorServer state as an object for the extension, accessing the process and server url from the object. In subsequent PR, we will need to expose the ability to restart the editor server. Instead of creating and exposing a restart function on the object, let's just move the editor server into a class so that we have a proper instance with methods to leverage for starting, stopping and (next PR) restarting.
Open an aiconfig, ensure the server starts and I can run a prompt
Close the config, verify in logging that the server process is properly killed
Open config again. See server start up on 8000 (i.e. the port is open again after server was killed)
--- …
> [1/n] Implement Editor Server as Class

- vscode-extension/package.json
- vscode-extension/src/aiConfigEditor.ts
- vscode-extension/src/aiConfigEditorManager.ts
- vscode-extension/src/editorServer.ts
- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
[2/n] Support Restarting Editor Server
Add an "AIConfig: Restart Active Editor Server" command so that users can restart the server for the active (in-view) editor. As part of this, implement the restart functionality for the EditorServer so that the server process is killed and a new one is started, ensuring the associated extension/webview is properly updated to associate with the new server process. As best effort, also implement an `onDidChangeState` so that we can listen to the editor server status changing and show a progress notification that the server is starting.
This logic will be leveraged in subsequent PR to handle restarting all editor servers when the workspace python interpreter changes.
https://github.com/lastmile-ai/aiconfig/assets/5060851/39739008-abc7-4538-9087-42972c14 …
> [2/n] Support Restarting Editor Server

- vscode-extension/package.json
- vscode-extension/src/util.ts
Fix error starting server on new aiconfig yaml
When you create a new aiconfig yaml, the server fails to start.
This is because of changes to the flow where we are calling `updateServerState` in the launch flow of the editor, which in turn calls `getModeForDocument`. This function uses the file extension to determine if the document is JSON or YAML, but in the case of Untitled documents, there is no file URI.
Since it is reasonable to expect this flow for Untitled documents, the fix here is to use the document's content to determine the mode (try parsing it as JSON or as YAML).
https://github.com/lastmile-ai/lastmile/assets/25641935/1c96d099-d970-4e5f-9b58-3768451e591c
> Fix error starting server on new aiconfig yaml

- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
[local editor] Don't poll server status when in read only view
In order to prevent showing status error message when in read only view, this diff makes sure that the aiconfig editor client does not poll the server status when in read only mode.
See #1320 for more context
1. Manually set readonly prop to True
2. Load local editor (Loaded in prod mode, I first built the editor with yarn build)
3. kill the python process that is hosting the aiconfig server.
| Before  | After |
| <img width="1913" alt="after" src="https://github.com/lastmile-ai/aiconfig/assets/141073967/ce3487ba-0174-4ca7-b58e-7e10aed6409d">  | <img width="1909" alt="before" src="https://github.com/lastmile-ai/aiconfig/assets/141073967/cba7b817-d09e-435f-b2e8-da7c13109459"> |
Note: the …
> [local editor] Don't poll server status when in read only view

- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
[vscode] Prompt User for Name When Creating New AIConfig
VS Code api for creating new/untitled files does not allow specifying the extension to use for the file on save. This results in untitled files being prompted to save with either .json or .yaml extension, NOT .aiconfig.json or .aiconfig.yaml. This is a big problem, since using the non-aiconfig extension will result in the file not opening with our custom editor next time it's opened.
As a workaround, we can default the untilted filename to untitle.aiconfig.json/yaml and prompt the user for the proper name when creating it (before showing the contents). See #1334 for the alternative, of saving the file immediately as untitled and requiring the user to rename manually if they want afterwards. …
> [vscode] Prompt User for Name When Creating New AIConfig

- vscode-extension/src/util.ts
[vscode][8/n] Setup Env Variables: Use lowest common ancestor path for multiple workspaces
Somewhat slightly checked out in https://gitlab.com/sebdeckers/lowest-common-ancestor/-/blob/master/src/index.js?ref_type=heads, but didn't want to use this package since:
1. It doesn't have exact functionality I want (ex: if only 1 path provided, it returns empty string)
2. Don't want something small to depend on a package when we can control it ourselves
Some VS Code setups can have multiple workspaces, in which case we should take the lowest common ancestor path that is shared across all of them so that the same .env file can be used for multiple AIConfig files. Initial comment from Sarmad in https://github.com/lastmile-ai/aiconfig/pull/1291#discussion_r1499876794
Tested it with my vscode …
> [vscode][8/n] Setup Env Variables: Use lowest common ancestor path for multiple workspaces

- vscode-extension/package.json
- vscode-extension/src/constants.ts
- vscode-extension/src/extension.ts
- vscode-extension/src/utilities/versionUpdateUtils.ts
Cache versions of extension into global settings
This is kind of a hack. I'm not sure why the extension walkthrough isn't opening when it first installs, but whatever we need to do this to ensure that walkthrough runs, because it's not running when users first download the extension (could be perhaps that we've already installed it so global settings is aware of it, idk but whatever)
Adding a global config for `vscode-aiconfig.version`, and also changed the activate settings to activate upon vscode startup. This is fine because we moved the initialize step outside of here so there's no negative consequences of activating it.
Will implement the actual functionality next PRs
Ok I don't know why I can't test directly bvy running the activation command, but instead I just hooked this up to …
> Cache versions of extension into global settings

- vscode-extension/src/aiConfigEditor.ts
Currently, if the server fails to start we just have the option to show details or retry. In cases where it will never start (e.g. current interpreter doesn't have the right packages) this leaves the user stuck. So, provide the option to "Change Python Interpreter" so that the user can try a different one. Note, changing interpreter will automatically show the 'Restart editor servers' notification for the user to restart the server. It would be nice to automatically do this, but I wasn't able to figure out a clean way to handle that (i.e. don't show our 'global' listener's notification in this case). Maybe we can do that as a P1 followup?
https://github.com/lastmile-ai/aiconfig/assets/5060851/9e65f38e-ae70-4d64-9c1d-645bfe897804
> [vscode] Give Option to Change Python Interpreter if Server Fails to Start

- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
- vscode-extension/src/utilities/pythonSetupUtils.ts
Fix issues when no workspace is opened
When no workspace folder is opened, we get errors. This is due to the fact that we are trying to save vscode configuration settings in the Workspace context, when none exists.
To fix, if no workspace is opened, we save the settings in the global context.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1335).
* #1336
* __->__ #1335
> Fix issues when no workspace is opened

- vscode-extension/src/utilities/pythonSetupUtils.ts
[vscode] Prompt User to restart Vscode after installing python
As part of the vscode extension installation flow, if the user doesn't have a valid python interpreter, they are prompted with a vscode notification asking them if they would like to install python.
If they do install python, vscode will need to be restarted in order to have the new interpreter available to select.
This diff shows the user a notification with the option to restart vscode for them, if they click on `Install Python` as mentioned above.
RFC: Python Extension API exposes  functionality to [Detect new environments discovered in the system](https://github.com/microsoft/vscode-python/wiki/Python-Environment-APIs#detect-new-environments-or-changes-to-the-interpreters-discovered-in-the-system) but I felt it would be …
> [vscode] Prompt User to restart Vscode after installing python

- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
This implements a proper(?) fix for creating new/untitled aiconfig files:
- treats the file as regular Untitled (but with proper `.aiconfig.json/yaml` extension), prompting for filename only on first save, no longer needing to prompt immediately on create (undoing #1337)
- now, only one tab is opened and it opens the custom editor
The main change/fix is using a `WorkspaceEdit` to hold the initial content changes instead of opening/showing a new text editor with the content. I found that solution from https://github.com/microsoft/vscode/issues/93441
However, now the webview seems to reload the file after saving it for the first time, which makes it go back to readonly and start up the server :( --> it seems to dispose the untitled webview (killing the server) and refresh with a new …
> Proper Fix for Ideal New/Untitled Flow

- my_aiconfig.aiconfig.json
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/GeminiPromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
4/n Gemini Prompt Schema
Prompt Schema for Gemini Pro.
This prompt schema doesn't define a schema for Gemini's Safety Settings As those are more complicated, they will come on top.
API Docs for Generation Config: https://ai.google.dev/api/python/google/ai/generativelanguage/GenerationConfig
Skipped these attributes as part of the prompt schema.
- skipped candidate count
- didn't add max_output_tokens. I was getting weird index out of bounds exceptions when setting max_output_tokens which occured at the output parsing step. I tried with 35, 400, 200. Thought it would be better UX to just leave it out for now before figuring out why.
- safety settings
See:
Code Ref: https://github.com/google/generative-ai-python/blob/main/google/generativeai/types/safety_types.py#L218-L221
API Doc Ref: …
> 4/n Gemini Prompt Schema

- vscode-extension/src/aiConfigEditor.ts
Currently when creating a new config file and saving it, the initial `untitled:/` document webview is disposed and quickly reloaded with that of the `file:/` document. Before the `untitled:/` is disposed, though, the text document emits a change event with the full contents of the file. This change event results in our extension attempting to update the server with the state from the changed file (on the server, it will attempt to load the content at the document's path), which fails because this untitled file does not exist on disk. Heres' the logging for this flow:
```
changeDocumentSubscription untitled:/Users/ryanholinshead/Projects/aiconfig/cookbooks/untitled.aiconfig.json -- updating webview (at console.<anonymous> (/Applications/Visual Studio …
```
> Don't Show Server Update Error for Untitled Configs

- vscode-extension/package.json
Currently, untitled yaml config files have the tab name matching the first line of our static untitled yaml template:
This appears to be a result of the `workbench.editor.untitled.labelFormat` setting:
```
// Controls the format of the label for an untitled editor.
//  - content: The name of the untitled file is derived from the contents of its first line unless it has an associated file path. It will fallback to the name in case the line is empty or contains no word characters.
//  - name: The name of the untitled file is not derived from the contents of the file.
"workbench.editor.untitled.labelFormat": "content",
```
We can set this setting for our extension to use the name instead of content (default):
Alternatively, it seems we could leave the first line of our …
> Use Name Instead of File Contents for Untitled Tab

- vscode-extension/src/utilities/versionUpdateUtils.ts
Hard-code extension id for opening walkthrough
This flow is being triggered and Tanya is opening the main `Help:Welcome` page, but this isn't opening our specific walktrough for Tanya when she's testing for some reason. HOpefully hardcoding this fixes it
https://github.com/lastmile-ai/aiconfig/assets/151060367/0d392d07-8e2c-40a5-92b9-832fae7107c1
> Hard-code extension id for opening walkthrough

- python/src/aiconfig/editor/client/src/components/JSONRenderer.tsx
Currently when rendering the editor in readonly, opening the model settings for a prompt which has no metadata and which has no prompt schema, results in a js/render error:
This is actually the problem Zak surfaced for the vscode doc of a blank screen when opening the settings for an aiconfig in vscode.
The problem is that Prism expects the contents to be a string, which obviously isn't the case if there is no metadata (it's undefined). To fix, just don't render anything in this specific scenario.
- Make sure rendering in and out of readonly works:
> [editor] Fix Readonly Rendering of Undefined Model Settings

- vscode-extension/editor/package.json
- vscode-extension/editor/yarn.lock
Includes:
- Fix readonly rendering for undefined model settings w/ no schema (#1358)
- Gemini prompt schema (#1023)
> [vscode] Bump aiconfig-editor Package to 0.2.3

- vscode-extension/src/utilities/pythonSetupUtils.ts
[vscode] Add 'Manual Fix' Message when Installing Dependencies fails
This diff modifies the Information Message that is shown when Installing Dependencies fails.
- Add a Fix Manually which then shows the user a command to pip install, that they can copy to clipboard
- Rename:
- - `Retry Install Dependencies` -> `Retry`
- - `Select Interpreter` -> `Change Interpreter`
Manually Modified the Pip Install spawn process to run `const pipInstall = spawn("sh", ["-c", "exit 1"]);` which will  automatically exit with error.
https://github.com/lastmile-ai/aiconfig/assets/141073967/6a7b8d6f-5d26-40c6-9696-235e713fed93
RFC: Wording =)
> [vscode] Add 'Manual Fix' Message when Installing Dependencies fails

- vscode-extension/src/aiConfigEditor.ts
Enable the find widget in our custom editor using the `enabledFindWidget` option when registering our custom editor provider. The default is false. In our case, setting to true works since it's just a regular text search in the DOM elements.
https://code.visualstudio.com/api/references/vscode-api#WebviewPanelOptions
https://github.com/lastmile-ai/aiconfig/assets/5060851/0a9d4c4d-af90-4cb0-8c1b-8ef9258dc657
> [vscode] Enable Find Widget in Editor

- vscode-extension/README.md
Small fix on readme that removed duplication for the video
> [docs] fixed duplication on extension readme

- vscode-extension/src/aiConfigEditor.ts
Currently, turning on autosave with default 1000ms delay causes a ton of buggy behaviour in the editor webview:
- typing can lose focus from the input
- execution gets cut off and outputs lost
https://github.com/lastmile-ai/aiconfig/assets/5060851/56123039-2245-4b6b-81ce-24b6c26ac0d1
The cause of this behaviour is that we subscribe to the document save event, obtaining the config contents from the server and propagating the change to the TextDocument. However, this change the the TextDocument is resulting in our `onDidChangeTextDocument` event firing and updating the webview (as well as pushing update back to the sever state). The result is that our webview has a new `aiconfig` value passed as prop to the editor and does a full re-render of the editor.
To fix, we should simply treat this …
> [vscode] Treat Autosaves as an internalDocumentChange

- CHANGELOG.md
- python/pyproject.toml
- typescript/package.json
Bump versions and publish changelog
TSIA
Summary:
Test Plan:
I learned that GH markdown automatically does short-form linking to full Github URLs (shows #NUMBER instead of full URL) so don't have to format that!
> Bump versions and publish changelog

- python/src/aiconfig/editor/server/server.py
1/n [vscode & server] Reload Environment when invoking the Run Step
This diff modifies the AIConfig backend server to reload the environment everytime the Run Step is invoked. This will allow api keys that are newly added to be picked up from the aiconfig server, without the need to restart the server.
I validated that `load_dotenv` does not add any noticeable latency.
```
import time
import dotenv
start = time.time()
dotenv.load_dotenv()
end = time.time()
print(end-start)
_____
0.0010402202606201172s
```
Surfaced from #1371, a restart of the server will no longer be required.
Ontop of this, we can pass a .env path directly the server initialization, instead of relying on a set of lowest-common-ancestor checks
Discussed offline with @saqadri …
> 1/n [vscode & server] Reload Environment when invoking the Run Step

- vscode-extension/src/extension.ts
[ez] Specify content type in Share request based on JSON vs. YAML document
TSIA, Sarmad aded change to render it correctly in the lastmile repo (https://github.com/lastmile-ai/lastmile/pull/1380), but still should be changing the content type now:
It actually still works before, not sure if content-type is a blocker. But just good to specify I guess
https://github.com/lastmile-ai/aiconfig/assets/151060367/4f7e6c8f-7198-45a9-b92c-43560ff5ba0d
> [ez] Specify content type in Share request based on JSON vs. YAML document

- cookbooks/Gradio/README.md
The commands are not necessary; they're for rebuilding local editor client which has nothing to do with this cookbook
> Remove Unnecessary Yarn Commands from README

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/editor/server/server_utils.py
[server] 4/n Update Use .env at the run step
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1384).
* __->__ #1384
* #1383
* #1382
> [server] 4/n Update Use .env at the run step

- python/src/aiconfig/editor/server/server_utils.py
[server] 2/n Add env path to Server State
Summary:
Stack contains changes that updates overall environment setup flow for vscode extension.
No functional Changes in this diff.
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1382).
* #1384
* #1383
* __->__ #1382
> [server] 2/n Add env path to Server State

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/editor/server/server_utils.py
[server] 3/n Endpoint for set_env
Summary:
Stack contains changes that updates overall environment setup flow for vscode extension.
This diff implements the server side endpoint. Will test on top with vscode
Test Plan:
```
payload={'env_file_path': {}}
Status Code: 400
Response JSON: {'message': 'Invalid request, specified .env file path is not a string.'}
payload={'env_file_path': '/hi'}
Status Code: 400
Response JSON: {'message': 'Specified .env file path does not exist.'}
payload={'env_file_path': '.env'}
Status Code: 200
Response JSON: {'message': 'Updated .env file path.'}
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1383).
* #1384
* __->__ #1383
* #1382
> [server] 3/n Endpoint for set_env

- vscode-extension/package.json
[ez] vscode extension - fix diff editor
The bug is a simple spacebar between`aiconfig.json,<SPACE>aiconfig.yaml`. This affects the regex used to apply the editor association.
Tested that now opening both aiconfig.yaml and aiconfig.json files in diff editor open them in regular text editor.
For good measure, also added support for *.aiconfig files, and tested that too.
> [ez] vscode extension - fix diff editor

- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceVisualQuestionAnsweringRemoteInferencePromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
Implement HuggingFaceVisualQuestionAnsweringRemoteInferencePromptSchema
For https://github.com/lastmile-ai/aiconfig/issues/1392
This will add the prompt schema so that visual question answering prompts have the nice UI for input and settings
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1396).
* #1397
* __->__ #1396
> Implement HuggingFaceVisualQuestionAnsweringRemoteInferencePromptSchema

- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputSchemaRenderer.tsx
- python/src/aiconfig/editor/client/src/shared/prompt_schemas/HuggingFaceVisualQuestionAnsweringRemoteInferencePromptSchema.ts
- python/src/aiconfig/editor/client/src/utils/promptUtils.ts
See comment in https://github.com/lastmile-ai/aiconfig/pull/1396#pullrequestreview-1915432291
When we have a Prompt Input with both attachment and data, most likely the attachment will be the main focus (e.g. Visual Question Answering) so we can show it first in the prompt input:
Was initially thinking we could order it based on the properties order in the schema, but just doing this for now since property order in schema may not be guaranteed when we define it in python and then serialize it to to client (will just be passing JSON object in response)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1397).
* __->__ #1397
* #1396
> Render Attachment before Data When Both Exist in Input

- python/src/aiconfig/editor/server/server_utils.py
- vscode-extension/package.json
- vscode-extension/src/constants.ts
- vscode-extension/src/editor_server/editorServer.ts
- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
[vscode] 8/n Remove LCA env checks
Summary:
Now that a user can specify a .env file path with no restrictions on its location, the LCA checks need to be removed.
LCA = Lowest Common Ancestor
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1398).
* __->__ #1398
* #1390
* #1387
* #1389
> [vscode] 8/n Remove LCA env checks

- python/src/aiconfig/editor/server/server_utils.py
- vscode-extension/package.json
- vscode-extension/src/constants.ts
- vscode-extension/src/editor_server/editorServer.ts
- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
[vscode] 7/n listeners and .env
Summary:
When the .env file path is set, vscode will invoke api/set_env on each AIConfig server.
Defines a listener to a newly introduced setting for the env_file_path.
This ensures that users do not need to restart vscode to pickup env changes.
Test Plan:
1. set env file path
2. changes picked up
3. changes picked up on restart
4. Changes picked up when manually removing vscode setting and re-setting env file path and api key
https://github.com/lastmile-ai/aiconfig/assets/141073967/07ac1d43-28ef-439f-98e7-94a4e73e11c9
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1390).
* #1398
* __->__ #1390
* #1387
* #1389
> [vscode] 7/n listeners and .env

- python/src/aiconfig/editor/server/server_utils.py
- vscode-extension/src/util.ts
[vscode] 6/n update Route Table with env api
Summary:
Stack contains changes that updates overall environment setup flow for vscode extension.
This diff adds support to call "SET_ENV_FILE_PATH" implemented in the previous diff.
No functional changes.
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1387).
* #1398
* #1390
* __->__ #1387
* #1389
> [vscode] 6/n update Route Table with env api

- python/src/aiconfig/editor/server/server_utils.py
[server] 5/n Update AIConfig edit|start commands to pass env
Summary:
This diff modifies the AIConfig start and edit commands to take in an dot env path.
Due to core utils logic of handling args, the help messages automatically get updated too.
Also Removes the loadenv() on server init. This is okay because loadenv is invoked at the run step. [see 4/n](https://github.com/lastmile-ai/aiconfig/pull/1384)
Test Plan:
```
ankush@ap-mbp aiconfig % aiconfig start -h
/opt/homebrew/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_parsers" has conflict with protected namespace "model_".
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
warnings.warn(
usage: aiconfig start [-h] [--server-port SERVER_PORT] …
```
> [server] 5/n Update AIConfig edit|start commands to pass env

- cookbooks/Groq/aiconfig_model_registry.py
- extensions/Groq/README.md
[groq] updated readme for the new instructions
addressed comments
> [groq] updated readme for the new instructions

- python/tests/parsers/test_openai_util.py
- python/tests/test_run_config.py
Fix Tests Marked as xfail
These were marked as `xfail` in https://github.com/lastmile-ai/aiconfig/pull/999 as part of the parser refactor. I noticed in https://github.com/openai/openai-python/issues/715#issuecomment-1809203346 that applying the patch to `openai.resources.chat.Completions.create` seems to fix the tests
Test Plan:
```
(aiconfig) ryanholinshead@Ryans-MBP python % pytest tests/parsers/test_openai_util.py
========================================================== test session starts ===========================================================
platform darwin -- Python 3.12.1, pytest-7.4.3, pluggy-1.4.0
rootdir: /Users/ryanholinshead/Projects/aiconfig/python
plugins: asyncio-0.23.5, hypothesis-6.91.0, cov-4.1.0, mock-3.12.0, anyio-4.2.0
asyncio: mode=Mode.STRICT
collected 3 …
```
> Fix Tests Marked as xfail

- python/src/aiconfig/editor/server/server.py
- python/src/aiconfig/editor/server/server_utils.py
9/n Server init env file Validation
Summary:
- Refactored Env File Validation to a helper method
- Added env file validation to aiconfig server start. Does not block on an invalid file, and instead logs error message
Test Plan:
```
aiconfig edit --env-file-path=testfiledoesntexist
[WARNING] 2024-03-06 11:59:44,800 server_utils.py:306: Specified env file path is not a .env file: 'testfiledoesntexist'
```
```
aiconfig edit --env-file-path=testfiledoesntexist.env
[WARNING] 2024-03-06 12:00:13,063 server_utils.py:306: Specified .env file path does not exist: 'testfiledoesntexist.env'
```
Note: while testing I noticed that argparse handles no argument passed as an empty string.
* __->__ #1404
* #1398
> 9/n Server init env file Validation

- python/requirements.txt
Update openai to 1.13.3
Summary:
Updating the openai version to latest (1.13.3) so that we can use the image messages for gpt-4-v in the next PR
Test Plan:
- pytest works without errors
- WIP: Testing all relevant cookbooks
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1415).
* #1419
* #1418
* #1417
* #1416
* __->__ #1415
> Update openai to 1.13.3

- python/requirements.txt
- python/src/aiconfig/default_parsers/openai_vision.py
Implement OpenAIVisionParser
Summary: Using the default openai parser as the basis (and extending it), implement a parser for text-and-image openai models (e.g. gpt-4-v). The key differences are:
- vision models don't support function calling or tools, so exclude from the completion params
- serialize/deserialize need to be a bit different to construct the user messages' content with text and image urls
One thing to note is the default max tokens for GPT-4V is quite small. Bumping it to 100 in #1419
Another thing I found while testing is that the model gets confused sometimes when you refer to the attached image as an image. For example, I had a prompt as "What is this image of" and it responded with "I can't provide information on any images until you upload one". Then I reran a handful …
> Implement OpenAIVisionParser

- python/requirements.txt
- python/src/aiconfig/Config.py
- python/src/aiconfig/default_parsers/openai_vision.py
Add "gpt-4-vision-preview" as default parser
Summary: Just adding this model/parser as a default alongside the other openai defaults
Test Plan: Can use the parser in the editor
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1417).
* #1419
* #1418
* __->__ #1417
* #1416
* #1415
> Add "gpt-4-vision-preview" as default parser

- aiconfig-docs/docs/gradio-notebook.md
[docs] Remove caution text from Gradio Notebooks Getting Started for incompatible SDK version
This is now resolved with https://github.com/lastmile-ai/gradio-notebook/pull/199 so we don't need this restriction anymore!
> [docs] Remove caution text from Gradio Notebooks Getting Started for incompatible SDK version

- vscode-extension/editor/src/VSCodeEditor.tsx
[vscode] add session id to telemetry
Summary:
in an effort to understand distinct session users, this diff adds a unique session identifier to telemetry.
Unfortunately, it looks like the "default" sessionID that comes with datadog browser telemetry is not being sent, similar to what we noticed with [gradio](https://github.com/lastmile-ai/gradio-notebook/pull/184). Hence the need to define this explicitly
Note: This does not collect new metrics. This will allow for the LastMile team to understand how many users are using our vscode extension.
Test Plan:
> [vscode] add session id to telemetry

- vscode-extension/package.json
[vscode] Fix package.json path parsing issue
Summary:
Ran into trouble when attempting to package the vscode extension due to errors parsing the logo path.
Running `vsce package` locally resulted in the following error:
` ERROR  The specified icon 'extension/./static/Logo.png' wasn't found in the extension.`
This diff attempts to fix that.
Test Plan:
`vsce package` and installed locally
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1423).
* __->__ #1423
* #1422
> [vscode] Fix package.json path parsing issue

- gradio-notebook/backend/gradio_notebook/templates/component/index.js
- python/src/aiconfig/editor/client/src/LocalEditor.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/global/ConfigMetadataContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/AddPromptButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/ModelSelector.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptsContainer.tsx
- python/src/aiconfig/editor/client/src/hooks/useLoadModels.ts
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
- python/src/aiconfig/editor/client/src/themes/LocalTheme.ts
- python/src/aiconfig/editor/client/src/themes/VSCodeTheme.ts
- vscode-extension/editor/src/VSCodeEditor.tsx
- vscode-extension/editor/src/VSCodeTheme.ts
Update getModels to Make Search String Optional
In a few cases, we don't have a search string to use for the getModels call and it's weird to need to pass in an empty string to represent that case. Just updating the implementation to make the search string optional
- Make sure all getModels calls work (add prompt, prompt model selector)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1438).
* #1444
* #1443
* #1442
* #1441
* #1440
* #1439
* __->__ #1438
* #1437
> Update getModels to Make Search String Optional

- gradio-notebook/backend/gradio_notebook/templates/component/index.js
- python/src/aiconfig/editor/client/src/LocalEditor.tsx
- python/src/aiconfig/editor/client/src/components/AIConfigEditor.tsx
- python/src/aiconfig/editor/client/src/components/global/ConfigMetadataContainer.tsx
- python/src/aiconfig/editor/client/src/components/models/ModelMenuDropdown.tsx
- python/src/aiconfig/editor/client/src/components/prompt/AddPromptButton.tsx
- python/src/aiconfig/editor/client/src/components/prompt/ModelSelector.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptContainer.tsx
- python/src/aiconfig/editor/client/src/components/prompt/PromptsContainer.tsx
- python/src/aiconfig/editor/client/src/hooks/useLoadModels.ts
- python/src/aiconfig/editor/client/src/themes/GradioTheme.ts
- python/src/aiconfig/editor/client/src/themes/LocalTheme.ts
- python/src/aiconfig/editor/client/src/themes/VSCodeTheme.ts
- vscode-extension/editor/src/VSCodeEditor.tsx
- vscode-extension/editor/src/VSCodeTheme.ts
Pull ModelMenuDropdown to its own Component
Pulling out the model menu dropdown (searchable list of models) into its own component for reuse. It's currently used in the AddPromptButton but will be used in the global model settings renderer for adding model to set settings for.
- Make sure add prompt menu works correctly
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1439).
* #1444
* #1443
* #1442
* #1441
* #1440
* __->__ #1439
* #1438
* #1437
> Pull ModelMenuDropdown to its own Component

- README.md
Spaces between the <a></a> tags create a hyperlinked `_` character that is visible on GitHub.
Fixed `_` by removing it as well as removing `|` separators between badges for cleaner appearance.
> Cosmetic Fixes to README.md badges - fix weird hyperlinked underscores and remove `|` character for cleaner appearance

- python/src/aiconfig/editor/client/src/components/models/model_settings/ModelSettingsRenderer.tsx
- python/src/aiconfig/editor/client/src/components/models/model_settings/ModelSettingsSchemaRenderer.tsx
I have no idea what's going on with sl but it didn't properly mark the file moves from the ModelSettingsRenderer components as moves in https://github.com/lastmile-ai/aiconfig/pull/1440/commits/c44889a1a83ab78b9802cdf7b9ad745fab2ae456, so manually adding them again here so that they exist in git
- Make sure the model settings renderers render correctly
> Add ModelSettings Renderers to sl

- python/src/aiconfig/editor/client/src/components/prompt/prompt_input/schema_renderer/PromptInputAttachmentsSchemaRenderer.tsx
[ez][ts lint] remove unused statements in editor Client
These warnings are surfaced by`Yarn lint` or `yarn build`
```
ankush@ap-mbp client % yarn build
yarn run v1.22.21
$ react-scripts build
Creating an optimized production build...
Compiled successfully.
File sizes after gzip:
316.5 kB  build/static/js/main.dde99e89.js
The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.
The build folder is ready to be deployed.
You may serve it with a static server:
yarn global add serve
serve -s build
Find out more about deployment here:
https://cra.link/deployment
$ node postbuild.js
✨  Done in 12.41s.
```
> [ez][ts lint] remove unused statements in editor Client

- .github/workflows/publish_python_sdk.yml
[ez] gh action remove uneeded step
This github action does not need to store builds. It should be fine to build and publish within the same action
> [ez] gh action remove uneeded step

- vscode-extension/package.json
- vscode-extension/src/extension.ts
- vscode-extension/src/util.ts
[vscode] 1/n rename create new yaml -> create example yaml
VSCode extension needs to have a "create new empty" command. This diff just renames the current create new commands to create example.
rfc: Maybe this should be create template instead of "example" to be more explicit
https://github.com/lastmile-ai/aiconfig/assets/141073967/0f79234c-f62c-4df5-995c-9261e9013538
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1447).
* #1448
* __->__ #1447
> [vscode] 1/n rename create new yaml -> create example yaml

- .github/workflows/check_formatting.yml
- cookbooks/Claude-And-Azure/aiconfig_model_registry.py
- cookbooks/Groq/aiconfig_model_registry.py
- extensions/Gemini/python/src/aiconfig_extension_gemini/Gemini.py
- extensions/Groq/src/aiconfig_extension_groq/groq.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/automatic_speech_recognition.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/image_2_text.py
- gradio-notebook/backend/gradio_notebook/aiconfig_manager.py
- gradio-notebook/backend/gradio_notebook/events.py
- gradio-notebook/backend/gradio_notebook/gradio_notebook.py
- gradio-notebook/backend/gradio_notebook/utils.py
- gradio-notebook/frontend/config/examine.py
- gradio-notebook/model_parsers.py
- python/src/aiconfig/ChatCompletion.py
- python/src/aiconfig/__init__.py
- python/src/aiconfig/default_parsers/azure.py
- python/src/aiconfig/default_parsers/claude.py
- python/src/aiconfig/default_parsers/gemini.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/editor/example_aiconfig_model_registry.py
- python/src/aiconfig/editor/server/queue_iterator.py
- python/src/aiconfig/editor/server/server_utils.py
- python/src/aiconfig/eval/api/__init__.py
- python/src/aiconfig/eval/common.py
- python/src/aiconfig/eval/metrics.py
- python/src/aiconfig/util/params.py
- python/tests/test_registry.py
- vscode-extension/static/example_aiconfig_model_registry.py
[ci/cd] Python Formatting Check
blocks on merging 
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1458).
* __->__ #1458
* #1459
> [ci/cd] Python Formatting Check

- cookbooks/Claude-And-Azure/aiconfig_model_registry.py
- cookbooks/Groq/aiconfig_model_registry.py
- extensions/Gemini/python/src/aiconfig_extension_gemini/Gemini.py
- extensions/Groq/src/aiconfig_extension_groq/groq.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/local_inference/automatic_speech_recognition.py
- extensions/HuggingFace/python/src/aiconfig_extension_hugging_face/remote_inference_client/image_2_text.py
- gradio-notebook/backend/gradio_notebook/aiconfig_manager.py
- gradio-notebook/backend/gradio_notebook/events.py
- gradio-notebook/backend/gradio_notebook/gradio_notebook.py
- gradio-notebook/backend/gradio_notebook/utils.py
- gradio-notebook/frontend/config/examine.py
- gradio-notebook/model_parsers.py
- python/src/aiconfig/ChatCompletion.py
- python/src/aiconfig/__init__.py
- python/src/aiconfig/default_parsers/azure.py
- python/src/aiconfig/default_parsers/claude.py
- python/src/aiconfig/default_parsers/gemini.py
- python/src/aiconfig/default_parsers/openai.py
- python/src/aiconfig/editor/example_aiconfig_model_registry.py
- python/src/aiconfig/editor/server/queue_iterator.py
- python/src/aiconfig/editor/server/server_utils.py
- python/src/aiconfig/eval/api/__init__.py
- python/src/aiconfig/eval/common.py
- python/src/aiconfig/eval/metrics.py
- python/src/aiconfig/util/params.py
- python/tests/test_registry.py
- vscode-extension/static/example_aiconfig_model_registry.py
[ez] Run Formatting on Python Files
`black --exclude '/\.sl\b' . --line-length=79`
A lot of the python files checked into the AIConfig repo have not been formatted. This command formats all python files the same way vscode would do it in the repo.
I noticed differences between black version 23.11 and 24 (latest). I had version 23.11 on my local install. This also causes different behaviours when running autoformat through vscode instead of the command line, I'm fairly certain vscode extension uses the latest version of the package. I upgraded my black formatter local install to 24 (latest).
Note: black is python package.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pul …
> [ez] Run Formatting on Python Files

- python/requirements.txt
[Python sdk] Remove test dependencies from Main Package Dependencies
This PR updates the Python SDK package to minimize its dependency footprint.
This pr removes the following packages from the main package dependencies. These libraries are primarily used for testing purposes and are not necessary for the sdk's functionality.
- `pytest`
- `pytest-asyncio`
- `mock`
> [Python sdk] Remove test dependencies from Main Package Dependencies

- typescript/jest.config.ts
Fix Jest Tests
Summary: For some reason, the current `jest` command is running on /dist/ test files, which fails to parse the transpiled js. For example:
```
FAIL  dist/__tests__/parsers/hf/hf.test.js
HuggingFaceTextGeneration ModelParser
✕ uses HuggingFace API token from environment variable if it exists
✕ serializing params to config prompt
✕ serialize callbacks
✕ deserializing config prompt to params
✕ deserialize callbacks
✕ run prompt, non-streaming
✕ run prompt, streaming
✕ run callbacks
● HuggingFaceTextGeneration ModelParser › uses HuggingFace API token from environment variable if it exists
TypeError: mockedHfInference.mockClear is not a function
102 | describe("HuggingFaceTextGeneration ModelParser", () => {
103 |     beforeEach(() => {
> 104 | …
```
> Fix Jest Tests

- vscode-extension/editor/package.json
- vscode-extension/editor/src/VSCodeEditor.tsx
- vscode-extension/editor/src/utils/api.ts
- vscode-extension/editor/yarn.lock
Summary:
Update the aiconfig-editor package to include UI for global model settings. As part of this, add the code to connect the delete_model request. Note that the delete_model call doesn't work because aiconfig python package needs to be updates so that the server has the endpoint.
Test Plan:
Added global settings, system prompt "respond in capital letters" for gpt-3.5-turbo and it works as expected
> Update aiconfig-editor Package and Attach delete_model request/callback

- CHANGELOG.md
- python/pyproject.toml
- typescript/package.json
[March 18, 2024] CHANGELOG and version updates
TSIA
Summary:
Test Plan:
> [March 18, 2024] CHANGELOG and version updates

- vscode-extension/package.json
Summary: Bump the package version to include the global model settings and new/empty config commands.
Test Plan: `vsce package`, installed extension from `vscode-aiconfig-0.0.21.vsix` and tested out the changes successfully
> Bump vscode extension package version

- python/src/aiconfig/Config.py
- python/src/aiconfig/registry.py
- python/tests/test_registry.py
I wasn't really sure where else this change needed to be done. I added this error message in this registry code since it will be called by the same run_batch call that checks for prompts too
> Update to throw IndexError if model name not registered

- vscode-extension/editor/package.json
- vscode-extension/editor/src/VSCodeEditor.tsx
- vscode-extension/editor/src/utils/api.ts
- vscode-extension/editor/yarn.lock
Summary: Bump `aiconfig-editor` package to include the UI for deleting single output. Connect the callback in VSCodeEditor. Also, updated deleteModelSettings callback to properly notify document change
Test Plan: Tested deleting output (and global model settings) and seeing the change reflected in the config
> Update aiconfig-editor for Delete Output

- python/requirements.txt
[sdk] pin HuggingFaceHub Dependency
HuggingFace Hub Python library released breaking changes in version 0.22.0: https://github.com/huggingface/huggingface_hub/releases/tag/v0.22.0
This diff pins the version dependency of `huggingface_hub` to avoid the impact of the broken change.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1478).
* #1479
* __->__ #1478
> [sdk] pin HuggingFaceHub Dependency

- vscode-extension/package.json
- vscode-extension/python/requirements.txt
Summary: Bump the package version to match the extension published version
Test Plan:  Created VSIX package and tested locally. Deleting outputs works (no server error, save empty outputs array to config)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1481).
* __->__ #1481
* #1480
> Bump VSCode Extension Package Version for Publish

- python/pyproject.toml
Bump python-sdk
1.1.33 was silently pushed. This diff updates to 1.1.34
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1488).
* __->__ #1488
* #1487
* #1486
> Bump python-sdk

- aiconfig-docs/docs/gradio-notebook.md
Summary: Make the documentation clearer on which space to use. Auto-select gradio sdk (via url param) and clarify usage of blank template
> Update Gradio Space Documentation

- cookbooks/Basic-Prompt-Routing/README.md
Fix readme
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/1495).
* __->__ #1495
* #1494
* #1493
* #1492
> Fix readme
